export default [
"Palimpsest - a manuscript or document whose original writing has been erased and overwritten, yet traces of the earlier text remain and allow reconstruction of underlying layers of meaning.",
"Ubiquitous - existing or being encountered everywhere at once, to the point that its presence becomes assumed rather than noticed, as with digital connectivity or background noise in cities.",
"Sycophant - a person who flatters those in power to gain favor or advantage, often at the cost of sincerity or integrity, creating a distorted social environment around authority.",
"Entropy - a measure of disorder or randomness in a system, used to describe the natural tendency of systems to move from ordered states toward more probable and less organized configurations.",
"Anhedonia - the diminished ability to experience pleasure from activities that are normally found enjoyable, often associated with depressive states or neurological dysfunction.",
"Obfuscate - to deliberately make something unclear, confusing, or difficult to understand, especially to prevent criticism or avoid accountability in communication or decision-making.",
"Cynosure - something or someone that becomes the central focus of attention or admiration, not merely visible but compelling, drawing the eyes and intentions of others toward it.",
"Ephemeral - lasting for a very short time before quickly fading or disappearing, typically used to describe states, experiences, or phenomena that cannot be captured or preserved fully.",
"Maelstrom - a powerful and violent whirlpool capable of pulling things into its center, used metaphorically for chaotic situations that destroy structure or stability.",
"Apathy - a state of emotional indifference where stimuli that usually provoke interest or concern fail to elicit motivation, engagement, or response from the individual.",
"Iridescent - showing luminous colors that appear to shift or change when viewed from different angles, as seen in soap bubbles, bird feathers, or certain mineral surfaces.",
"Petrichor - the distinctive and pleasant earthy aroma that rises from dry soil when rain first falls, caused by oils released from plants and compounds formed by microbes.",
"Obsolete - no longer in general use or relevant because it has been replaced by something newer or more effective, though it may persist in archives or legacy systems.",
"Metamorphosis - a profound change in form, structure, or character, seen biologically in insects and metaphorically in processes of personal or social transformation.",
"Barometer - an instrument that measures atmospheric pressure, used to forecast short-term changes in weather and metaphorically to gauge shifts in opinion or conditions.",
"Parsimony - extreme unwillingness to spend resources, whether money, effort, or words, often producing minimal but functional outcomes at the cost of generosity or richness.",
"Mercurial - characterized by rapid and unpredictable changes in mood or behavior, reminiscent of quicksilver’s shifting nature, creating difficulty in anticipation or trust.",
"Vindictive - having or showing a desire to seek revenge, not merely remembering a wrong but actively aiming to punish or inflict harm in return.",
"Laconic - expressing ideas using very few words, resulting in speech that is concise to the point of austerity, often interpreted as confident, cold, or dismissive.",
"Vicissitude - a change of circumstances or fortune, especially one that is unwelcome or outside one’s control, emphasizing instability as a natural feature of life.",
"Zealot - a person who shows extreme and uncompromising devotion to a belief or cause, often rejecting moderation and disregarding opposing perspectives or consequences.",
"Erudite - having or showing extensive knowledge gained from reading and study, not merely informed but deeply learned in a way that shapes expression and analysis.",
"Dogmatic - inclined to present opinions as incontrovertible truths, resisting questioning or alternative views, diminishing open inquiry in discourse or institutions.",
"Transient - lasting only for a short time before passing away, especially of states or populations that exist briefly and leave limited trace once conditions shift.",
"Rescind - to revoke, cancel, or reverse a decision, law, or agreement, restoring the prior state or nullifying obligations previously in force.",
"Melancholia - a deep, persistent form of sadness not tied to immediate causes, historically described as a temperament and now associated with depressive affect.",
"Synecdoche - a figure of speech in which a part stands for the whole or the whole for a part, altering perspective by shifting representational scale.",
"Panacea - a hypothetical cure-all remedy capable of addressing every disease or problem, often invoked rhetorically to criticize naive or simplistic solutions.",
"Immutable - not capable of being changed or altered over time, whether by intention or force, often used to describe principles, mathematical truths, or code states.",
"Equanimity - a state of psychological composure and steadiness under stress or conflict, where emotional reactions remain measured rather than volatile or extreme.",
"Ambivalence - a state in which a person holds two opposing feelings or beliefs simultaneously, creating hesitation and difficulty in making decisions or committing to a single course.",
"Conflate - to merge two or more ideas, issues, or pieces of information into one in a way that obscures their distinctions and can mislead interpretation or analysis.",
"Denouement - the final phase of a narrative in which complicated plots are resolved and tensions are released, revealing consequences that follow the climax.",
"Equivocate - to speak in an intentionally vague or ambiguous way in order to avoid stating a clear position or to mislead without telling a direct falsehood.",
"Fastidious - showing extreme attention to detail and precision, often combined with a strong preference for order or cleanliness and a low tolerance for error.",
"Gregoriate - to reorganize or remodel a structure of thought, policy, or behavior in accordance with a new dominant principle, often replacing what was previously entrenched.",
"Heuristic - a practical method for solving problems or making decisions using experience-based strategies rather than exhaustive logic or guaranteed accuracy.",
"Inscrutable - impossible to interpret or understand due to the opacity of motive, expression, or structure, leaving observers uncertain about underlying meaning.",
"Juxtaposition - the placement of two elements side by side in order to highlight contrast, similarity, or tension that emerges only through their proximity.",
"Kaleidoscopic - rapidly shifting in pattern or appearance in a way that creates a sense of continual recomposition, like the shifting mirrors in a kaleidoscope.",
"Liminal - relating to a boundary or threshold between two states, phases, or identities, where transformation, ambiguity, or instability is naturally concentrated.",
"Manifesto - a formal written statement announcing principles, intentions, or demands of a movement or individual, intended to influence opinion or initiate change.",
"Nihilism - the belief that life lacks inherent meaning, purpose, or value, often paired with skepticism toward moral, religious, or political claims of truth.",
"Obsequious - showing exaggerated and excessive willingness to serve or obey, especially toward those with power, often perceived as humiliating or manipulative.",
"Paradox - a statement or situation that appears self-contradictory or absurd but may contain an underlying truth when examined from a deeper perspective.",
"Quixotic - driven by idealistic but unrealistic hopes or goals, often ignoring practical constraints and leading to noble but ineffective action.",
"Recalibrate - to adjust or reconfigure the parameters of a system, measurement, or strategy in order to restore accuracy or adapt to changed conditions.",
"Salient - standing out in a way that draws attention due to prominence, relevance, or clarity, making it the first feature perceived or recalled.",
"Transcendence - the act of surpassing ordinary limits of experience, thought, or condition, often associated with spiritual, intellectual, or artistic ascent.",
"Umbrage - a feeling of resentment or offense triggered by an implied slight or insult, even when the provocation is subtle or ambiguous.",
"Verisimilitude - the appearance of truth or realism in art, argument, or narrative, causing something fictional or constructed to feel convincingly authentic.",
"Whimsical - characterized by playful unpredictability or fanciful imagination, sometimes charming and sometimes erratic or impractical in consequence.",
"Xenophobia - fear or hostility toward foreigners or perceived outsiders, expressed through suspicion, rejection, or aggressive behavior at social or political levels.",
"Yoke - to bind two entities together physically or metaphorically in a way that restricts independence or forces alignment under shared burden or authority.",
"Zeitgeist - the defining spirit or intellectual climate of an era, reflected in its dominant values, anxieties, and cultural expressions.",
"Ameliorate - to make something bad or unsatisfactory better or more tolerable, not by eliminating the cause but by reducing its negative impact.",
"Capitulate - to surrender or give in after resistance, usually under pressure or inevitability, acknowledging loss of agency or strategic position.",
"Debacle - a sudden and disastrous failure that collapses a structure, plan, or reputation, leaving disorder and exposing underlying weaknesses.",
"Ennui - a feeling of deep boredom and weariness arising from a lack of occupation or stimulation, often accompanied by a sense of meaninglessness.",
"Furtive - behaving in a secretive or stealthy manner to avoid detection or scrutiny, implying that the concealed action would provoke disapproval if revealed.",
"Grandiose - appearing or intended to appear impressive, magnificent, or more important than is realistic, often reflecting exaggerated ambition or inflated self-perception.",
"Hegemony - the dominance of one state, ideology, or social group over others, maintained not only by force but by cultural influence, norms, and consent of the governed.",
"Iconoclast - a person who attacks or rejects established beliefs, traditions, or revered institutions, challenging what others consider untouchable or sacred.",
"Judicious - showing sound judgment based on reason, caution, and foresight rather than impulse, often visible in decisions taken under uncertainty.",
"Kafkaesque - resembling the absurdly oppressive, illogical, and nightmarish situations found in Kafka’s works, where individuals are trapped in senseless bureaucracy.",
"Lugubrious - excessively mournful or gloomy in manner, tone, or atmosphere in a way that feels heavy, theatrical, or drawn out.",
"Monolithic - large, uniform, and inflexible in structure or ideology, resisting modification and suppressing internal diversity or dissent.",
"Nebulous - lacking clear form, limits, or definition, whether referring to physical shapes, argument structures, or unfocused ideas.",
"Ontology - the branch of philosophy concerned with the nature of being, categories of existence, and the fundamental structure of reality.",
"Perfunctory - carried out with minimal effort or reflection merely to fulfill a duty or expectation, showing absence of engagement or sincerity.",
"Quintessence - the purest or most perfect embodiment of a quality or class, serving as the defining example against which others are measured.",
"Ramification - a consequence or secondary effect that branches out from an initial action or decision, often creating complex chains of impact.",
"Sanctimonious - displaying moral superiority or righteousness in a hypocritical or performative manner that invites irritation rather than respect.",
"Torque - a rotational force that causes twisting or turning, used literally in mechanics and metaphorically for forces that pivot opinion or policy.",
"Understate - to describe or present something as smaller or less serious than it is, often to soften impact, control narrative, or avoid alarm.",
"Vanguard - the leading edge of a movement, innovation, or transformation, composed of those who act or change before others follow.",
"Warrant - to justify or authorize an action or belief by supplying adequate grounds, legitimacy, or necessity for accepting or performing it.",
"Xeric - characterized by extremely dry conditions with minimal moisture, typically used of habitats, soils, or adaptive biological strategies.",
"Yield - to submit or give way to a force, argument, or circumstance, or to produce a measurable outcome in response to input over time.",
"Zenith - the highest or most successful point reached by a person, process, or phenomenon before decline or transformation begins.",
"Ambiguous - open to more than one interpretation because of vagueness or structural duality, generating uncertainty in inference or response.",
"Byzantine - highly complicated, layered, and difficult to navigate due to excessive detail, procedure, or concealment of intent.",
"Conundrum - a difficult problem or question with no clear solution, often complicated by conflicting constraints or missing information.",
"Didactic - intended to teach or convey instruction, sometimes with a tone that feels moralizing, prescriptive, or aesthetically heavy.",
"Extrapolate - to infer or predict beyond known data by extending observed patterns, accepting increased uncertainty with increasing distance.",
"Fidelity - loyalty or faithfulness to a person, standard, or obligation, or the degree of exactness with which something reproduces an original.",
"Glacial - extremely slow in pace or progress, or cold and distant in emotional tone, evoking the movement and chill of literal ice.",
"Hypothesis - a tentative explanatory statement that can be tested or refuted through observation, experiment, or logical deduction.",
"Inertia - the tendency of a system to resist change in its state or motion, persisting in existing trajectory unless acted upon by external force.",
"Juxtapose - to place elements side by side so that contrast or correspondence becomes perceptible only through their adjacency.",
"Adjudicate - to make a formal judgment or decision about a dispute or claim, typically within a legal or institutional framework that confers authority on the decision-maker.",
"Antagonist - a person, force, or principle that actively opposes or creates conflict for another agent or protagonist, shaping the dynamics of struggle or resistance.",
"Belligerent - showing readiness to fight or engage in conflict, either through hostile attitude or active participation in warfare or aggressive confrontation.",
"Cacophony - a harsh and discordant mixture of sounds perceived as unpleasant or overwhelming, often used metaphorically for chaotic or misaligned interactions.",
"Canonize - to formally declare someone a saint or to treat a text or figure as authoritative and beyond criticism within a tradition or intellectual lineage.",
"Chiaroscuro - the interplay of light and shadow that produces dramatic contrast in visual art, emphasizing depth, volume, and emotional intensity.",
"Coercion - the act of compelling someone to act against their will by use of force, threats, or pressure that removes the condition of free consent.",
"Convalesce - to gradually recover strength and health after illness or medical intervention through rest, stabilization, and controlled activity.",
"Deference - respectful submission to the judgment, opinion, or authority of another person, motivated by recognition of status, expertise, or hierarchy.",
"Dogma - a principle or set of beliefs presented as authoritative and unquestionable within a system, upheld without tolerance for challenge or revision.",
"Emulate - to match or surpass a model or competitor through imitation combined with improvement, driven by ambition rather than replication alone.",
"Epitaph - an inscription or brief text written in memory of a deceased person, typically engraved on a tombstone and summarizing identity or legacy.",
"Exegesis - the critical interpretation of a text, especially one of religious or canonical status, aiming to extract intended meaning through reasoned analysis.",
"Falsifiable - capable of being disproven through observation or experiment, marking a claim as scientifically testable rather than merely asserted.",
"Gravitas - a serious and weighty manner that conveys intellectual depth, social authority, or moral significance in speech, posture, or decision.",
"Hapless - experiencing persistent misfortune or failure despite the absence of intention or fault, drawing attention to circumstance rather than competence.",
"Heresy - a belief or assertion that departs from established doctrine within a tradition, perceived as a threat to orthodoxy or institutional coherence.",
"Homogeneous - composed of parts or members that are alike in nature or characteristics, reducing internal variation and producing uniform behavior.",
"Ineffable - too great, intense, or subtle to be adequately expressed in words, standing beyond the limits of linguistic representation.",
"Inveigh - to speak or write with great hostility or indignation against something perceived as wrong, using forceful accusation or denunciation.",
"Jurisprudence - the theory or philosophy of law that examines the principles, sources, and logic underlying legal systems and reasoning.",
"Linearize - to simplify a phenomenon by approximating its behavior as linear, reducing complexity for analysis while sacrificing nuanced accuracy.",
"Litotes - a rhetorical device in which an affirmative idea is expressed by negating its opposite, producing understatement as a mode of emphasis.",
"Macabre - having a grim or disturbing quality linked to death, decay, or grotesque imagery, provoking fascination entwined with discomfort.",
"Mnemonic - a method or device used to aid memory retention by associating information with patterns that are easier to recall than the raw data itself.",
"Normative - concerned with establishing standards of what ought to be rather than describing what is, prescribing ideals rather than recording facts.",
"Ontogeny - the development of an individual organism from its earliest stage to maturity, tracing structural and functional transformations over time.",
"Pathos - a quality in communication that evokes pity, sorrow, or deep emotion in an audience by appealing to vulnerability and shared human frailty.",
"Perennial - enduring or recurring repeatedly over long duration without significant decline, whether referring to plants, debates, or structural problems.",
"Probative - having the quality of proving or demonstrating something, especially evidence that is relevant and sufficient to influence a legal or rational conclusion.",




]