const allNames = {
'Proverb': "",
'Idioms': "",
'Historical fact': "",
'Interesting fact': "",
'Fact about space': "",
'Interesting Fact': "",
'Ralph Waldo Emerson': "American poet, philosopher, and essayist",
'Scientific fact': "",
'Mark Twain': "American writer, humorist",
'Animal fact': "",
'Fact about food': "",
'idioms': "",
'George Bernard Shaw': "Irish playwright, critic, and essayist",
'Fact about sports': "",
'Oscar Wilde': "Irish writer and poet",
'Fact about the world': "",
'Thomas Jefferson': "Third President of the United States",
'Charles Dickens': "English writer and social critic",
'Fact about arts': "",
'Fact about jobs': "",
'Joke': "",
'William Shakespeare': "English playwright, poet, and actor",
'Albert Schweitzer': "German-French organist and physician",
'Russian proverb': "",
'Elvis Presley': "American singer, musician, and actor",
'Fact about politics': "",
'Forrest Gump': "",
'Robert Frost': "American poet",
'Johann Wolfgang von Goethe': "German poet, novelist, and playwright",
'Steve Jobs': "American businessman, inventor, and investor",
'Life hack': "",
'Fact about flora': "",
'Henry David Thoreau': "American transcendentalist writer, philosopher",
'Nelson Mandela': "South African activist and politician",
'R. Kelly': "American singer and record producer",
'The Godfather Part II': "Film, 1974",
'A. A. Milne': "English poet, novelist",
'The Beatles': "English rock band",
'The Wizard of Oz': "",
'Henry Wadsworth Longfellow': "American poet, novelist",
'Who Framed Roger Rabbit': "Film, 1988",
'Gustave Flaubert': "French novelist",
'Fact about economics': "",
'Wolfgang Amadeus Mozart': "Composer of the Classical period",
'On the Waterfront': "Film, 1954",
'George Herbert': "English poet, clergyman, and hymnwriter",
'Justin Bieber': "Canadian singer, songwriter, and actor",
'Notting Hill': "Film, 1999",
'R. Buckminster Fuller': "American architect, designer, and author",
'Knute Rockne': "American football coach",
'Stanley Coren': "Canadian psychologist and author",
'English lullaby': "English lullaby",
'Lullaby': "Lullaby",
'Julius Caesar': "Roman politician and general",
'Taxi Driver': "Film, 1976",
'Benjamin Franklin': "American statesman, inventor, and scientist",
'Wall Street': "Film, 1987",
'Beau Taplin': "American actor",
'The Stand': "Film, 1994",
'Anais Nin': "French-American author, poet, and diarist",
'The History of Mr. Polly': "Novel, 1910",
'Breaking Bad': "Film, 2008",
'George Burns': "American actor, comedian, and singer",
'Life Hack': "",
'Emile Zola': "French novelist and journalist",
'Wonder Woman ': "Film, 2017",
'Shania Twain': "Canadian singer, songwriter, and actress",
'Leon Trotsky': "Russian revolutionary",
'George Orwell': "English novelist and critic",
'Thich Nhat Hanh': "Vietnamese Buddhist monk",
'Walter Winchell': "American radio personality",
'The Notebook': "Film, 2004",
'Agnes Repplier': "American writer and critic",
'Jean Cocteau': "French poet and filmmaker",
'Dead Poets Society': "Film, 1989",
'Walt Whitman': "American poet, journalist, and editor",
'German law': "German law",
'Plato': "Greek philosopher",
'Henry Ford': "American businessman",
'Nicolaus Copernicus': "Polish astronomer, mathematician",
'Harry Potter': "Film, 2001",
'African proverb': "African proverb",
'Lucy Maud Montgomery': "Canadian author",
'Lily Leung': "Hong Kong actress",
'To Kill a Mockingbird': "Film, 1962",
'Mexican proverb': "",
'Dr. John Bradshaw': "English author and broadcaster",
'Immanuel Kant': "German philosopher",
'Popular myth': "Popular myth",
'Benjamin Mays': "American educator",
'J.K. Rowling': "British author",
'Theodore Roosevelt': "26th President of the United States",
'Stirling Moss': "British racing driver",
'Joel Osteen': "American televangelist",
'Confucius': "Chinese philosopher",
'Martin Luther King Jr.': "American civil rights activist",
'Invisible Man': "Novel, 1952",
'Antoine de Saint-Exupéry': "French writer and aviator",
'Zhuangzi': "Chinese philosopher",
'Neil Armstrong': "First man to walk on the moon",
'Socrates': "Greek philosopher",
'George Washington': "First President of the United States",
'Wassily Kandinsky': "Russian painter and art theorist",
'The Lord of the Rings': "Film, 2001",
'John Barrymore': "American actor",
'Gilbert Keith Chesterton': "English writer and critic",
'Fact about relaxation': "",
'Dwight D. Eisenhower': "34th President of the United States",
'Nicole Richie': "American actress and singer",
'Ernest Hemingway': "American novelist",
'Winston Churchill': "British statesman and prime minister",
'Dr. Seuss': "American children's author",
'Friedrich Nietzsche': "German philosopher",
'Osho': "Indian spiritual leader",
'Francis Bacon': "English philosopher, statesman",
'Laozi': "Chinese philosopher",
'Barbara Kingsolver': "American novelist and essayist",
'Greek proverb': "Greek proverb",
'Epictetus': "Greek philosopher",
'Pablo Picasso': "Spanish painter, sculptor",
'Braveheart': "Film, 1995",
'Kate Douglas Wiggin': "American novelist and playwright",
'Marcus Aurelius': "Roman emperor and philosopher",
'Voltaire': "French philosopher, writer",
'Samuel Butler': "English writer and critic",
'Fact about music': "Fact about music",
'Robert Louis Stevenson': "Scottish novelist",
'The Pursuit of Happyness': "Film, 2006",
'Emanuel Lasker': "German chess player and composer",
'Lao Tzu': "Chinese philosopher",
'Horatio Nelson': "British naval officer",
'Albert Einstein': "German-born theoretical physicist",
'Fact about Surma': "",
'Japanese law': "Japanese law",
'George Matthew Adams': "American writer and critic",
'Mark Halperin': "American political commentator",
'Chinese proverb': "Chinese proverb",
'Samuel Taylor Coleridge': "English poet, novelist, and critic",
'Pericles': "Greek statesman",
'Desmond Tutu': "South African Anglican priest",
'Lucius Annaeus Seneca': "Roman philosopher"
}