export default [
  "Palimpsesto: un manuscrito o documento cuyo texto original ha sido borrado y sobreescrito, pero aún quedan rastros del texto anterior que permiten reconstruir capas subyacentes de significado.",
  "Omnipresente: que existe o se encuentra en todas partes a la vez, hasta el punto de que su presencia se asume en lugar de notarse, como ocurre con la conectividad digital o el ruido de fondo en las ciudades.",
  "Sycophant: una persona que adula a los que están en el poder para ganar favor o ventaja, a menudo a costa de la sinceridad o la integridad, creando un entorno social distorsionado alrededor de la autoridad.",
  "Entropía - una medida del desorden o aleatoriedad en un sistema, utilizada para describir la tendencia natural de los sistemas a pasar de estados ordenados hacia configuraciones más probables y menos organizadas.",
  "Anhedonia: la capacidad disminuida para experimentar placer en actividades que normalmente se consideran placenteras, a menudo asociada con estados depresivos o disfunciones neurológicas.",
  "Ofuscar - hacer deliberadamente algo poco claro, confuso o difícil de entender, especialmente para evitar críticas o eludir la responsabilidad en la comunicación o la toma de decisiones.",
  "Cynosure: algo o alguien que se convierte en el centro de atención o admiración, no solo visible sino también atractivo, que atrae las miradas y la intención de los demás hacia él.",
  "Efímero: que dura muy poco tiempo antes de desvanecerse o desaparecer rápidamente, generalmente utilizado para describir estados, experiencias o fenómenos que no pueden ser capturados o preservados completamente.",
  "Maelstrom: un remolino poderoso y violento capaz de atraer objetos hacia su centro, usado metafóricamente para situaciones caóticas que destruyen la estructura o la estabilidad.",
  "La apatía es un estado de indiferencia emocional en el que los estímulos que normalmente provocan interés o preocupación no logran generar motivación, participación o respuesta por parte del individuo.",
  "Iridescente - que muestra colores luminosos que parecen cambiar o desplazarse cuando se observan desde diferentes ángulos, como se ve en las burbujas de jabón, las plumas de los pájaros o ciertas superficies minerales.",
  "Petrichor: el aroma terroso distintivo y agradable que surge del suelo seco cuando cae la primera lluvia, causado por aceites liberados por las plantas y compuestos formados por microbios.",
  "Obsoleto: ya no se usa comúnmente ni es relevante porque ha sido reemplazado por algo más nuevo o efectivo, aunque puede persistir en archivos o sistemas heredados.",
  "Metamorfosis: un cambio profundo en la forma, estructura o carácter, observado biológicamente en los insectos y metafóricamente en procesos de transformación personal o social.",
  "Barómetro: un instrumento que mide la presión atmosférica, utilizado para prever cambios meteorológicos a corto plazo y, metafóricamente, para evaluar cambios en la opinión o en las condiciones.",
  "Parsimonia: extrema falta de disposición a gastar recursos, ya sean dinero, esfuerzo o palabras, que a menudo produce resultados mínimos pero funcionales a costa de la generosidad o la riqueza.",
  "Mercurial: caracterizado por cambios rápidos e impredecibles en el estado de ánimo o comportamiento, que recuerdan a la naturaleza cambiante del mercurio, creando dificultad para anticipar o confiar.",
  "Vengativo - que tiene o muestra un deseo de buscar venganza, no solo recordando una ofensa sino apuntando activamente a castigar o infligir daño en respuesta.",
  "Lacónico: expresar ideas utilizando muy pocas palabras, lo que resulta en un discurso conciso hasta el punto de la austeridad, a menudo interpretado como seguro, frío o despectivo.",
  "Vicisitud - un cambio de circunstancias o fortuna, especialmente uno que es indeseado o está fuera del control de uno, enfatizando la inestabilidad como una característica natural de la vida.",
  "Fanático: una persona que muestra una devoción extrema e intransigente a una creencia o causa, a menudo rechazando la moderación y desestimando las perspectivas opuestas o las consecuencias.",
  "Erudito - que posee o demuestra un conocimiento extenso adquirido mediante la lectura y el estudio, no simplemente informado sino profundamente aprendido de una manera que moldea la expresión y el análisis.",
  "Dogmático: inclinado a presentar opiniones como verdades incontrovertibles, resistiéndose a cuestionamientos o puntos de vista alternativos, lo que disminuye la indagación abierta en el discurso o las instituciones.",
  "Transitorio: que dura solo un corto tiempo antes de desaparecer, especialmente en referencia a estados o poblaciones que existen brevemente y dejan una huella limitada una vez que las condiciones cambian.",
  "Rescindir: revocar, cancelar o revertir una decisión, ley o acuerdo, restaurando el estado anterior o anulando obligaciones que antes estaban vigentes.",
  "Melancolía: una forma profunda y persistente de tristeza no vinculada a causas inmediatas, históricamente descrita como un temperamento y ahora asociada con un afecto depresivo.",
  "Sinécdoque: una figura retórica en la que una parte representa al todo o el todo representa a una parte, alterando la perspectiva al cambiar la escala representacional.",
  "Panacea: un remedio hipotético capaz de curar todas las enfermedades o problemas, a menudo invocado retóricamente para criticar soluciones ingenuas o simplistas.",
  "Inmutable: que no puede ser cambiado o alterado con el tiempo, ya sea por intención o por fuerza, a menudo utilizado para describir principios, verdades matemáticas o estados de código.",
  "Ecuanimidad: un estado de compostura psicológica y estabilidad bajo estrés o conflicto, donde las reacciones emocionales se mantienen medidas en lugar de volátiles o extremas.",
  "Ambivalencia: un estado en el que una persona sostiene simultáneamente dos sentimientos o creencias opuestas, creando vacilación y dificultad para tomar decisiones o comprometerse con un solo curso de acción.",
  "Confluir: fusionar dos o más ideas, temas o fragmentos de información en uno solo de manera que se oscurezcan sus diferencias y se pueda inducir a error en la interpretación o el análisis.",
  "Desenlace: la fase final de una narrativa en la que se resuelven tramas complicadas y se liberan tensiones, revelando las consecuencias que siguen al clímax.",
  "Equivocar - hablar de manera intencionadamente vaga o ambigua para evitar expresar una posición clara o para engañar sin decir una falsedad directa.",
  "Meticuloso: que muestra una atención extrema al detalle y la precisión, a menudo combinada con una fuerte preferencia por el orden o la limpieza y una baja tolerancia al error.",
  "Gregoriate: reorganizar o remodelar una estructura de pensamiento, política o comportamiento de acuerdo con un nuevo principio dominante, a menudo reemplazando lo que antes estaba arraigado.",
  "Heurístico: un método práctico para resolver problemas o tomar decisiones utilizando estrategias basadas en la experiencia en lugar de una lógica exhaustiva o precisión garantizada.",
  "Inescrutable: imposible de interpretar o entender debido a la opacidad del motivo, la expresión o la estructura, lo que deja a los observadores inseguros sobre el significado subyacente.",
  "Yuxtaposición: la colocación de dos elementos uno junto al otro para resaltar el contraste, la similitud o la tensión que surge únicamente a través de su proximidad.",
  "Caleidoscópico - que cambia rápidamente su patrón o apariencia de manera que crea una sensación de recomposición continua, como los espejos cambiantes en un caleidoscopio.",
  "Liminal - relacionado con un límite o umbral entre dos estados, fases o identidades, donde la transformación, la ambigüedad o la inestabilidad se concentran naturalmente.",
  "Manifiesto - una declaración formal por escrito que anuncia los principios, intenciones o demandas de un movimiento o individuo, destinada a influir en la opinión o a iniciar un cambio.",
  "Nihilismo: la creencia de que la vida carece de un significado, propósito o valor inherente, a menudo acompañada de escepticismo hacia las afirmaciones morales, religiosas o políticas de verdad.",
  "Servil - que muestra una disposición exagerada y excesiva para servir u obedecer, especialmente hacia quienes tienen poder, a menudo percibido como humillante o manipulador.",
  "Paradoja: una afirmación o situación que parece autocontradictoria o absurda, pero que puede contener una verdad subyacente cuando se examina desde una perspectiva más profunda.",
  "Quijotesco - impulsado por esperanzas o metas idealistas pero poco realistas, a menudo ignorando las limitaciones prácticas y conduciendo a una acción noble pero ineficaz.",
  "Recalibrar - ajustar o reconfigurar los parámetros de un sistema, medición o estrategia para restaurar la precisión o adaptarse a condiciones cambiantes.",
  "Saliente - que destaca de manera que llama la atención debido a su prominencia, relevancia o claridad, convirtiéndose en la primera característica percibida o recordada.",
  "Trascendencia: el acto de superar los límites ordinarios de la experiencia, el pensamiento o la condición, a menudo asociado con el ascenso espiritual, intelectual o artístico.",
  "Umbrage: una sensación de resentimiento u ofensa provocada por un desprecio o insulto implícito, incluso cuando la provocación es sutil o ambigua.",
  "Verosimilitud: la apariencia de verdad o realismo en el arte, el argumento o la narrativa, que hace que algo ficticio o construido parezca auténticamente convincente.",
  "Caprichoso - caracterizado por una imprevisibilidad juguetona o una imaginación fantasiosa, a veces encantador y otras veces errático o poco práctico como consecuencia.",
  "La xenofobia es el miedo u hostilidad hacia los extranjeros o personas percibidas como ajenas, expresado a través de la sospecha, el rechazo o un comportamiento agresivo en niveles sociales o políticos.",
  "Yugo: unir dos entidades física o metafóricamente de manera que se restrinja la independencia o se obligue a la alineación bajo una carga o autoridad compartida.",
  "Zeitgeist: el espíritu definitorio o clima intelectual de una época, reflejado en sus valores dominantes, ansiedades y expresiones culturales.",
  "Ameliorar: hacer que algo malo o insatisfactorio sea mejor o más tolerable, no eliminando la causa, sino reduciendo su impacto negativo.",
  "Capitular - rendirse o ceder después de resistir, usualmente bajo presión o inevitabilidad, reconociendo la pérdida de autonomía o posición estratégica.",
  "Debacle: un fracaso repentino y desastroso que derrumba una estructura, plan o reputación, dejando desorden y exponiendo debilidades subyacentes.",
  "Ennui: una sensación de profundo aburrimiento y fatiga que surge de la falta de ocupación o estimulación, a menudo acompañada de una sensación de falta de sentido.",
  "Furtivo - comportarse de manera secreta o sigilosa para evitar ser detectado o examinado, implicando que la acción oculta provocaría desaprobación si fuera revelada.",
  "Grandioso - que aparenta o pretende aparentar ser impresionante, magnífico o más importante de lo que es realista, a menudo reflejando una ambición exagerada o una auto-percepción inflada.",
  "Hegemonía: el dominio de un estado, ideología o grupo social sobre otros, mantenido no solo por la fuerza sino también por la influencia cultural, las normas y el consentimiento de los gobernados.",
  "Iconoclasta: una persona que ataca o rechaza creencias establecidas, tradiciones o instituciones veneradas, desafiando lo que otros consideran intocable o sagrado.",
  "Juicioso: que muestra un juicio sólido basado en la razón, la precaución y la previsión en lugar de en el impulso, a menudo visible en decisiones tomadas bajo incertidumbre.",
  "Kafkiano: que se asemeja a las situaciones absurdamente opresivas, ilógicas y de pesadilla presentes en las obras de Kafka, donde los individuos están atrapados en una burocracia sin sentido.",
  "Lúgubre: excesivamente triste o sombrío en el modo, tono o atmósfera, de una manera que se siente pesada, teatral o prolongada.",
  "Monolítico: grande, uniforme e inflexible en estructura o ideología, resistiéndose a la modificación y suprimiendo la diversidad interna o la disidencia.",
  "Nebuloso: que carece de forma clara, límites o definición, ya sea refiriéndose a formas físicas, estructuras argumentativas o ideas poco enfocadas.",
  "Ontología: la rama de la filosofía que se ocupa de la naturaleza del ser, las categorías de la existencia y la estructura fundamental de la realidad.",
  "Superficial: realizado con un esfuerzo o reflexión mínimos, simplemente para cumplir con un deber o expectativa, mostrando ausencia de compromiso o sinceridad.",
  "Quintessence: la encarnación más pura o perfecta de una cualidad o clase, que sirve como el ejemplo definitivo contra el cual se miden los demás.",
  "Ramificación: una consecuencia o efecto secundario que se ramifica a partir de una acción o decisión inicial, a menudo creando cadenas complejas de impacto.",
  "Santurrón - mostrar superioridad moral o rectitud de manera hipócrita o performativa que provoca irritación en lugar de respeto.",
  "Torque: una fuerza rotacional que provoca torsión o giro, utilizada literalmente en mecánica y metafóricamente para fuerzas que cambian la opinión o la política.",
  "Subestimar: describir o presentar algo como más pequeño o menos serio de lo que realmente es, a menudo para suavizar el impacto, controlar la narrativa o evitar alarmas.",
  "Vanguardia: la punta de lanza de un movimiento, innovación o transformación, compuesta por aquellos que actúan o cambian antes de que otros los sigan.",
  "Garantizar - justificar o autorizar una acción o creencia proporcionando fundamentos adecuados, legitimidad o necesidad para aceptarla o llevarla a cabo.",
  "Xérico - caracterizado por condiciones extremadamente secas con humedad mínima, típicamente utilizado para hábitats, suelos o estrategias biológicas adaptativas.",
  "Ceder: someterse o dar paso a una fuerza, argumento o circunstancia, o producir un resultado medible en respuesta a una entrada a lo largo del tiempo.",
  "Zenith: el punto más alto o exitoso alcanzado por una persona, proceso o fenómeno antes de que comience el declive o la transformación.",
  "Ambiguo: abierto a más de una interpretación debido a la vaguedad o a la dualidad estructural, generando incertidumbre en la inferencia o respuesta.",
  "Bizantino - altamente complicado, estratificado y difícil de navegar debido a un exceso de detalles, procedimientos o al ocultamiento de la intención.",
  "Enigma: un problema o cuestión difícil sin una solución clara, a menudo complicada por restricciones conflictivas o información faltante.",
  "Didáctico - destinado a enseñar o transmitir instrucción, a veces con un tono que puede parecer moralizante, prescriptivo o estéticamente cargado.",
  "Extrapolar: inferir o predecir más allá de los datos conocidos extendiendo los patrones observados, aceptando una mayor incertidumbre a medida que aumenta la distancia.",
  "Fidelidad: lealtad o fidelidad hacia una persona, norma u obligación, o el grado de exactitud con que algo reproduce un original.",
  "Glacial: extremadamente lento en el ritmo o progreso, o frío y distante en el tono emocional, evocando el movimiento y el frío del hielo literal.",
  "Hipótesis: una declaración explicativa tentativa que puede ser probada o refutada mediante la observación, el experimento o la deducción lógica.",
  "Inercia: la tendencia de un sistema a resistir el cambio en su estado o movimiento, persistiendo en la trayectoria existente a menos que sea actuado por una fuerza externa.",
  "Yuxtaponer: colocar elementos uno al lado del otro de manera que el contraste o la correspondencia se haga perceptible únicamente a través de su proximidad.",
  "Adjudicar: tomar una decisión o dictamen formal sobre una disputa o reclamo, normalmente dentro de un marco legal o institucional que confiere autoridad al encargado de tomar la decisión.",
  "Antagonista: una persona, fuerza o principio que se opone activamente o genera conflicto a otro agente o protagonista, moldeando la dinámica de la lucha o resistencia.",
  "Beligerante: que muestra disposición para pelear o involucrarse en un conflicto, ya sea a través de una actitud hostil o de la participación activa en la guerra o en una confrontación agresiva.",
  "Cacofonía: una mezcla áspera y discordante de sonidos percibida como desagradable o abrumadora, a menudo utilizada metafóricamente para interacciones caóticas o desalineadas.",
  "Canonizar - declarar formalmente a alguien santo o tratar un texto o figura como autoritativo y fuera de crítica dentro de una tradición o línea intelectual.",
  "Claroscuro: la interacción de la luz y la sombra que produce un contraste dramático en el arte visual, enfatizando la profundidad, el volumen y la intensidad emocional.",
  "Coerción - el acto de obligar a alguien a actuar en contra de su voluntad mediante el uso de la fuerza, amenazas o presiones que eliminan la condición de consentimiento libre.",
  "Convalecer: recuperarse gradualmente la fuerza y la salud después de una enfermedad o intervención médica mediante el descanso, la estabilización y la actividad controlada.",
  "Deferencia: sumisión respetuosa al juicio, opinión o autoridad de otra persona, motivada por el reconocimiento del estatus, la experiencia o la jerarquía.",
  "Dogma: un principio o conjunto de creencias presentados como autoritativos e incuestionables dentro de un sistema, sostenidos sin tolerancia a desafíos o revisiones.",
  "Emular: igualar o superar un modelo o competidor mediante la imitación combinada con la mejora, impulsado por la ambición más que por la mera réplica.",
  "Epígrafe - una inscripción o breve texto escrito en memoria de una persona fallecida, típicamente grabado en una lápida y que resume la identidad o legado.",
  "Exégesis: la interpretación crítica de un texto, especialmente uno de estatus religioso o canónico, con el objetivo de extraer el significado intencionado mediante un análisis razonado.",
  "Falsable: capaz de ser refutado mediante observación o experimento, lo que convierte una afirmación en científicamente comprobable en lugar de simplemente declarada.",
  "Gravitas: una manera seria y solemne que transmite profundidad intelectual, autoridad social o importancia moral en el discurso, la postura o la decisión.",
  "Desdichado - que experimenta una mala suerte o fracaso persistente a pesar de la ausencia de intención o culpa, destacando las circunstancias más que la competencia.",
  "Herejía: una creencia o afirmación que se aparta de la doctrina establecida dentro de una tradición, percibida como una amenaza para la ortodoxia o la coherencia institucional.",
  "Homogéneo: compuesto por partes o miembros que son semejantes en naturaleza o características, reduciendo la variación interna y produciendo un comportamiento uniforme.",
  "Inefable - demasiado grande, intenso o sutil para ser expresado adecuadamente con palabras, trascendiendo los límites de la representación lingüística.",
  "Inveigh: hablar o escribir con gran hostilidad o indignación contra algo que se percibe como incorrecto, utilizando acusaciones o denuncias contundentes.",
  "La jurisprudencia es la teoría o filosofía del derecho que examina los principios, las fuentes y la lógica subyacentes en los sistemas legales y el razonamiento jurídico.",
  "Linealizar: simplificar un fenómeno aproximando su comportamiento como lineal, reduciendo la complejidad para el análisis a costa de sacrificar la precisión matizada.",
  "Litotes: un recurso retórico en el que una idea afirmativa se expresa negando su opuesto, produciendo una atenuación como modo de énfasis.",
  "Macabro: que posee una cualidad sombría o perturbadora vinculada a la muerte, la decadencia o imágenes grotescas, que provoca una fascinación entrelazada con el malestar.",
  "Nemónico: un método o dispositivo utilizado para ayudar a la retención de la memoria asociando la información con patrones que son más fáciles de recordar que los datos en bruto en sí mismos.",
  "Normativo: se ocupa de establecer normas sobre lo que debería ser en lugar de describir lo que es, prescribiendo ideales en lugar de registrar hechos.",
  "Ontogenia: el desarrollo de un organismo individual desde sus primeras etapas hasta la madurez, rastreando las transformaciones estructurales y funcionales a lo largo del tiempo.",
  "Pathos: una cualidad en la comunicación que evoca compasión, tristeza o una emoción profunda en una audiencia al apelar a la vulnerabilidad y a la fragilidad humana compartida.",
  "Perenne - que perdura o se repite continuamente a lo largo de un largo período sin un declive significativo, ya sea refiriéndose a plantas, debates o problemas estructurales.",
  "Probatorio: que posee la cualidad de probar o demostrar algo, especialmente evidencia que es relevante y suficiente para influir en una conclusión legal o racional."
];
