export default {
  "Nelson Mandela": "South African anti-apartheid leader and former president.",
  "Proverb": "A concise traditional saying expressing a general truth or advice.",
  "R. Kelly": "American singer and songwriter known for R&B hits and controversies",
  "Fact about space": "Information related to the universe beyond Earth’s atmosphere.",
  "The Godfather Part II": "Second film in The Godfather series, exploring crime and family legacy",
  "A. A. Milne": "English author best known for creating Winnie-the-Pooh.",
  "The Beatles": "Iconic British rock band known for pioneering music and culture.",
  "Idioms": "Phrases with figurative meanings different from literal words",
  "The Wizard of Oz": "Classic American fantasy film about a girl's journey in a magical land",
  "Henry Wadsworth Longfellow": "American poet known for narrative poems and lyric poetry.",
  "Who Framed Roger Rabbit": "A film blending live-action and animation featuring a detective and a ",
  "Oscar Wilde": "Irish poet and playwright known for wit and works like The Picture of ",
  "Gustave Flaubert": "French novelist known for writing 'Madame Bovary'",
  "Fact about economics": "General information related to the study of production, consumption, a",
  "Wolfgang Amadeus Mozart": "Renowned Austrian composer known for classical symphonies and operas.",
  "William Shakespeare": "English playwright and poet, author of many classic plays",
  "On the Waterfront": "A classic film about corruption on New York docks.",
  "George Herbert": "English poet and Anglican priest known for devotional poetry.",
  "Scientific fact": "A verifiable observation or principle confirmed by scientific method.",
  "Justin Bieber": "Canadian singer and pop star known for hits like 'Baby'.",
  "Notting Hill": "Romantic comedy film set in London starring Hugh Grant and Julia Rober",
  "Mark Twain": "American writer known for 'Adventures of Huckleberry Finn'",
  "R. Buckminster Fuller": "American architect and inventor known for geodesic domes",
  "Fact about food": "Information regarding edible substances and their consumption.",
  "Fact about the world": "Information that is true about the Earth or global events.",
  "Knute Rockne": "Legendary American football coach known for Notre Dame success.",
  "Thomas Jefferson": "Third president of the US and principal author of the Declaration of I",
  "Stanley Coren": "Psychologist and author known for research on dogs and human behavior.",
  "Charles Dickens": "English writer known for classic novels like Oliver Twist and Great Ex",
  "English lullaby": "A traditional soothing song sung to children to help them sleep.",
  "Lullaby": "A soothing song used to lull children to sleep.",
  "Albert Schweitzer": "Alsatian theologian, musician, and humanitarian known for philosophy o",
  "Ralph Waldo Emerson": "American essayist, lecturer, and poet promoting transcendentalism",
  "Russian proverb": "Traditional Russian sayings expressing cultural wisdom.",
  "Elvis Presley": "American singer and cultural icon known as the 'King of Rock and Roll'",
  "Julius Caesar": "Roman general and dictator, key figure in the end of the Roman Republi",
  "Interesting Fact": "A piece of information that captures attention due to its uniqueness.",
  "Taxi Driver": "A film about a mentally unstable veteran working as a taxi driver.",
  "Benjamin Franklin": "One of the Founding Fathers of the United States, polymath and invento",
  "Fact about arts": "Information or truths related to various forms of art.",
  "idioms": "Common phrases with meanings different from their literal words.",
  "Wall Street": "Drama film about finance and stock market dynamics.",
  "Fact about politics": "Information related to governance and public decision-making.",
  "Beau Taplin": "Australian poet and writer known for inspirational quotes and verses.",
  "The Stand": "Post-apocalyptic novel by Stephen King about a deadly plague and survi",
  "Anais Nin": "Writer known for diaries and erotic literature",
  "The History of Mr. Polly": "A novel by H.G. Wells about a man's life and adventures.",
  "Breaking Bad": "American TV series about a chemistry teacher turned meth producer.",
  "George Burns": "American comedian and actor known for his cigar and wit.",
  "Life Hack": "Tips and tricks to improve daily efficiency and solve problems",
  "Emile Zola": "French novelist and critic, key figure in literary naturalism.",
  "Wonder Woman ": "Iconic DC superheroine known for strength and compassion",
  "Life hack": "Tips and tricks to improve daily life efficiency.",
  "Walt Disney": "American entrepreneur and animator, founder of The Walt Disney Company",
  "Dr. Seuss": "American author known for children's books with imaginative characters",
  "Animal fact": "Concise true information about animals.",
  "Interesting fact": "A piece of information that is surprising or unusual.",
  "Moliere": "French playwright and actor, master of comedic drama.",
  "Tony Gaskins": "Motivational speaker and relationship coach.",
  "Alfred Tennyson": "British poet known for works like \"The Charge of the Light Brigade\".",
  "Epictetus": "Ancient Greek Stoic philosopher known for teachings on ethics and resi",
  "Samuel Butler": "English author known for satirical works and novel Erewhon",
  "George Orwell": "English writer known for dystopian novels like '1984' and 'Animal Farm",
  "Federico Fellini": "Italian film director known for distinctive style and surreal storytel",
  "Russian custom": "Traditional practices and rituals unique to Russian culture.",
  "Fact about sports": "Information related to athletic activities and competitions.",
  "J.R.R. Tolkien": "English writer and scholar, author of The Lord of the Rings",
  "Wassily Kandinsky": "Russian painter and art theorist, pioneer of abstract art.",
  "Fact about movies": "Brief insights or truths related to films and cinema.",
  "Game of Thrones": "Epic fantasy TV series about power struggles in a fictional kingdom.",
  "Historical fact": "A verified event or detail from the past.",
  "Fact about flora": "Information related to plant life and botanical studies.",
  "Dietrich Bonhoeffer": "German theologian and anti-Nazi dissident",
  "Fact about Hollywood": "Information related to the American film industry centered in Hollywoo",
  "Eva Gabor": "Hungarian-American actress and singer known for Green Acres.",
  "Thomas Hardy": "English novelist and poet known for Wessex novels",
  "Henry Ward Beecher": "American clergyman and social reformer known for abolitionism.",
  "Fact about jobs": "Information or data related to employment and occupations.",
  "Dwight D. Eisenhower": "35th U.S. President and WWII Allied Supreme Commander",
  "Charlie Chaplin": "Iconic silent film actor and director known for the Tramp character.",
  "Serbian proverb": "Traditional sayings expressing Serbian cultural wisdom.",
  "Donald Curtis": "American actor known for film and television roles.",
  "Fargo": "Crime drama film and TV series set in Minnesota with dark humor.",
  "Thomas Wentworth Higginson": "American author, abolitionist, and military officer.",
  "Mother Teresa": "Catholic nun and missionary known for charitable work in India",
  "We Bought a Zoo": "Family film about rescuing and restoring a zoo.",
  "English proverb": "A traditional saying expressing common wisdom or truth in English.",
  "Ralph Marston": "Author known for writings on motivation and productivity.",
  "Albert Einstein": "Physicist known for the theory of relativity.",
  "British law": "Legal system of the United Kingdom covering statutes and common law",
  "Roger A. Caras": "American wildlife photographer, writer, and conservationist.",
  "Mexican proverb": "Traditional saying expressing Mexican cultural wisdom and values.",
  "Max Eastman": "American writer, poet, and political activist known for socialism and ",
  "Mary Lou Retton": "American gymnast, Olympic all-around champion.",
  "Fact about music": "Information or truth related to music and its elements",
  "Donatella Versace": "Italian fashion designer and vice president of Versace",
  "Maya Angelou": "American poet and civil rights activist known for autobiographies",
  "Robert Breault": "American tenor known for opera and concert performances.",
  "James Cromwell": "American actor known for roles in film and television.",
  "Lily Leung": "Hong Kong actress known for roles in film and television.",
  "Thomas Mann": "German novelist and Nobel laureate known for works like Buddenbrooks.",
  "Fact about the Yanomami": "Indigenous people of the Amazon known for unique culture and tradition",
  "Fact about the Sentinelese": "The Sentinelese are an isolated indigenous tribe in the Andaman Island",
  "Irish Proverb": "Traditional sayings expressing Irish wisdom and culture.",
  "Theodore Roosevelt": "26th president of the USA, known for progressive policies and conserva",
  "Fact about Huli Wigmen": "Indigenous people of Papua New Guinea known for elaborate wigs.",
  "Pablo Picasso": "Spanish painter and sculptor, co-founder of Cubism.",
  "Johann Wolfgang von Goethe": "German writer and statesman, key figure in literature and philosophy",
  "Steve Jobs": "Co-founder of Apple, pioneer in personal computing and tech innovation",
  "Chris Rock": "American comedian and actor known for sharp social humor.",
  "Johnny Depp": "American actor known for versatile roles in film and theater.",
  "Leo Tolstoy": "Russian author, known for 'War and Peace' and 'Anna Karenina'.",
  "Immanuel Kant": "German philosopher known for his work in epistemology and ethics",
  "Henry David Thoreau": "American essayist and philosopher known for naturalism and civil disob",
  "Bryant McGill": "American author and social entrepreneur focused on self-awareness.",
  "Voltaire": "French Enlightenment writer and philosopher known for wit and advocacy",
  "Lao Tzu": "Ancient Chinese philosopher, founder of Taoism.",
  "Jack London": "American author known for adventure novels like The Call of the Wild",
  "Kate Douglas Wiggin": "American author known for children's literature, including Rebecca of ",
  "French proverb": "Traditional French saying expressing cultural wisdom or advice.",
  "Emanuel Lasker": "German chess player and World Chess Champion known for strategy.",
  "Denis Waitley": "American motivational speaker and writer on self-improvement",
  "Kofi Annan": "Ghanaian diplomat and former UN Secretary-General.",
  "Fact about inventions": "Brief truths or discoveries related to inventions",
  "Community": "American TV sitcom about a diverse group at a community college.",
  "Big Fish": "Film about a man's fantastical life stories recounted by his son.",
  "Arthur Schopenhauer": "German philosopher known for pessimism and 'The World as Will and Repr",
  "Jean Cocteau": "French poet, playwright, and filmmaker known for avant-garde works",
  "Unknown author": "An unidentified individual credited with a work or creation.",
  "Dante Alighieri": "Italian poet, author of The Divine Comedy, key medieval figure",
  "Sophocles": "Ancient Greek playwright known for tragedies like Oedipus Rex.",
  "Popular Myth": "Widespread traditional story explaining natural or social phenomena.",
  "Joke": "A short story or phrase with a humorous punchline.",
  "Sun Tzu": "Ancient Chinese military strategist and author of The Art of War",
  "Jewish Proverb": "Traditional saying expressing Jewish wisdom or moral lessons.",
  "Fact about the Maasai": "Indigenous East African ethnic group known for distinctive customs.",
  "African proverb": "Traditional sayings reflecting African cultural wisdom and values.",
  "George Bernard Shaw": "Irish playwright and critic, known for works like Pygmalion.",
  "Lady Gaga": "American singer, songwriter, and actress known for pop music and activ",
  "Vincent van Gogh": "Dutch post-Impressionist painter known for vivid works.",
  "Fact about entertainment": "Information related to movies, music, or other amusements.",
  "Fact about the Toda": "An indigenous tribe in India known for their unique culture.",
  "Jack Kerouac": "American novelist and poet, pioneer of the Beat Generation.",
  "Edgar Degas": "French artist famous for his paintings, sculptures, and ballet scenes.",
  "Korean proverb": "Traditional sayings conveying Korean cultural wisdom.",
  "Champfleury": "French writer and art critic associated with realism",
  "Confucius": "Ancient Chinese philosopher and teacher known for ethics and morality.",
  "Ayn Rand": "Russian-American writer known for philosophy of Objectivism.",
  "Fact about drinks": "Information related to various types of beverages.",
  "Chinese proverb": "Traditional wise sayings from Chinese culture.",
  "Relax life hack": "Techniques to reduce stress and improve well-being.",
  "Fact about the Cuiva": "Indigenous people living in Colombia, known for their unique culture.",
  "Erich Fromm": "German social psychologist and humanistic philosopher",
  "Ancient Greece": "Civilization known for philosophy, democracy, and classical art.",
  "Walt Whitman": "American poet known for 'Leaves of Grass' and free verse style.",
  "Tom Barrett": "American politician, former mayor of Milwaukee, Wisconsin",
  "John Barrymore": "American actor known for stage and film performances in early 20th cen",
  "Marcus Aurelius": "Roman emperor and Stoic philosopher known for Meditations",
  "Fact about Dani": "A piece of information related to someone named Dani.",
  "Herman Melville": "American novelist known for the novel Moby-Dick",
  "Charles de Gaulle": "French general and statesman, leader of Free France in WWII.",
  "Nicole Richie": "American television personality, fashion designer, and actress.",
  "Lucius Annaeus Seneca": "Roman Stoic philosopher, statesman, and playwright.",
  "C.S. Lewis": "British writer and scholar, famous for The Chronicles of Narnia.",
  "Woodrow Wilson": "28th U.S. President known for World War I leadership and League of Nat",
  "English Tradition": "Cultural customs and practices originating from England.",
  "Charles Caleb Colton": "English cleric, writer, and collector known for aphorisms.",
  "Winston Churchill": "British Prime Minister and WWII leader known for his speeches",
  "Nicolaus Copernicus": "Renaissance astronomer who proposed the heliocentric model of the sola",
  "Canadian law": "Legal system governing the laws of Canada.",
  "Jules Verne": "French author known for pioneering science fiction adventure novels",
  "Robert Louis Stevenson": "Scottish author known for adventure novels like Treasure Island.",
  "Bob Newhart": "American comedian and actor known for his deadpan delivery.",
  "Eckhart Tolle": "Spiritual teacher and author known for 'The Power of Now'.",
  "Dalai Lama": "Spiritual leader of Tibetan Buddhism and advocate for peace.",
  "Jacques Yves Cousteau": "French explorer and marine conservationist known for oceanography.",
  "Harry Potter": "A famous wizard from J.K. Rowling's fantasy book series.",
  "Franklin D. Roosevelt": "32nd U.S. President who led during the Great Depression and WWII",
  "Neil Armstrong": "First person to walk on the Moon.",
  "Forrest Gump": "A film about a man's extraordinary life journey through history.",
  "Stirling Moss": "British Formula One racing driver known for his skill and sportsmanshi",
  "Plato": "Ancient Greek philosopher, student of Socrates, founder of the Academy",
  "Calvin Coolidge": "30th U.S. President known for his quiet demeanor and conservative poli",
  "Osho": "Spiritual teacher known for teachings on meditation and mindfulness.",
  "Horatio Nelson": "British naval commander known for his victories in the Napoleonic Wars",
  "David Hume": "Scottish philosopher known for empiricism and skepticism",
  "Abraham Lincoln": "16th U.S. president who led the country during the Civil War",
  "Harry Potter and the Chamber of Secrets": "Second book of the Harry Potter series by J.K. Rowling.",
  "Michael Johnson": "American sprinter and multiple Olympic gold medalist",
  "Thom Jones": "American short story writer known for dark and intense narratives.",
  "Scott Adams": "American cartoonist, creator of the Dilbert comic strip.",
  "Rocky": "A fictional boxer from the iconic film series starring Sylvester Stall",
  "Kahlil Gibran": "Lebanese-American writer, poet, and artist known for The Prophet.",
  "The Walking Dead": "TV series about a group surviving a zombie apocalypse.",
  "Rabindranath Tagore": "Indian poet, writer, and Nobel laureate known for 'Gitanjali'.",
  "Interesting Facts": "Brief and surprising pieces of information on various topics.",
  "Fact about traveling": "Information related to journeys and travel experiences.",
  "Miriam Beard": "Historian specializing in ancient Rome and classical studies.",
  "Charles Mingus": "American jazz bassist, composer, and bandleader.",
  "Kimora Lee Simmons": "American fashion model and entrepreneur known for Baby Phat brand.",
  "Mahatma Gandhi": "Leader of Indian independence and advocate of nonviolent resistance",
  "Mandy Hale": "Author and motivational speaker known for inspiring women's empowermen",
  "Greek proverb": "Traditional sayings originating from ancient Greece expressing wisdom.",
  "World record": "The best performance achieved globally in a specific activity.",
  "Alfred Marshall": "English economist known for contributions to microeconomics and supply",
  "Rajneesh": "Indian mystic and spiritual teacher known as Osho",
  "J.K. Rowling": "British author known for writing the Harry Potter series.",
  "Dead Poets Society": "Film about inspiring students through poetry and personal expression.",
  "Venezuelan custom": "Traditional practices and rituals unique to Venezuela's culture",
  "Niccolò Machiavelli": "Italian Renaissance political philosopher and author of The Prince",
  "Lucy Maud Montgomery": "Canadian author known for the novel Anne of Green Gables",
  "Idiom": "A phrase with a meaning different from its literal words.",
  "John F. Kennedy": "35th U.S. President known for Cold War leadership and assassination",
  "Marsha Norman": "American playwright and screenwriter known for her impactful dramas.",
  "Bill Gates": "Co-founder of Microsoft, philanthropist, and technology pioneer.",
  "Dr. John Bradshaw": "Author and educator specializing in family therapy and psychology.",
  "Thomas Hobbes": "English philosopher known for social contract theory and Leviathan",
  "The Usual Suspects": "Crime thriller film known for its twist ending and complex plot.",
  "Martin Mull": "American actor, comedian, and musician known for TV and film roles.",
  "Braveheart": "Epic historical film about Scottish hero William Wallace's fight for f",
  "Audrey Hepburn": "Iconic British actress and humanitarian, known for classic films.",
  "Marva Collins": "Innovative American educator known for her work with disadvantaged stu",
  "Philip Fisher": "American investment analyst known for growth investing principles",
  "Popular myth": "A widely held but false belief or idea.",
  "John Ruskin": "English art critic and social thinker influential in the Victorian era",
  "Bruce Garrabrandt": "American actor known for roles in TV and film.",
  "Fact about the Asaro Mudmen": "Traditional Papua New Guinea tribe known for distinctive mud masks.",
  "Thich Nhat Hanh": "Vietnamese Buddhist monk and peace activist known for mindfulness",
  "Aristotle": "Ancient Greek philosopher and scientist, student of Plato.",
  "Avicenna": "Persian polymath known for contributions to medicine and philosophy",
  "The Pursuit of Happyness": "Film about a man's struggle for a better life and success.",
  "Albert E Cliffe": "",
  "Ibn Battuta": "Medieval Moroccan explorer known for extensive travels across the Isla",
  "Martin Luther King Jr.": "American civil rights leader known for nonviolent activism and speeche",
  "Desmond Tutu": "South African Anglican bishop and human rights activist",
  "William James": "American philosopher and psychologist, founder of functional psycholog",
  "Kinky Friedman": "American singer, songwriter, novelist, and humorist known for satire",
  "Robert Frost": "American poet known for his depictions of rural life and nature.",
  "Jane Austen": "English novelist known for novels like Pride and Prejudice",
  "Catherine Pulsifer": "Author known for inspirational quotes and self-help writings.",
  "Armin Houman": "",
  "W.L. George": "British author known for novels and social criticism",
  "Desiderius Erasmus": "Dutch Renaissance humanist and theologian known for his writings",
  "Claude Adrien Helvetius": "French philosopher known for his works on ethics and human nature.",
  "John Evelyn": "English writer, gardener, and diarist known for his detailed journals.",
  "Bat Masterson": "American Old West figure known as lawman, gambler, and sportswriter",
  "Ann Landers": "American advice columnist known for her syndicated newspaper column.",
  "Hope Floats": "Romantic drama film about love and personal growth after loss.",
  "Mark Halperin": "American political analyst and journalist",
  "Benjamin Disraeli": "British statesman and novelist, twice Prime Minister of the UK.",
  "Filipino proverb": "Traditional Filipino sayings conveying cultural wisdom and values.",
  "Benjamin Mays": "African American minister and civil rights leader.",
  "Benjamin Harrison": "23rd president of the United States",
  "Socrates": "Classical Greek philosopher credited as a founder of Western philosoph",
  "Paul Walker": "American actor known for the Fast & Furious film series.",
  "Madame de Staël": "French-Swiss writer and intellectual influential during the Enlightenm",
  "Will Rogers": "American humorist, actor, and social commentator",
  "Alfred A. Montapert": "American author known for writings on success and motivation.",
  "Tacitus": "Roman historian known for Annals and Histories",
  "Herm Albright": "American cartoonist known for editorial and humorous drawings.",
  "Blaise Pascal": "French mathematician, physicist, and philosopher known for Pascal's Tr",
  "Norwegian proverb": "Traditional sayings originating from Norway, conveying folk wisdom.",
  "Alphonse de Lamartine": "French poet, politician, and historian known for Romantic poetry.",
  "Michael Hyatt": "Leadership mentor and author focused on personal development.",
  "Spanish proverb": "Traditional sayings reflecting Spanish culture and values.",
  "Arthur Ashe": "American tennis player and social activist",
  "Hindu proverb": "Traditional saying expressing wisdom from Hindu culture",
  "Zig Ziglar": "Motivational speaker and author known for sales and personal developme",
  "Italian Tradition": "Customs and cultural practices originating from Italy",
  "The Notebook": "Romantic drama film based on Nicholas Sparks' novel.",
  "Henry Ford": "American industrialist, founder of Ford Motor Company",
  "Fact about Maasai": "Indigenous ethnic group known for distinct culture in East Africa.",
  "François de La Rochefoucauld": "French writer known for maxims and moral reflections.",
  "Stephen R. Covey": "Author known for 'The 7 Habits of Highly Effective People'",
  "To Kill a Mockingbird": "Classic novel addressing racial injustice in the American South.",
  "Christian D. Larson": "American New Thought leader and author on self-improvement.",
  "Friedrich Nietzsche": "German philosopher known for ideas on nihilism and existentialism",
  "Jarod Kintz": "American author known for his witty and philosophical quotes.",
  "Arthur Conan Doyle": "British writer, creator of Sherlock Holmes detective stories.",
  "T.S. Eliot": "Renowned poet and critic, author of 'The Waste Land'.",
  "Democritus": "Ancient Greek philosopher known for atomic theory of the universe",
  "Tiberius Claudius Augustus Germanicus": "Roman emperor known as Claudius, ruled the Roman Empire.",
  "Jonathan Swift": "Anglo-Irish satirist and author of Gulliver's Travels.",
  "Oliver Wendell Holmes Sr.": "American physician, poet, and essayist known for medical reform.",
  "Japanese proverb": "Traditional wise saying from Japan conveying cultural values.",
  "Antoine de Saint-Exupéry": "French writer and aviator, author of The Little Prince.",
  "Charles Darwin": "Naturalist who developed the theory of evolution by natural selection",
  "Fact about theaters": "Information related to venues for performing arts and films",
  "Muhammad Ali": "Legendary American professional boxer and cultural icon.",
  "Anthony Bourdain": "Chef, author, and travel documentarian known for exploring food cultur",
  "Fact about books": "Information or trivia related to books and literature.",
  "Interesing fact": "",
  "Khalil Gibran": "Lebanese-American writer, poet, and philosopher known for The Prophet.",
  "Oprah Winfrey": "American talk show host, actress, producer, and philanthropist",
  "Niki Lauda": "Austrian Formula One driver and three-time World Champion.",
  "James Herriot": "British veterinary surgeon and author known for animal stories",
  "Thomas à Kempis": "Author of 'The Imitation of Christ,' a Christian devotional writer.",
  "Stephen Colbert": "American comedian and TV host known for satirical news shows.",
  "Kevin Gates": "American rapper and singer known for his emotional lyrics and mixtapes",
  "Dr. Jane Smith": "Medical professional and researcher specialized in healthcare.",
  "Maud Lindsay": "American author known for children's literature and poetry.",
  "Fact about Mursi": "An ethnic group in Ethiopia known for lip plates and customs.",
  "David Ogilvy": "Pioneer of modern advertising and founder of Ogilvy & Mather.",
  "Pat Parelli": "Natural horsemanship trainer and founder of Parelli Natural Horsemansh",
  "Guinness World Records": "Annual reference book listing world record achievements",
  "Shania Twain": "Canadian singer-songwriter known for country and pop music hits.",
  "Margaret Fuller": "American journalist and women's rights advocate.",
  "Napoleon Hill": "American self-help author known for 'Think and Grow Rich'.",
  "Jane Howard": "British writer and journalist known for cultural and social commentary",
  "Robert Kiyosaki": "Author and entrepreneur known for personal finance and investing books",
  "Konrad Lorenz": "Austrian zoologist known for founding ethology, the study of animal be",
  "Francis Bacon": "English philosopher and statesman, father of modern empiricism.",
  "Judith Jamison": "Renowned American dancer and choreographer in modern dance.",
  "Hungarian proverb": "Traditional saying reflecting Hungarian culture and wisdom",
  "Laozi": "Ancient Chinese philosopher, founder of Taoism",
  "Idowu Koyenikan": "Author known for works on leadership and personal development.",
  "Anatole France": "French poet, journalist, and novelist known for satirical works.",
  "Levantine proverb": "A traditional saying from the Levant region expressing common wisdom.",
  "Eleanor Roosevelt": "American political figure and wife of President Franklin D. Roosevelt",
  "Barry Eisler": "American author known for thriller and espionage novels.",
  "Walter Winchell": "American newspaper and radio gossip commentator.",
  "Amy Purdy": "American snowboarder and motivational speaker",
  "Donovan Bailey": "Canadian sprinter and Olympic gold medalist in 100 meters.",
  "Japanese law": "Legal system governing Japan, based on civil law tradition.",
  "Sarah Kay": "Poet and spoken word artist known for engaging performances.",
  "The Lord of the Rings": "Epic fantasy novel by J.R.R. Tolkien about Middle-earth's struggle.",
  "Ernest Hemingway": "American author known for concise prose and novels like The Old Man an",
  "Tom Bodett": "American author and voice actor, known for Motel 6 commercials",
  "Ashleigh Brilliant": "Writer and artist known for concise, witty aphorisms.",
  "Fact about the Himba": "Indigenous Namibian tribe known for red ochre body paint.",
  "Gilbert Keith Chesterton": "English writer, philosopher, and critic known for detective fiction.",
  "Tim Ferriss": "Author and entrepreneur known for productivity and lifestyle design.",
  "Sleepless In Seattle": "Romantic comedy film about a widower finding love via radio call-in.",
  "Gilbert K. Chesterton": "English writer and philosopher known for detective fiction and essays",
  "Barbara Kingsolver": "American novelist and poet known for her environmental and social them",
  "Charlotte Brontë": "English novelist and poet, author of 'Jane Eyre'.",
  "Wayne W. Dyer": "Self-help author and motivational speaker known for spiritual teaching",
  "Shiv Khera": "Indian author and motivational speaker known for self-help books.",
  "Robert Montgomery": "American actor and director known for classic films.",
  "Albert Camus": "French-Algerian philosopher and writer, key figure in existentialism.",
  "Pavana": "A slow processional instrumental form in Baroque music.",
  "Liam James": "Canadian actor known for roles in film and television.",
  "Leon Trotsky": "Russian revolutionary and Marxist theorist",
  "William Butler Yeats": "Irish poet and playwright, key figure in 20th-century literature",
  "David Cottrell": "",
  "Emily Dickinson": "American poet known for her unique and concise poetry style.",
  "Oliver Goldsmith": "Irish novelist and playwright known for 'The Vicar of Wakefield'.",
  "E. W. Howe": "American author and editor known for short stories and novels.",
  "Iron Man": "Marvel superhero in a high-tech armored suit",
  "Rene Descartes": "French philosopher, mathematician, and scientist, father of modern phi",
  "Victor Hugo": "French writer known for Les Misérables and The Hunchback of Notre-Dame",
  "Bernard Meltzer": "American radio host known for his legal advice program.",
  "Jordan Belfort": "American former stockbroker and motivational speaker",
  "Richelle E. Goodrich": "American author known for poetry and inspirational books",
  "Spanish Tradition": "Customs and cultural practices originating from Spain.",
  "Archimedes": "Ancient Greek mathematician, physicist, and engineer.",
  "Syrus": "A historical figure known as a tutor and strategist in ancient Rome.",
  "Hermann Hesse": "German-Swiss poet, novelist, and painter known for explorations of spi",
  "Doctor Who": "British sci-fi TV series about a time-traveling alien called the Docto",
  "Italian proverb": "Traditional saying expressing Italian cultural wisdom.",
  "William Arthur Ward": "American motivational writer known for inspirational quotes.",
  "Jason Mraz": "American singer-songwriter known for his hit song \"I'm Yours\"",
  "Lebanese proverb": "Traditional proverb reflecting Lebanese culture and wisdom.",
  "French Tradition": "Cultural customs and practices originating from France.",
  "Pericles": "Ancient Athenian statesman and general influential in democracy.",
  "Brian Tracy": "Author and motivational speaker specializing in personal development.",
  "Shannon L. Alder": "Author known for inspirational quotes and self-help books.",
  "Daniel Defoe": "English writer known for 'Robinson Crusoe'",
  "Vincent Van Gogh": "Dutch post-impressionist painter known for expressive works.",
  "Rembrandt": "Dutch painter and etcher, famous for portraits and biblical scenes.",
  "Invisible Man": "A novel about racial identity and social invisibility.",
  "The Shawshank Redemption": "Drama film about hope and friendship in prison.",
  "South Korean custom": "Traditional practices and rituals unique to South Korean culture.",
  "Greek custom": "Traditional practices and rituals originating from Greece.",
  "Elisabeth Foley": "Researcher focused on public health and epidemiology",
  "Bruce Lee": "Martial artist, actor, and influential figure in cinema and culture",
  "Walter Hagen": "American professional golfer known for winning multiple major champion",
  "Sylvia Earle": "Marine biologist and oceanographer known for ocean conservation.",
  "James E. Faust": "American LDS Church leader and apostle.",
  "Anjay Cohen": "Comedian and actor known for his comedic performances and sketches.",
  "Francois de La Rochefoucauld": "French writer known for maxims and moral reflections.",
  "Czech proverb": "Traditional sayings expressing Czech cultural wisdom.",
  "Joel Osteen": "American televangelist and author known for positive sermons.",
  "Cesare Pavese": "Italian poet and novelist known for his literary works",
  "Rick Warren": "American evangelical Christian pastor and author of The Purpose Driven",
  "Samuel Taylor Coleridge": "English poet and philosopher, founder of English Romanticism.",
  "George Washington": "First president of the United States and Revolutionary War leader",
  "Swedish Tradition": "Cultural customs and practices originating from Sweden.",
  "Carl Sagan": "American astronomer, author, and science communicator.",
  "Bernice Johnson Reagon": "American scholar, singer, and civil rights activist",
  "Galileo Galilei": "Italian astronomer, physicist, and pioneer of the scientific method",
  "Loki": "Marvel character, god of mischief and brother of Thor.",
  "William Wordsworth": "English Romantic poet known for nature-themed works",
  "Heywood Broun": "American sportswriter and journalist known for his progressive views.",
  "German law": "Legal system governing Germany's federal and state laws.",
  "Bernice Fitz-Gibbon": "American retail advertising executive known for innovative slogans",
  "Fact about relaxation": "Information related to methods or benefits of relaxation.",
  "Fact about the Soliga": "An indigenous community in India known for traditional forest liveliho",
  "Australian law": "Legal system governing Australia's laws and judicial processes.",
  "Agnes Repplier": "American essayist known for wit and literary criticism.",
  "Jacques Cousteau": "French oceanographer and explorer known for marine conservation.",
  "Publius Vergilius Maro": "Ancient Roman poet known for the epic Aeneid.",
  "W. H. Auden": "Renowned English-American poet known for his technical skill and varie",
  "Ice Cube": "American rapper, actor, and filmmaker.",
  "Alan Alda": "American actor and writer known for M*A*S*H and advocacy work",
  "Edward R. Murrow": "American broadcast journalist known for WWII reporting and integrity",
  "H. L. Mencken": "American journalist, essayist, and cultural critic known for satire",
  "Fact about the Mantawai": "Indigenous tribe residing in the Mentawai Islands, Indonesia.",
  "Egyptian custom": "Traditional practices and rituals originating from ancient Egypt.",
  "Fyodor Dostoevsky": "Russian novelist and philosopher known for exploring psychology and mo",
  "Fact about Surma": "Surma refers to various cultural and geographical terms in South Asia.",
  "Robert A Heinlein": "American science fiction author known for influential novels.",
  "George Matthew Adams": "American newspaper columnist and publisher known for inspirational wri",
  "Zhuangzi": "Ancient Chinese philosopher known for Daoist writings and parables.",
  "James A. Garfield": "20th U.S. president and Civil War general"
}