export default [
  "Palinsesto - un manoscritto o documento il cui testo originale è stato cancellato e riscritto, ma tracce del testo precedente rimangono e permettono la ricostruzione dei livelli di significato sottostanti.",
  "Ominipresente - esistente o incontrato ovunque contemporaneamente, al punto che la sua presenza diventa data per scontata piuttosto che notata, come con la connettività digitale o il rumore di fondo nelle città.",
  "Leccapiedi - una persona che adulare coloro che detengono il potere per ottenere favori o vantaggi, spesso a scapito della sincerità o dell'integrità, creando un ambiente sociale distorto intorno all'autorità.",
  "Entropia - una misura del disordine o della casualità in un sistema, utilizzata per descrivere la tendenza naturale dei sistemi a muoversi da stati ordinati verso configurazioni più probabili e meno organizzate.",
  "Anedonia - la ridotta capacità di provare piacere dalle attività che normalmente sono considerate piacevoli, spesso associata a stati depressivi o a disfunzioni neurologiche.",
  "Offuscare - rendere deliberatamente qualcosa poco chiaro, confuso o difficile da comprendere, specialmente per evitare critiche o responsabilità nella comunicazione o nel processo decisionale.",
  "Cynosure - qualcosa o qualcuno che diventa il fulcro dell'attenzione o dell'ammirazione, non semplicemente visibile ma irresistibile, attirando gli sguardi e le intenzioni degli altri verso di sé.",
  "Effimero - che dura per un tempo molto breve prima di svanire o scomparire rapidamente, tipicamente usato per descrivere stati, esperienze o fenomeni che non possono essere completamente catturati o conservati.",
  "Maelstrom - un potente e violento vortice capace di attirare cose al suo centro, usato metaforicamente per situazioni caotiche che distruggono la struttura o la stabilità.",
  "Apatie - uno stato di indifferenza emotiva in cui gli stimoli che solitamente suscitano interesse o preoccupazione non riescono a provocare motivazione, coinvolgimento o risposta da parte dell'individuo.",
  "Iridescente - che mostra colori luminosi che sembrano cambiare o spostarsi quando vengono osservati da angolazioni diverse, come si vede nelle bolle di sapone, nelle piume degli uccelli o in alcune superfici minerali.",
  "Petrichor - l'odore terrestre distintivo e piacevole che si sprigiona dal terreno secco quando cade la prima pioggia, causato dagli oli rilasciati dalle piante e dai composti formati dai microrganismi.",
  "Obsoleto - non più in uso generale o rilevante perché è stato sostituito da qualcosa di più nuovo o più efficace, anche se può persistere negli archivi o nei sistemi legacy.",
  "Metamorfosi - un cambiamento profondo nella forma, struttura o carattere, osservato biologicamente negli insetti e metaforicamente nei processi di trasformazione personale o sociale.",
  "Barometro - uno strumento che misura la pressione atmosferica, utilizzato per prevedere i cambiamenti meteorologici a breve termine e, in senso metaforico, per valutare le variazioni di opinione o di condizioni.",
  "Parsimonia - estrema riluttanza a spendere risorse, siano esse denaro, impegno o parole, producendo spesso risultati minimi ma funzionali a scapito della generosità o della ricchezza.",
  "Mercuriale - caratterizzato da rapidi e imprevedibili cambiamenti di umore o comportamento, ricordando la natura mutevole del mercurio, creando difficoltà nell'anticipazione o nella fiducia.",
  "Vendicativo - che prova o mostra il desiderio di cercare vendetta, non si limita a ricordare un torto ma mira attivamente a punire o infliggere danno in risposta.",
  "Laconico - esprimere idee usando pochissime parole, ottenendo un discorso conciso fino al punto dell'austerità, spesso interpretato come sicuro, freddo o sprezzante.",
  "Vicissitudine - un cambiamento di circostanze o fortuna, specialmente uno indesiderato o fuori dal proprio controllo, che sottolinea l'instabilità come caratteristica naturale della vita.",
  "Zealot - una persona che mostra una devozione estrema e inflessibile a una credenza o causa, spesso rifiutando la moderazione e ignorando le prospettive o le conseguenze opposte.",
  "Erudito - che possiede o dimostra una vasta conoscenza acquisita attraverso la lettura e lo studio, non semplicemente informato ma profondamente istruito in un modo che influenza l'espressione e l'analisi.",
  "Dogmatico - incline a presentare le opinioni come verità incontrovertibili, resistendo al dubbio o a punti di vista alternativi, riducendo l'indagine aperta nel discorso o nelle istituzioni.",
  "Transitorio - che dura solo per un breve periodo prima di scomparire, in particolare riferito a stati o popolazioni che esistono per poco tempo e lasciano tracce limitate una volta che le condizioni cambiano.",
  "Rescindere - revocare, annullare o invertire una decisione, una legge o un accordo, ripristinando lo stato precedente o annullando obblighi precedentemente vigenti.",
  "Melanconia - una forma profonda e persistente di tristezza non legata a cause immediate, storicamente descritta come un temperamento e ora associata a un affetto depressivo.",
  "Sinécdoque - una figura retórica en la que una parte representa el todo o el todo representa una parte, alterando la perspectiva al cambiar la escala representativa.",
  "Panacea - un rimedio ipotetico capace di curare ogni malattia o problema, spesso invocato retoricamente per criticare soluzioni ingenue o semplicistiche.",
  "Immutabile - non soggetto a cambiamenti o alterazioni nel tempo, sia intenzionali che forzati, spesso usato per descrivere principi, verità matematiche o stati del codice.",
  "Equanimità - uno stato di compostezza psicologica e stabilità sotto stress o conflitto, in cui le reazioni emotive rimangono misurate piuttosto che volatili o estreme.",
  "Ambivalenza - uno stato in cui una persona nutre contemporaneamente due sentimenti o convinzioni opposti, generando esitazione e difficoltà nel prendere decisioni o nell'impegnarsi in un'unica direzione.",
  "Confliggere - unire due o più idee, questioni o informazioni in un'unica entità in modo tale da offuscare le loro differenze e poter fuorviare l'interpretazione o l'analisi.",
  "Denouement - la fase finale di una narrazione in cui trame complicate vengono risolte e le tensioni si sciolgono, rivelando le conseguenze che seguono il climax.",
  "Equivocare - parlare in modo intenzionalmente vago o ambiguo per evitare di esprimere una posizione chiara o per ingannare senza pronunciare una falsa dichiarazione diretta.",
  "Meticoloso - mostrare estrema attenzione ai dettagli e precisione, spesso combinata con una forte preferenza per l'ordine o la pulizia e una bassa tolleranza per gli errori.",
  "Gregoriate - riorganizzare o rimodellare una struttura di pensiero, politica o comportamento in conformità con un nuovo principio dominante, spesso sostituendo ciò che era precedentemente consolidato.",
  "Euristico - un metodo pratico per risolvere problemi o prendere decisioni utilizzando strategie basate sull'esperienza piuttosto che sulla logica esaustiva o sulla precisione garantita.",
  "Impenetrabile - impossibile da interpretare o comprendere a causa dell'opacità del motivo, dell'espressione o della struttura, lasciando gli osservatori incerti sul significato sottostante.",
  "Giustapposizione - la collocazione di due elementi affiancati al fine di evidenziare il contrasto, la somiglianza o la tensione che emerge solo mediante la loro prossimità.",
  "Caleidoscopico - che cambia rapidamente forma o aspetto in modo tale da creare una sensazione di ricomposizione continua, come i specchi oscillanti in un caleidoscopio.",
  "Liminale - relativo a un confine o una soglia tra due stati, fasi o identità, dove trasformazione, ambiguità o instabilità sono naturalmente concentrate.",
  "Manifesto - una dichiarazione scritta formale che annuncia i principi, le intenzioni o le richieste di un movimento o di un individuo, con l'intento di influenzare l'opinione pubblica o avviare un cambiamento.",
  "Nihilismo - la convinzione che la vita manchi di significato, scopo o valore intrinseco, spesso accompagnata da scetticismo verso affermazioni morali, religiose o politiche di verità.",
  "Ossequioso - che mostra una disponibilità esagerata ed eccessiva a servire o obbedire, specialmente verso chi detiene il potere, spesso percepita come umiliante o manipolativa.",
  "Paradosso - un'affermazione o una situazione che sembra contraddittoria o assurda, ma che può contenere una verità sottostante quando esaminata da una prospettiva più profonda.",
  "Quixotico - guidato da speranze o obiettivi idealistici ma irrealistici, spesso ignorando vincoli pratici e portando ad azioni nobili ma inefficaci.",
  "Ricalibrare - regolare o riconfigurare i parametri di un sistema, misura o strategia per ripristinare l'accuratezza o adattarsi a condizioni modificate.",
  "Saliente - che si distingue in modo da attirare l'attenzione grazie alla sua rilevanza, importanza o chiarezza, rendendolo la prima caratteristica percepita o ricordata.",
  "Trascendenza - l'atto di superare i limiti ordinari dell'esperienza, del pensiero o della condizione, spesso associato all'ascesa spirituale, intellettuale o artistica.",
  "Umbrage - un sentimento di risentimento o offesa scatenato da un'offesa o un insulto implicito, anche quando la provocazione è sottile o ambigua.",
  "Verosimiglianza - l'apparenza di verità o realismo nell'arte, nell'argomentazione o nella narrazione, che fa sì che qualcosa di fittizio o costruito sembri convincente e autentico.",
  "Capriccioso - caratterizzato da un'imprevedibilità giocosa o da un'immaginazione fantastica, a volte affascinante e a volte irregolare o poco pratica nelle conseguenze.",
  "Xenofobia - paura o ostilità verso gli stranieri o presunti esterni, espressa attraverso sospetto, rifiuto o comportamenti aggressivi a livello sociale o politico.",
  "Giogo - legare due entità insieme, fisicamente o metaforicamente, in modo da limitare l'indipendenza o imporre un allineamento sotto un onere o un'autorità condivisa.",
  "Zeitgeist - lo spirito dominante o il clima intellettuale di un'epoca, riflesso nei suoi valori predominanti, nelle ansie e nelle espressioni culturali.",
  "Ameliorare - rendere qualcosa di cattivo o insoddisfacente migliore o più tollerabile, non eliminando la causa ma riducendo il suo impatto negativo.",
  "Capitolare - arrendersi o cedere dopo una resistenza, solitamente sotto pressione o inevitabilità, riconoscendo la perdita di autonomia o della posizione strategica.",
  "Debacle - un fallimento improvviso e disastroso che provoca il crollo di una struttura, un piano o una reputazione, lasciando disordine ed esponendo debolezze sottostanti.",
  "Ennui - una sensazione di profonda noia e stanchezza derivante dalla mancanza di occupazione o stimoli, spesso accompagnata da un senso di insignificanza.",
  "Furtivo - comportarsi in modo segreto o furtivo per evitare di essere scoperti o controllati, implicando che l'azione nascosta provocherebbe disapprovazione se rivelata.",
  "Grandioso - che appare o è inteso ad apparire impressionante, magnifico o più importante di quanto sia realistico, spesso riflettendo ambizioni esagerate o una percezione di sé gonfiata.",
  "Egemoneia - il dominio di uno stato, ideologia o gruppo sociale sugli altri, mantenuto non solo con la forza ma anche attraverso l'influenza culturale, le norme e il consenso dei governati.",
  "Iconoclasta - una persona che attacca o rifiuta credenze, tradizioni o istituzioni rispettate, sfidando ciò che gli altri considerano intoccabile o sacro.",
  "Giudizioso - che dimostra un giudizio ragionevole basato su ragione, cautela e lungimiranza piuttosto che sull'impulso, spesso evidente nelle decisioni prese in condizioni di incertezza.",
  "Kafkiano - che assomiglia alle situazioni assurde, oppressive, illogiche e da incubo presenti nelle opere di Kafka, in cui gli individui sono intrappolati in una burocrazia senza senso.",
  "Lugubre - eccessivamente mesto o cupo nel modo, nel tono o nell'atmosfera in un modo che risulta pesante, teatrale o prolungato.",
  "Monolitico - grande, uniforme e inflessibile nella struttura o ideologia, resistente alle modifiche e repressivo della diversità interna o del dissenso.",
  "Nebuloso - privo di una forma chiara, confini o definizione, sia che si riferisca a forme fisiche, strutture argomentative o idee poco concentrate.",
  "Ontologia - il ramo della filosofia che si occupa della natura dell'essere, delle categorie dell'esistenza e della struttura fondamentale della realtà.",
  "Superficiale - eseguito con il minimo sforzo o riflessione, semplicemente per adempiere a un dovere o a un'aspettativa, mostrando assenza di impegno o sincerità.",
  "Quintessenza - la manifestazione più pura o perfetta di una qualità o classe, che serve da esempio definitorio rispetto al quale gli altri vengono misurati.",
  "Ramificazione - una conseguenza o un effetto secondario che si dirama da un'azione o decisione iniziale, spesso creando catene complesse di impatti.",
  "Saccente - che mostra superiorità morale o rettitudine in modo ipocrita o performativo che suscita irritazione piuttosto che rispetto.",
  "Coppia - una forza rotazionale che provoca torsione o rotazione, usata letteralmente in meccanica e metaforicamente per forze che influenzano opinioni o politiche.",
  "Sottovalutare - descrivere o presentare qualcosa come più piccolo o meno grave di quanto non sia in realtà, spesso per attenuare l'impatto, controllare la narrazione o evitare allarmi.",
  "Avanguardia - l'avanguardia di un movimento, innovazione o trasformazione, composta da coloro che agiscono o cambiano prima che gli altri seguano.",
  "Mandato - giustificare o autorizzare un'azione o una credenza fornendo motivi adeguati, legittimità o necessità per accettarla o eseguirla.",
  "Xerico - caratterizzato da condizioni estremamente secche con umidità minima, tipicamente utilizzato per habitat, suoli o strategie biologiche adattative.",
  "Cedere - sottomettersi o dare spazio a una forza, a un argomento o a una circostanza, oppure produrre un risultato misurabile in risposta a un input nel tempo.",
  "Zenith - il punto più alto o di maggior successo raggiunto da una persona, un processo o un fenomeno prima che inizi il declino o la trasformazione.",
  "Ambiguo - aperto a più interpretazioni a causa di vaghezza o dualità strutturale, generando incertezza nell'inferenza o nella risposta.",
  "Bizantino - altamente complesso, stratificato e difficile da navigare a causa di dettagli eccessivi, procedure o occultamento dell'intento.",
  "Enigma - un problema o una domanda difficile senza una soluzione chiara, spesso complicata da vincoli contrastanti o informazioni mancanti.",
  "Didattico - inteso per insegnare o trasmettere istruzioni, talvolta con un tono che può risultare moralistico, prescrittivo o esteticamente pesante.",
  "Estrarre - dedurre o prevedere oltre i dati conosciuti estendendo i modelli osservati, accettando un'incertezza crescente con l'aumentare della distanza.",
  "Fedeltà - lealtà o fedeltà a una persona, standard o obbligo, oppure il grado di precisione con cui qualcosa riproduce un originale.",
  "Glaciale - estremamente lento nel ritmo o nel progresso, o freddo e distante nel tono emotivo, evocando il movimento e il gelo del ghiaccio letterale.",
  "Ipotesi - un'affermazione esplicativa provvisoria che può essere testata o smentita tramite osservazione, esperimento o deduzione logica.",
  "Inerzia - la tendenza di un sistema a resistere al cambiamento del suo stato o del suo moto, persistendo nella traiettoria esistente a meno che non venga agito da una forza esterna.",
  "Giustapporre - porre elementi affiancati in modo che il contrasto o la corrispondenza diventino percepibili solo attraverso la loro prossimità.",
  "Giudicare - prendere una decisione o un giudizio formale su una controversia o una richiesta, tipicamente all'interno di un quadro legale o istituzionale che conferisce autorità al decisore.",
  "Antagonista - una persona, forza o principio che si oppone attivamente o crea conflitto per un altro agente o protagonista, modellando la dinamica della lotta o della resistenza.",
  "Belligerante - che mostra prontezza a combattere o ad impegnarsi in conflitti, sia attraverso un atteggiamento ostile sia mediante una partecipazione attiva alla guerra o a confronti aggressivi.",
  "Cacofonia - un miscuglio duro e disarmonico di suoni percepito come sgradevole o travolgente, spesso usato metaforicamente per interazioni caotiche o disallineate.",
  "Canonizzare - dichiarare ufficialmente qualcuno santo o trattare un testo o una figura come autorevole e al di là di ogni critica all'interno di una tradizione o di una linea intellettuale.",
  "Chiaroscuro - l'interazione di luce e ombra che produce un contrasto drammatico nell'arte visiva, enfatizzando profondità, volume e intensità emotiva.",
  "Coercizione - l'atto di costringere qualcuno ad agire contro la propria volontà mediante l'uso della forza, minacce o pressioni che eliminano la condizione del libero consenso.",
  "Convalescere - recuperare gradualmente forza e salute dopo una malattia o un intervento medico attraverso il riposo, la stabilizzazione e un'attività controllata.",
  "Deferenza - sottomissione rispettosa al giudizio, all'opinione o all'autorità di un'altra persona, motivata dal riconoscimento dello status, dell'esperienza o della gerarchia.",
  "Dogma - un principio o insieme di credenze presentati come autorevoli e indiscutibili all'interno di un sistema, sostenuti senza tolleranza per sfide o revisioni.",
  "Emulare - eguagliare o superare un modello o un concorrente attraverso l'imitazione combinata con il miglioramento, spinti dall'ambizione piuttosto che dalla mera replica.",
  "Epitaffio - un'iscrizione o un breve testo scritto in memoria di una persona deceduta, solitamente inciso su una lapide e che riassume l'identità o l'eredità.",
  "Esegesi - l'interpretazione critica di un testo, in particolare di uno di status religioso o canonico, con l'obiettivo di estrarre il significato intenzionato attraverso un'analisi ragionata.",
  "Falsificabile - in grado di essere smentito attraverso l'osservazione o l'esperimento, caratterizzando un'affermazione come scientificamente verificabile piuttosto che semplicemente asserita.",
  "Gravitas - un modo serio e solenne che trasmette profondità intellettuale, autorità sociale o significato morale nel discorso, nella postura o nella decisione.",
  "Sfortunato - che sperimenta sventure o fallimenti persistenti nonostante l'assenza di intenzione o colpa, attirando l'attenzione sulla circostanza piuttosto che sulla competenza.",
  "Eresia - una credenza o affermazione che si discosta dalla dottrina stabilita all'interno di una tradizione, percepita come una minaccia all'ortodossia o alla coerenza istituzionale.",
  "Omogeneo - composto da parti o membri simili per natura o caratteristiche, riducendo la variazione interna e producendo un comportamento uniforme.",
  "Ineffabile - troppo grande, intenso o sottile per essere adeguatamente espresso a parole, che supera i limiti della rappresentazione linguistica.",
  "Inveire - parlare o scrivere con grande ostilità o indignazione contro qualcosa percepito come sbagliato, utilizzando accuse o denunce vigorose.",
  "La giurisprudenza - la teoria o filosofia del diritto che esamina i principi, le fonti e la logica sottostanti i sistemi giuridici e il ragionamento legale.",
  "Linearizzare - semplificare un fenomeno approssimandone il comportamento come lineare, riducendo la complessità per l'analisi a scapito di una precisione sfumata.",
  "Litote - una figura retorica in cui un'idea affermativa è espressa negando il suo opposto, producendo un understatement come modalità di enfasi.",
  "Macabro - che ha una qualità cupa o inquietante legata alla morte, al decadimento o a immagini grottesche, provocando una fascinazione intrecciata con il disagio.",
  "Mnemotecnica - un metodo o dispositivo utilizzato per aiutare la memorizzazione associando le informazioni a schemi che sono più facili da ricordare rispetto ai dati grezzi stessi.",
  "Normativo - riguarda la definizione di standard su ciò che dovrebbe essere piuttosto che descrivere ciò che è, prescrivendo ideali piuttosto che registrare fatti.",
  "Ontogenesi - lo sviluppo di un organismo individuale dalla sua fase iniziale fino alla maturità, tracciando le trasformazioni strutturali e funzionali nel tempo.",
  "Pathos - una qualità nella comunicazione che evoca pietà, dolore o profonda emozione nel pubblico, appellandosi alla vulnerabilità e alla fragile umanità condivisa.",
  "Perennante - che dura o si ripete più volte nel corso di un lungo periodo senza un calo significativo, riferito a piante, dibattiti o problemi strutturali.",
  "Probatorio - che possiede la qualità di provare o dimostrare qualcosa, specialmente prove che sono rilevanti e sufficienti a influenzare una conclusione legale o razionale."
];
