const allNames = {'Historical fact': "",
'Interesting fact': "",
'Fact about space': "",
'Interesting Fact': "",
'Proverb': "",
'Idioms': "",
'Animal fact': "",
'Scientific fact': "",
'Fact about sports': "",
'Fact about food': "",
'Fact about the world': "",
'Ralph Waldo Emerson': "",
'Fact about arts': "",
'Fact about music': "",
'Fact about economics': "",
'Mark Twain': "",
'Life hack': "",
'Fact about flora': "",
'Oscar Wilde': "",
'idioms': "",
'George Bernard Shaw': "",
'Fact about jobs': "",
'Fact about inventions': "",
'William Shakespeare': "",
'Thomas Jefferson': "",
'Charles Dickens': "",
'Johann Wolfgang von Goethe': "",
'Confucius': "",
'Joke': "",
'Socrates': "",
'Albert Einstein': "",
'World record': "",
'Albert Schweitzer': "",
'Russian proverb': "",
'Elvis Presley': "",
'Fact about politics': "",
'Life Hack': "",
'Forrest Gump': "",
'Robert Frost': "",
'African proverb': "",
'Popular myth': "",
'Steve Jobs': "",
'Dwight D. Eisenhower': "",
'Dr. Seuss': "",
'Friedrich Nietzsche': "",
'Epictetus': "",
'Henry David Thoreau': "",
'C.S. Lewis': "",
'Fact about Hollywood': "",
'Fact about books': "",
'William James': "",
'Nelson Mandela': "",
'R. Kelly': "",
'The Godfather Part II': "",
'A. A. Milne': "",
'The Beatles': "",
'The Wizard of Oz': "",
'Henry Wadsworth Longfellow': "",
'Who Framed Roger Rabbit': "",
'Gustave Flaubert': "",
'Wolfgang Amadeus Mozart': "",
'On the Waterfront': "",
'George Herbert': "",
'Justin Bieber': "",
'Notting Hill': "",
'R. Buckminster Fuller': "",
'Knute Rockne': "",
'Stanley Coren': "",
'English lullaby': "",
'Lullaby': "",
'Julius Caesar': "",
'Taxi Driver': "",
'Benjamin Franklin': "",
'Wall Street': "",
'Beau Taplin': "",
'The Stand': "",
'Anais Nin': "",
'The History of Mr. Polly': "",
'Breaking Bad': "",
'George Burns': "",
'Emile Zola': "",
'Wonder Woman ': "",
'Shania Twain': "",
'Leon Trotsky': "",
'George Orwell': "",
'Thich Nhat Hanh': "",
'Walter Winchell': "",
'The Notebook': "",
'Agnes Repplier': "",
'Jean Cocteau': "",
'Dead Poets Society': "",
'Walt Whitman': "",
'German law': "",
'Plato': "",
'Henry Ford': "",
'Nicolaus Copernicus': "",
'Harry Potter': "",
'Lucy Maud Montgomery': "",
'Lily Leung': "",
'To Kill a Mockingbird': "",
'Mexican proverb': "",
'Dr. John Bradshaw': "",
'Immanuel Kant': "",
'Benjamin Mays': "",
'J.K. Rowling': "",
'Theodore Roosevelt': "",
'Stirling Moss': "",
'Joel Osteen': "",
'Martin Luther King Jr.': "",
'Invisible Man': "",
'Antoine de Saint-Exupéry': "",
'Zhuangzi': "",
'Neil Armstrong': "",
'George Washington': "",
'Wassily Kandinsky': "",
'The Lord of the Rings': "",
'John Barrymore': "",
'Gilbert Keith Chesterton': "",
'Fact about relaxation': "",
'Nicole Richie': "",
'Ernest Hemingway': "",
'Winston Churchill': "",
'Osho': "",
'Francis Bacon': "",
'Laozi': "",
'Barbara Kingsolver': "",
'Greek proverb': "",
'Pablo Picasso': "",
'Braveheart': "",
'Kate Douglas Wiggin': "",
'Marcus Aurelius': "",
'Voltaire': "",
'Samuel Butler': "",
'Robert Louis Stevenson': "",
'The Pursuit of Happyness': "",
'Emanuel Lasker': "",
'Lao Tzu': "",
'Horatio Nelson': "",
'Fact about Surma': "",
'Japanese law': "",
'George Matthew Adams': "",
'Mark Halperin': "",
'Chinese proverb': "",
'Samuel Taylor Coleridge': "",
'Pericles': "",
'Desmond Tutu': "",
'Lucius Annaeus Seneca': "",
'Tim Ferriss': "",
'Ibn Battuta': "",
'Madame de Staël': "",
'Ayn Rand': "",
'Dr. Jane Smith': "",
'Max Eastman': "",
'Jason Mraz': "",
'Fyodor Dostoevsky': "",
'Greek custom': "",
'Guinness World Records': "",
'Ann Landers': "",
'François de La Rochefoucauld': "",
'Heywood Broun': "",
'Maya Angelou': "",
'Judith Jamison': "",
'Relax life hack': "",
'Jules Verne': "",
'Idiom': "",
'W.L. George': "",
'Chris Rock': "",
'Marva Collins': "",
'Miriam Beard': "",
'Serbian proverb': "",
'John F. Kennedy': "",
'Woodrow Wilson': "",
'Michael Johnson': "",
'Aristotle': "",
'Robert Kiyosaki': "",
'Roger A. Caras': "",
'Charlie Chaplin': "",
'Fact about movies': "",
'Bruce Lee': "",
'Robert A Heinlein': "",
'French Tradition': "",
'Jane Howard': "",
'Anthony Bourdain': "",
'Albert Camus': "",
'Publius Vergilius Maro': "",
'Eva Gabor': "",
'Carl Sagan': "",
'French proverb': "",
'Fact about the Himba': "",
'Fact about Dani': "",
'Rene Descartes': "",
'Canadian law': "",
'English proverb': "",
'Abraham Lincoln': "",
'Sylvia Earle': "",
'Wayne W. Dyer': "",
'Fact about Huli Wigmen': "",
'Ice Cube': "",
'Syrus': "",
'Unknown author': "",
'Bernice Johnson Reagon': "",
'Paul Walker': "",
'Tacitus': "",
'Filipino proverb': "",
'Fact about theaters': "",
'Catherine Pulsifer': "",
'Edgar Degas': "",
'Robert Montgomery': "",
'Kofi Annan': "",
'Mary Lou Retton': "",
'Jordan Belfort': "",
'Mandy Hale': "",
'Christian D. Larson': "",
'Norwegian proverb': "",
'Thomas Hardy': "",
'Dietrich Bonhoeffer': "",
'Ashleigh Brilliant': "",
'Italian proverb': "",
'Arthur Schopenhauer': "",
'William Wordsworth': "",
'Kahlil Gibran': "",
'Dante Alighieri': "",
'Charlotte Brontë': "",
'Will Rogers': "",
'Vincent Van Gogh': ""}