export default {
  "Benjamin Franklin": "Scientifique et homme politique américain, un des Pères fondateurs.",
  "Henri Fauconnier": "Écrivain français, auteur du roman La Croisière jaune.",
  "Gaston Bouthoul": "Sociologue français spécialisé dans l'étude des conflits",
  "Woody Allen": "Réalisateur et scénariste américain célèbre pour ses comédies.",
  "Henri Rochefort": "Journaliste et homme politique français connu pour son esprit critique",
  "Charles Baudelaire": "Poète français célèbre pour \"Les Fleurs du mal\".",
  "Roland Barthes": "Critique littéraire et sémiologue français influent du XXe siècle",
  "Pierre-Gilles de Gennes": "Physicien français, prix Nobel pour ses travaux en physique de la mati",
  "Proverbe chinois": "Sagesse populaire traditionnelle de la culture chinoise.",
  "V pour Vendetta (film)": "Film dystopique britannique sur un révolutionnaire masqué.",
  "Philippe Djian": "Écrivain français connu pour ses romans contemporains.",
  "Anonyme": "Auteur ou créateur dont l'identité est inconnue.",
  "Clifford Simak": "Écrivain américain de science-fiction connu pour ses récits humanistes",
  "Lewis Carroll": "Écrivain anglais célèbre pour \"Alice au pays des merveilles\".",
  "Samuel Johnson": "Écrivain et lexicographe anglais célèbre pour son dictionnaire.",
  "Charles Kingsley": "Écrivain et prêtre anglais connu pour ses romans et sermons.",
  "Sinead O’Connor": "Chanteuse irlandaise connue pour sa voix puissante et son hit \"Nothing",
  "Léon-Paul Fargue": "Poète et essayiste français reconnu pour son style unique.",
  "François Mauriac": "Écrivain et essayiste français, lauréat du Prix Nobel de littérature.",
  "Wikipedia": "Encyclopédie collaborative en ligne, multilingue et gratuite.",
  "Dante Alighieri": "Poète italien célèbre pour La Divine Comédie.",
  "Francis Picabia": "Peintre et écrivain français, figure du dadaïsme et du surréalisme.",
  "Mathias Malzieu": "Musicien et écrivain français, leader du groupe Dionysos.",
  "Robert Desnos": "Poète français surréaliste célèbre pour ses écrits et résistances",
  "McCoy": "Personnage de fiction célèbre, souvent un médecin dans Star Trek.",
  "Michel Jonasz": "Chanteur et compositeur français de musique pop et jazz.",
  "Noctuel": "Projet musical de metal atmosphérique français",
  "Oscar Wilde": "Écrivain irlandais célèbre pour ses œuvres satiriques et son style fla",
  "atoute.org": "Site web dédié à la santé naturelle et au bien-être.",
  "Inconnu": "",
  "Georges Courteline": "Écrivain français connu pour ses pièces satiriques et comiques.",
  "Céline": "Nom de scène de la chanteuse française Céline Dion",
  "Denis Leary": "Acteur et comédien américain connu pour son humour satirique.",
  "Buffy contre les vampires": "Série télé fantastique sur une chasseuse de vampires.",
  "Björk": "Chanteuse et musicienne islandaise innovante et éclectique",
  "Henry de Montherlan": "",
  "Alphonse Daudet": "Écrivain français connu pour ses récits et nouvelles provinciaux.",
  "Sermons de Karras": "Textes religieux prononcés par le personnage Karras",
  "Proverbe irlandais": "Citation traditionnelle d'Irlande avec sagesse populaire.",
  "Didier Van Cauwelaert": "Écrivain français, connu pour ses romans et ses pièces de théâtre.",
  "Napoléon Bonaparte": "Militaire et homme d'État français, empereur et réformateur",
  "Winston L S Churchill": "Homme politique britannique, Premier ministre durant la Seconde Guerre",
  "Alessandro Baricco": "Écrivain italien connu pour ses romans et essais littéraires.",
  "Michel Tournier": "Écrivain français connu pour ses romans et contes philosophiques.",
  "Jean Baudrillard": "Philosophe français, père de la théorie de la simulation et de l'hyper",
  "Loi de Murphy": "Principe selon lequel tout ce qui peut mal tourner, tournera mal.",
  "Didier Erasme": "",
  "Yann Bloyet": "Pianiste et compositeur français, spécialiste du jazz et de la musique",
  "Yehudi Menuhin": "Violoniste et chef d'orchestre américain-britannique célèbre",
  "Bob Monkhouse": "Comédien et animateur britannique célèbre pour son humour et ses jeux ",
  "Goethe": "Écrivain et poète allemand, auteur de Faust.",
  "Henri de Régnier": "Poète et écrivain français symboliste.",
  "W. Congreve": "Dramaturge et poète anglais du théâtre restauré.",
  "Simonetta Greggio": "Écrivain italienne, auteure de romans et essais en français.",
  "Publius Syrus": "Auteur latin célèbre pour ses maximes morales et proverbes.",
  "Aurélien Scholl": "Journaliste et écrivain français connu pour ses chroniques et récits.",
  "Albert Camus": "Écrivain et philosophe français, auteur de L'Étranger.",
  "Robert Goffin": "Écrivain belge, pionnier de la poésie jazz.",
  "Charlie la licorne": "Animation humoristique mettant en scène une licorne nommée Charlie.",
  "Thomas Fuller": "Écrivain et historien anglais connu pour ses anecdotes et proverbes.",
  "Simone de Beauvoir": "Philosophe et écrivaine française, pionnière du féminisme.",
  "Louis Aragon": "Poète et écrivain français, figure du surréalisme et du communisme.",
  "Bouddha": "Fondateur du bouddhisme, enseignant spirituel de l'Inde ancienne.",
  "Régis Debray": "Intellectuel français, spécialiste de la communication et politique.",
  "André Ruellan": "Écrivain français de science-fiction et d'horreur.",
  "Philippe Geluck": "Dessinateur et humoriste belge, créateur du Chat.",
  "Albert Cohen": "Écrivain franco-suisse connu pour \"Belle du Seigneur\".",
  "Mark Twain": "Écrivain américain célèbre pour ses romans sur le Mississippi.",
  "Serge Beucler": "Entrepreneur et innovateur français dans le domaine digital.",
  "Jean-Marie Gourio": "Écrivain français connu pour son humour et ses chroniques",
  "Friedrich Nietzsche": "Philosophe allemand, connu pour sa critique de la morale et la volonté",
  "Hubert Aquin": "Écrivain et militant québécois connu pour ses romans et engagements po",
  "Martial Villemin": "Personne impliquée dans l'affaire criminelle Villemin en France.",
  "Somerset Maugham": "Écrivain britannique célèbre pour ses romans et pièces de théâtre.",
  "Alan Bennet": "Écrivain et dramaturge britannique célèbre pour ses pièces et monologu",
  "Al-Moutanabbi": "Poète arabe célèbre pour sa langue éloquente et sa sagesse.",
  "Gerard Kornelis Van Het Reve": "Écrivain néerlandais connu pour ses œuvres provocatrices et autobiogra",
  "Victor Hugo": "Écrivain français majeur, auteur des Misérables et Notre-Dame.",
  "Jean-Paul Grousset": "Historien et géographe français spécialisé dans l'Asie centrale.",
  "Jean-Paul Sartre": "Philosophe et écrivain français, figure du existentialisme.",
  "Alain Pontaut": "Expert français en gestion des risques naturels et catastrophes.",
  "John Milton": "Poète anglais célèbre pour \"Le Paradis perdu\".",
  "Carlos Ruis Zafon": "Écrivain espagnol célèbre pour ses romans mystérieux et gothiques.",
  "Lovecraft": "Écrivain américain, maître de l'horreur cosmique et du fantastique.",
  "James Aggrey": "Éducateur et activiste ghanéen, promoteur de l'éducation en Afrique.",
  "Grégoire Lacroix": "Pianiste et compositeur canadien de jazz contemporain.",
  "Jorge Luis Borges": "Écrivain argentin célèbre pour ses nouvelles et sa littérature fantast",
  "Stéphane Collaro": "Animateur et producteur de télévision français.",
  "Morpheus": "Personnage de la mythologie grecque, dieu des rêves.",
  "Delfeil de Ton": "Écrivain et journaliste français, critique littéraire renommé",
  "Proverbe": "Formule courte exprimant une vérité ou un conseil populaire.",
  "Jean-Marie Adiaffi": "Écrivain ivoirien et poète, figure de la littérature africaine francop",
  "Stendhal": "Écrivain français, auteur de 'Le Rouge et le Noir'.",
  "Jean Cocteau": "Poète, dramaturge et cinéaste français influent du XXe siècle",
  "J. R. R. Tolkien": "Auteur britannique, créateur du Seigneur des Anneaux et du Hobbit.",
  "Bertrand Russell": "Philosophe et mathématicien britannique, pionnier de la logique modern",
  "Helen Keller": "Écrivaine et militante sourde-aveugle américaine",
  "Marcel Dassault": "Industriel et homme politique français, fondateur de Dassault Aviation",
  "Léo Campion": "Acteur et écrivain belge, spécialiste du théâtre et de la marionnette.",
  "Joyce Carey": "Actrice britannique connue pour ses rôles au théâtre et au cinéma.",
  "Francis Scott Fitzgerald": "Écrivain américain célèbre pour \"Gatsby le Magnifique\".",
  "Michael Palmer": "Écrivain américain de romans policiers et thrillers médicaux",
  "Werner Von Braun": "Ingénieur et pionnier de la fusée allemand-américain.",
  "Alexandre Dumas": "Écrivain français célèbre pour ses romans d'aventure.",
  "Karine Tuil": "Écrivaine française contemporaine, auteur de romans sociaux.",
  "Proverbe russe": "Expression traditionnelle russe reflétant la sagesse populaire.",
  "Jean de La Bruyère": "Écrivain français célèbre pour ses maximes et portraits satiriques.",
  "Jacques Deval": "Écrivain et scénariste français, connu pour ses pièces et films.",
  "Forum (anonyme)": "Plateforme en ligne pour discussions anonymes.",
  "Rodolphe Töpffer": "Auteur suisse considéré comme le père de la bande dessinée.",
  "John Alexander Tristram": "",
  "Winston Churchill": "Premier ministre britannique et leader durant la Seconde Guerre mondia",
  "Jean Echenoz": "Écrivain français connu pour ses romans innovants et subtils.",
  "Sacha Guitry": "Dramaturge, acteur et réalisateur français célèbre pour ses pièces et ",
  "Moses Isegawa": "Écrivain ougandais connu pour ses romans traitant de l'histoire et soc",
  "George Bernard Shaw": "Dramaturge irlandais, auteur et critique social influent.",
  "Alexandre Ostrovski": "Dramaturge russe célèbre pour ses pièces réalistes et sociales.",
  "Daniel Pennac": "Écrivain français connu pour ses romans et ses œuvres jeunesse.",
  "Montesquieu": "Philosophe et juriste français, auteur de 'L'Esprit des lois'.",
  "Henri Barbusse": "Écrivain français connu pour son roman La Flamme, pacifiste engagé",
  "Gustave Flaubert": "Écrivain français célèbre pour son roman 'Madame Bovary'.",
  "André Pronovost": "Joueur canadien de hockey sur glace",
  "François Moreau": "Historien français spécialisé dans l'histoire contemporaine.",
  "Prosper Mérimée": "Écrivain français connu pour \"Carmen\" et ses nouvelles historiques.",
  "Ray Bradberry": "",
  "Chevalier de Méré": "Noble français amateur de jeux et premiers contributeurs aux probabili",
  "Marc Twain": "Écrivain américain célèbre pour ses œuvres comme Les Aventures de Tom ",
  "Louis Dumur": "Personnalité dont les détails spécifiques ne sont pas disponibles",
  "Michèle Bernier": "Actrice et humoriste française reconnue pour ses spectacles comiques.",
  "Otto Lilienthal": "Pionnier allemand de l'aviation, premier à réussir des vols planés con",
  "Alphonse daudet": "Écrivain français connu pour ses récits et nouvelles réalistes.",
  "Dorothy Parker": "Écrivaine et critique américaine, célèbre pour son esprit acéré.",
  "Alphonse Allais": "Écrivain et humoriste français connu pour son humour absurde et ses je",
  "Jiddu Krishnamurti": "Philosophe indien, conférencier sur la spiritualité et la psychologie.",
  "William Faulkner": "Écrivain américain célèbre pour ses romans du Sud des États-Unis.",
  "Emil Michel Cioran": "Philosophe et essayiste roumain, connu pour son pessimisme.",
  "Jean François Marmontel": "Écrivain et historien français du XVIIIe siècle.",
  "Léo Bertrand": "Homme politique français, membre du parti Les Républicains.",
  "Théodore Adorno": "Philosophe et sociologue allemand, figure majeure de l'École de Francf",
  "Laurent Ruquier": "Animateur et humoriste français connu pour ses émissions de radio et T",
  "César Auguste": "Premier empereur romain, fondateur de l'Empire romain.",
  "Molière": "Dramaturge français célèbre pour ses comédies classiques.",
  "Lao She": "Écrivain chinois célèbre pour ses romans et pièces de théâtre.",
  "Kheira Chakor": "Joueuse française de handball évoluant en équipe nationale.",
  "Alain": "Prénom masculin courant en français.",
  "Journal Officiel de la République Française, 1981": "Publication officielle des lois et décrets en France.",
  "Guglielmo Ferrero": "Historien et écrivain italien spécialisé dans l'Antiquité et la politi",
  "Chamfort": "Écrivain et moraliste français célèbre pour ses maximes.",
  "Antoine de Saint-Exupéry": "Écrivain et aviateur français, auteur du Petit Prince.",
  "J.B. Rousse": "Auteur français spécialisé dans le roman historique et la bande dessin",
  "André Gide": "Écrivain français, Prix Nobel de littérature, connu pour ses romans.",
  "Felicia Hemans": "Poétesse britannique reconnue pour ses poèmes romantiques et patriotiq",
  "Tristan Bernard": "Écrivain et dramaturge français connu pour ses comédies et romans.",
  "Jean Gastaldi": "Chercheur et enseignant en philosophie française",
  "Alexandre Pope": "Poète et critique littéraire anglais du XVIIIe siècle.",
  "Jakob Böhme": "Philosophe mystique allemand connu pour ses écrits spirituels.",
  "Jules Barbey d’Aurevilly": "Écrivain français connu pour son style gothique et ses contes.",
  "Jean Giraudoux": "Écrivain et dramaturge français connu pour ses œuvres poétiques et phi",
  "Pierre Dac": "Humoriste français célèbre pour ses jeux de mots et sketches satirique",
  "Friedrich Wilhelm Nietzsche": "Philosophe allemand, critique de la morale traditionnelle et du nihili",
  "George Sand": "Romancière française célèbre pour ses œuvres et son engagement social.",
  "Joe Lewis": "Boxeur et acteur britannique célèbre pour ses combats et films.",
  "Epicure": "Philosophe grec fondant l'épicurisme, axé sur le plaisir modéré",
  "Christine Arnothy": "Écrivaine française d'origine hongroise, connue pour ses récits autobi",
  "John Donne": "Poète et prêtre anglican anglais, connu pour sa poésie métaphysique.",
  "Boris Vian": "Écrivain, poète et musicien français célèbre pour son œuvre éclectique",
  "Francis Blanche": "Acteur et humoriste français célèbre pour ses sketches et doublages.",
  "Pauline Michel": "Écrivaine et poétesse canadienne francophone.",
  "Rowland Watkins": "",
  "Chen Zhuhuang": "Peintre chinois contemporain connu pour ses œuvres classiques.",
  "Rivarol": "Écrivain et polémiste royaliste français célèbre pour ses lettres crit",
  "Georges Duhame": "Artiste français reconnu pour ses œuvres contemporaines.",
  "Clément d’Alexandrie": "Théologien chrétien ancien, auteur de commentaires bibliques.",
  "Voltaire": "Écrivain et philosophe français du XVIIIe siècle, auteur des Lumières",
  "Ylipe": "Artiste français connu pour ses dessins et textes humoristiques.",
  "Larry Baker": "Nom courant sans information spécifique disponible",
  "Marguerite Yourcenar": "Écrivaine française, première femme à l'Académie française.",
  "Jean-Jacques Rousseau": "Philosophe français influent du XVIIIe siècle, auteur du Contrat socia",
  "Anatole France": "Écrivain français célèbre pour ses romans et ses essais.",
  "Jacques Folch-Ribas": "Écrivain et critique littéraire franco-canadien.",
  "Joseph Addison": "Écrivain et homme politique anglais, connu pour ses essais.",
  "Samuel Butler": "Écrivain anglais et critique social, connu pour ses satires.",
  "Gilbert Keith Chesterton": "Écrivain anglais connu pour ses essais, romans et personnages détectiv",
  "Marcel Proust": "Écrivain français célèbre pour son œuvre « À la recherche du temps per",
  "Alice au pays des merveilles": "Roman fantastique de Lewis Carroll sur un voyage imaginaire.",
  "Marc Gendron": "Auteur et spécialiste québécois en communication et relations publique",
  "Paul Valéry": "Poète et philosophe français, figure du symbolisme et de l'esprit crit",
  "André Lévy": "Écrivain et sinologue français, spécialiste de la littérature chinoise",
  "Anthony Dacheville": "Réalisateur et scénariste français de films et documentaires.",
  "Dave Small": "Joueur de basket-ball américain connu pour sa carrière universitaire.",
  "Alan Jay Perlis": "Informaticien américain, pionnier en programmation informatique.",
  "Renée Bazin": "Écrivain et juriste français, spécialiste du droit international.",
  "Howard Phillips Lovecraft": "Écrivain américain, pionnier de la littérature d'horreur cosmique.",
  "André Chenier": "Poète français célèbre pour son œuvre pendant la Révolution française.",
  "Taylor Caldwell": "Romancière américaine connue pour ses romans historiques et dramatique",
  "Noam Chomski": "Linguiste et philosophe américain, pionnier en linguistique.",
  "Marc Caussidière": "Révolutionnaire français et préfet de police au XIXe siècle.",
  "Une maman bien pratique": "Film français sur les péripéties d'une mère débrouillarde.",
  "Alan Perlis": "Pionnier américain en informatique et premier lauréat du prix Turing.",
  "Tristan l'Hermite": "Poète et dramaturge français de la Renaissance.",
  "Vauvenargue": "Philosophe et moraliste français du XVIIIe siècle.",
  "Jacques Bergier": "Écrivain et scientifique français d'origine russe, spécialiste en ufol",
  "Pierre Corneille": "Dramaturge français classique, auteur de tragédies célèbres.",
  "Baltasar Gracián": "Écrivain et philosophe espagnol, maître du baroque et de la sagesse mo",
  "Milan Kundera": "Écrivain tchèque célèbre pour ses romans philosophiques.",
  "Muriel Robin": "Comédienne et humoriste française célèbre pour ses sketches.",
  "Théognis de Mégare": "Poète grec archaïque connu pour ses maximes morales.",
  "Louise Thaden": "Pilote américaine célèbre pour ses records d'aviation",
  "Charles Nodier": "Écrivain et bibliothécaire français influent du romantisme.",
  "Orhan Pamuk": "Écrivain turc, lauréat du prix Nobel de littérature.",
  "B.Franklin": "Inventeur et homme d'État américain célèbre pour l'électricité.",
  "Jean Racine": "Dramaturge français célèbre pour ses tragédies classiques.",
  "Lao Tseu": "Philosophe chinois fondateur du taoïsme.",
  "Proverbe japonais": "Expression traditionnelle japonaise transmettant sagesse et valeurs.",
  "Pausanias": "Général et géographe grec connu pour ses écrits sur la Grèce ancienne.",
  "J.R.R.Tolkien": "Auteur britannique célèbre pour Le Seigneur des Anneaux et Bilbo",
  "Kōbō Abe": "Écrivain japonais connu pour ses romans et pièces de théâtre abstraits",
  "Eleanor Roosevelt": "Première dame américaine, défenseure des droits humains et diplomate.",
  "Pierre Doris": "Acteur et humoriste français reconnu pour ses sketches et films.",
  "Thomas Jefferson": "Troisième président des États-Unis, principal auteur de la Déclaration",
  "Georges Dor": "Auteur-compositeur-interprète et poète québécois.",
  "Cholem Aleichem": "Écrivain yiddish célèbre pour ses histoires humoristiques juives.",
  "Dave Bary": "Musicien et auteur-compositeur britannique.",
  "Bill Gates": "Co-fondateur de Microsoft et philanthrope américain.",
  "Miguel de Cervantes": "Écrivain espagnol, auteur de Don Quichotte.",
  "Xavier Forneret": "Écrivain et poète français du XIXe siècle, connu pour son style origin",
  "Henry Fielding": "Écrivain anglais célèbre pour ses romans satiriques et comédies.",
  "Paul Véron": "Auteur et spécialiste français, connu pour ses travaux en généalogie.",
  "Honoré de Balzac": "Écrivain français célèbre pour La Comédie humaine.",
  "Gandalf": "Magicien sage et puissant dans Le Seigneur des Anneaux.",
  "Fernand Vandérem": "Cycliste belge connu pour ses compétitions sur route.",
  "Bernard Arcand": "Anthropologue québécois spécialisé en culture et communication.",
  "Hazrat Ali": "Cousin et gendre du prophète Mahomet, figure centrale de l'islam chiit",
  "Nicolas Hulot": "Militant écologiste et ancien ministre français de la Transition écolo",
  "Joël Jouanneau": "Metteur en scène et dramaturge français.",
  "George Jean Nathan": "Critique dramatique et éditeur américain influent.",
  "Lord Byron": "Poète romantique anglais célèbre pour son œuvre et son charisme.",
  "Michael Babcock": "",
  "Académie de Bordeau": "Institution française dédiée à l'enseignement et à la recherche à Bord",
  "Henri Michaux": "Poète et peintre belge connu pour son œuvre surréaliste et exploratoir",
  "G.C.Lichtenberg": "Écrivain et scientifique allemand, connu pour ses aphorismes.",
  "Star Wars": "Saga cinématographique de science-fiction épique créée par George Luca",
  "Henry de Montherlant": "Écrivain et dramaturge français, connu pour ses œuvres classiques.",
  "Chaval": "Dessinateur français connu pour ses caricatures satiriques.",
  "Graham Greene": "Écrivain britannique célèbre pour ses romans explorant la morale et la",
  "Elbert Hubbard": "Écrivain et philosophe américain, promoteur de l'artisanat et du desig",
  "André Santin": "Auteur et journaliste français spécialisé en littérature et culture.",
  "Serge Gainsbourg": "Auteur-compositeur-interprète français célèbre pour sa musique et poés",
  "Proverbe tibétain": "Sagesse traditionnelle tibétaine exprimée en proverbes courts.",
  "Gimli": "Nain guerrier emblématique du Seigneur des Anneaux.",
  "Histoire": "Étude et récit des événements passés.",
  "Jean-Charles": "Prénom masculin d'origine française.",
  "Chawki Amari": "Essayiste et poète tunisien, explorant culture et société.",
  "Dicocitations": "Site web de citations et proverbes en français.",
  "Tom Baker": "Acteur britannique connu pour son rôle dans Doctor Who",
  "James Hastings": "Théologien et érudit biblique écossais, connu pour ses travaux littéra",
  "Andrew Lang": "Écrivain écossais connu pour ses recueils de contes populaires.",
  "Francis Ford Coppola": "Réalisateur et producteur de cinéma américain célèbre pour Le Parrain.",
  "Johnny Depp": "Acteur américain célèbre pour ses rôles variés et excentriques",
  "Bertrand Cèbe": "Écrivain et scénariste français reconnu dans la bande dessinée.",
  "Gérard de Nerval": "Poète et écrivain français connu pour ses œuvres romantique et son sty",
  "Angélique Planchette": "",
  "Jane Austen": "Romancière anglaise célèbre pour ses romans sur la société et l'amour.",
  "Maître Eckhart": "Théologien et philosophe mystique allemand du Moyen Âge.",
  "Louis de Cussy": "Écrivain et diplomate français, spécialiste des relations internationa",
  "Raoul Poncho": "",
  "André Frossar": "",
  "Napoléon Ier": "Empereur français et chef militaire célèbre pour ses conquêtes.",
  "Reine Malouin": "Artiste québécoise connue pour ses chansons engagées et poétiques.",
  "W.C. Fields": "Comédien et humoriste américain célèbre pour son humour caustique.",
  "Yi-king": "Ancien texte chinois de divination fondé sur 64 hexagrammes.",
  "Hafiz": "Poète persan célèbre pour ses ghazals mystiques et lyriques.",
  "Francis Dannemark": "",
  "Gao Xingjian": "Écrivain et dramaturge sino-français, prix Nobel de littérature.",
  "Jean-François Deniau": "Hommes politique et diplomate français, écrivain renommé.",
  "Isaac Asimov": "Auteur américain célèbre pour ses œuvres de science-fiction et ses ess",
  "Plaute": "Dramaturge romain célèbre pour ses comédies antiques.",
  "Sri Guru Granth Sahib": "Livre saint central du sikhisme, recueil des hymnes sacrés.",
  "Charles de Leusse": "Peintre français connu pour ses œuvres détaillées et colorées.",
  "Comédie": "Genre théâtral et cinématographique centré sur l'humour.",
  "Jonathan Swift": "Écrivain irlandais, auteur de \"Les Voyages de Gulliver\".",
  "Louis-Ferdinand Céline": "Écrivain français connu pour son style polémique et innovant.",
  "James Joyce": "Écrivain irlandais, auteur de \"Ulysse\" et du \"Portrait de l'artiste\".",
  "Fred Metcalf": "Footballeur australien de la Liga de fútbol australiano.",
  "Jean-François Kahn": "Journaliste et essayiste français reconnu pour ses analyses politiques",
  "Heinrich Heine": "Poète et essayiste allemand, critique de la société et de la politique",
  "Ahiqar": "Conseiller sage dans les traditions mésopotamiennes anciennes",
  "Gilbert Cesbron": "Écrivain français connu pour ses romans sociaux et humanistes.",
  "Patrick Sébastien": "Animateur et chanteur français connu pour ses émissions de divertissem",
  "Jean de Rotrou": "Dramaturge français célèbre du théâtre baroque.",
  "Sandor Brody": "",
  "Charles-Augustin Sainte-Beuve": "Critique littéraire français célèbre pour ses portraits d'auteurs.",
  "Stanislaw Jerzy Lec": "Poète et aphoriste polonais connu pour ses pensées satiriques.",
  "La Bible": "Recueil sacré des textes religieux du judaïsme et du christianisme",
  "William Blake": "Poète et artiste britannique, connu pour sa poésie mystique et gravure",
  "Lord Dunsany": "Écrivain irlandais de fantasy et de récits légendaires.",
  "Baruch Spinoza": "Philosophe néerlandais, fondateur du rationalisme moderne.",
  "Régis Hauser": "Psychologue et chercheur en neurosciences cognitives français.",
  "Frédéric Dard": "Écrivain français célèbre pour la série policière San-Antonio.",
  "Jacques Prévert": "Poète et scénariste français célèbre pour ses poèmes et chansons.",
  "Proverbe yiddish": "Dicton traditionnel exprimant une sagesse populaire juive.",
  "Amory Lovins": "Physicien américain et expert en énergie durable.",
  "William Shakespeare, Henry VI, IIIe partie": "Pièce historique de Shakespeare sur la guerre des Deux-Roses.",
  "Umberto Eco": "Écrivain et sémioticien italien, auteur de « Le Nom de la rose ».",
  "Jean-Paul Lebourhis": "Chercheur en sciences sociales spécialisé en histoire culturelle.",
  "Charles Péguy": "Écrivain et poète français engagé dans la littérature et la politique.",
  "Dracula, 1992": "Film d'horreur fantastique réalisé par Francis Ford Coppola.",
  "Roland Bacri": "Acteur français connu pour ses rôles au cinéma et au théâtre.",
  "William Thackeray": "Écrivain britannique connu pour \"Vanity Fair\", roman satirique.",
  "Craig Clairborne": "Critique culinaire américain célèbre pour son travail au New York Time",
  "Robert Heinlein": "Écrivain américain de science-fiction, auteur influent et prolifique",
  "Futura-Sciences": "Site web français dédié aux actualités et dossiers scientifiques.",
  "Jeanson René Château": "Auteur français connu pour ses œuvres littéraires.",
  "Arthur Schopenhauer": "Philosophe allemand célèbre pour sa vision pessimiste du monde.",
  "Proverbe africain": "Expression traditionnelle reflétant la sagesse africaine.",
  "Lord of War": "Film sur le trafic d'armes et ses conséquences.",
  "Proverbe arabe": "Maxime populaire reflétant la sagesse arabe traditionnelle.",
  "Chateaubriand": "Écrivain et homme politique français, pionnier du romantisme.",
  "Francisco de Quevedo": "Poète et écrivain espagnol du Siècle d'or, maître du conceptisme.",
  "Joseph P. Kennedy": "Homme d'affaires et patriarche de la famille Kennedy.",
  "Proverbe brahman": "Expression courte exprimant une vérité ou une sagesse traditionnelle b",
  "Gérard Haas": "Chercheur en informatique spécialisé en systèmes distribués.",
  "Romain Gary": "Écrivain et diplomate français d'origine lettone.",
  "Cicéron": "Orateur et homme politique romain de l'Antiquité",
  "François Rabelais": "Écrivain français de la Renaissance, connu pour ses œuvres satiriques.",
  "Anne-Marie MacDonald": "Écrivaine canadienne reconnue pour ses romans et pièces de théâtre.",
  "Sidonie Gabrielle Colette": "Écrivaine française célèbre pour ses romans et sa vie artistique.",
  "Nagarjuna": "Acteur et producteur indien du cinéma télougou.",
  "Coluche": "Humoriste et acteur français célèbre pour son humour satirique.",
  "Angelus Silesius": "Poète et mystique chrétien allemand du XVIIe siècle",
  "François Cavanna": "Écrivain et journaliste français, cofondateur de Hara-Kiri et Charlie ",
  "Chester Anthony": "",
  "Alfred Hitchcock": "Réalisateur britannique célèbre pour ses films à suspense et thrillers",
  "Buffy contre les vampires (série)": "Série télévisée sur une chasseuse de vampires adolescente.",
  "Albert Caraco": "Écrivain et philosophe franco-uruguayen connu pour sa pensée pessimist",
  "Proverbe tanzanien": "Sagesse traditionnelle de Tanzanie exprimée en proverbes courts.",
  "Calvin Coolidge": "30e président des États-Unis, connu pour sa politique conservatrice.",
  "Schwaller de Lubicz": "Égyptologue suisse connu pour ses études hermétiques de l'Égypte ancie",
  "Corneille": "Poète et dramaturge français du XVIIe siècle, célèbre pour ses tragédi",
  "Bible": "Recueil sacré des textes religieux du judaïsme et du christianisme",
  "Jacques Brel": "Chanteur et compositeur belge célèbre pour ses chansons poétiques.",
  "Robert Aron": "Historien et écrivain français, cofondateur du CELF",
  "Ambrose Bierce": "Écrivain et journaliste américain, connu pour ses récits macabres.",
  "Lao-Tseu": "Philosophe chinois fondateur du taoïsme et auteur du Tao Te King.",
  "Jean-Louis Hue": "Écrivain et journaliste français, spécialisé en littérature.",
  "bibliothequeinterdite.fr": "Site dédié aux livres et ressources rares ou interdites.",
  "Yosa Buson": "Poète haïku et peintre japonais de l'époque Edo.",
  "Charlie et la Chocolaterie": "Roman fantastique de Roald Dahl sur une fabrique de chocolat magique.",
  "Henri Louis Mencken": "Écrivain et journaliste américain, critique culturel influent.",
  "Carlos Castaneda": "Écrivain et anthropologue, connu pour ses livres sur le chamanisme.",
  "Martin Luther King": "Leader américain des droits civiques et défenseur de la non-violence.",
  "Burt Lancaster": "Acteur américain célèbre pour ses rôles dans des films classiques.",
  "Théodore Mono": "Écrivain et journaliste français.",
  "Robinson Crusoé": "Roman d'aventure sur un naufragé isolé sur une île déserte.",
  "Jean Gabin": "Acteur français célèbre pour ses rôles dans le cinéma classique.",
  "Ambroise Paré": "Chirurgien français reconnu pour ses innovations en chirurgie.",
  "William Shakespeare": "Dramaturge et poète anglais, auteur d'œuvres classiques célèbres.",
  "Oswald Spengler": "Philosophe allemand connu pour sa théorie sur le déclin des civilisati",
  "Proverbe malgache": "Sagesse traditionnelle de Madagascar exprimée en proverbes.",
  "Archipresse": "Maison d'édition française spécialisée dans la presse audiovisuelle.",
  "Illustre inconnu": "Personne célèbre dont l'identité est inconnue",
  "Guy-Marc Fournier": "Réalisateur et scénariste canadien connu pour ses œuvres télévisuelles",
  "François Truffaut": "Réalisateur français, pionnier de la Nouvelle Vague au cinéma.",
  "Dante": "Poète italien célèbre pour la Divine Comédie.",
  "Jacques Attali": "Économiste et écrivain français, conseiller politique influent.",
  "Pierre Legaré": "Humoriste et conférencier québécois connu pour son humour noir.",
  "Carl Gustav Jung": "Psychiatre suisse, fondateur de la psychologie analytique.",
  "Patrick Cauvin": "Écrivain français, auteur de romans populaires",
  "Proverbe allemand": "Dicton d’origine allemande",
  "Jean Rostand": "Biologiste et écrivain français",
  "A. Chavanne": "",
  "Luc Fayard": "Journaliste et auteur français",
  "Paul Eluard": "Poète majeur du surréalisme français",
  "Jules Renard": "Écrivain français, auteur de \"Poil de Carotte\"",
  "Van Gogh": "Peintre néerlandais postimpressionniste",
  "Proverbe serbo-croate": "Dicton traditionnel serbo-croate",
  "Claude Jasmin": "Écrivain et scénariste québécois",
  "Henry Wadsworth Longfellow": "Poète américain renommé",
  "Jerold Rochwald": "",
  "Dicton arabe": "Dicton issu de la tradition arabe",
  "Eva Peron": "Figure politique argentine, épouse de Perón",
  "Proverbe haoussa": "Dicton de la culture haoussa",
  "Harriet Beecher Stowe": "Romancière américaine, auteure d’« Uncle Tom »",
  "Proverbe zen": "Dicton issu de la tradition zen",
  "Proverbe brésilien": "Dicton populaire du Brésil",
  "Paul Ohl": "Écrivain et aventurier canadien",
  "François Bayrou": "Homme politique français, centriste",
  "MASSILLON": "Prédicateur et évêque français du XVIIe siècle",
  "Geiler de Kaysersberg": "Prédicateur allemand de la Renaissance",
  "Proverbe suédois": "Dicton traditionnel suédois",
  "Robert Bridges": "Poète anglais, ancien poète lauréat",
  "Le Nom de la rose (film)": "Film policier médiéval inspiré du roman d’Eco",
  "Saint Augustin": "Philosophe et théologien chrétien",
  "Cyril Bachelier": "",
  "Michaël Krüger": "Écrivain, éditeur et poète allemand",
  "Saint Luc": "Évangéliste du Nouveau Testament",
  "Bernard Noël": "Poète, romancier et essayiste français",
  "Xavier de Maistre": "Écrivain savoyard, auteur de récits courts",
  "Francis Bacon": "Philosophe anglais, pionnier de l’empirisme",
  "Benoîs Marsant": "",
  "Jean-Loup Chiflet": "Auteur français spécialisé dans l’humour linguistique",
  "Henry Barbusse": "Écrivain français, auteur du « Feu »",
  "Edgar Morin": "Sociologue et philosophe français",
  "Théognis": "Poète grec archaïque",
  "René Goscinny": "Scénariste de BD, co-créateur d’Astérix",
  "Franz Kafka": "Écrivain majeur de langue allemande",
  "Antoine de Saint Exupéry": "Écrivain aviateur français, auteur du Petit Prince",
  "Annelou Dupuis": "",
  "Pierre Mac Orlan": "Écrivain français, auteur d’aventures",
  "ranck Hammoutène": "",
  "Gabrielle Roy": "Romancière canadienne francophone",
  "Washington Irving": "Écrivain américain, auteur de contes",
  "Marcel Mauss": "Sociologue et anthropologue français",
  "Albert Einstein": "Physicien théoricien, auteur de la relativité",
  "Dave Barry": "Chroniqueur et humoriste américain",
  "Barry Marter": "",
  "Philippe Labro": "Écrivain, journaliste et cinéaste français",
  "Robert von Musil": "Écrivain autrichien, auteur de l’Homme sans qualités",
  "Vassilis Alexakis": "Écrivain franco-grec, bilingue",
  "Bruno Samson": "",
  "Samuel Taylor Coleridge": "Poète anglais, cofondateur du romantisme",
  "Bruno Masure": "Journaliste et présentateur français",
  "Konrad Zacharias Lorenz": "Éthologue autrichien, spécialiste du comportement",
  "Etienne Grandterre": "",
  "Alan Lewis": "",
  "Jean Chalon": "Écrivain et biographe français",
  "Françoise Lefèvre": "Romancière française contemporaine",
  "Vladimir Nabokov": "Écrivain russo-américain, auteur de « Lolita »",
  "Thomas Beecham": "Chef d’orchestre britannique",
  "Taisen Deshimaru": "Maître zen japonais, diffuseur du zen en Europe",
  "David Orr": "",
  "Benjamin Winston": "",
  "Raymond Devos": "Humoriste et comédien français",
  "Philipe Bouvard": "Journaliste et animateur français",
  "Gandhi": "Leader indien de la non-violence",
  "Yves Thériault": "Écrivain canadien francophone",
  "Michel Folco": "Écrivain français, auteur de romans",
  "Proverbe anglais": "Dicton traditionnel anglais",
  "Sir Robert Watson-Watt": "Pionnier britannique du radar",
  "Jean Chalon": "Écrivain et biographe français",
  "Françoise Lefèvre": "Romancière française contemporaine",
  "Vladimir Nabokov": "Écrivain russo-américain, auteur de « Lolita »",
  "Thomas Beecham": "Chef d’orchestre britannique",
  "Taisen Deshimaru": "Maître zen japonais, diffuseur du zen en Europe",
  "David Orr": "",
  "Benjamin Winston": "",
  "Raymond Devos": "Humoriste et comédien français",
  "Philipe Bouvard": "Journaliste et animateur français",
  "Gandhi": "Leader indien de la non-violence",
  "Yves Thériault": "Écrivain canadien francophone",
  "Michel Folco": "Écrivain français, auteur de romans",
  "Proverbe anglais": "Dicton traditionnel anglais",
  "Sir Robert Watson-Watt": "Pionnier britannique du radar",
  "Jean Michel Ribes": "Dramaturge, metteur en scène et auteur français",
  "Philippe Besson": "Romancier français contemporain",
  "Gloria Swanson": "Actrice américaine du cinéma muet",
  "Simon Bolivar": "Libérateur et homme d’État sud-américain",
  "Auteur Anonyme": "Auteur dont l’identité est inconnue",
  "Laure Adler": "Journaliste, écrivaine et éditrice française",
  "Proverbe français": "Dicton traditionnel français",
  "D.B.Brown": "",
  "Planète aux trésors": "Film d’animation Disney de science-fiction",
  "Levison": "",
  "Miguel de Cervantès": "Écrivain espagnol, auteur de Don Quichotte",
  "Blaise Pascal": "Philosophe, savant et moraliste français",
  "Proverbe bulgare": "Dicton traditionnel bulgare",
  "Vauvenargues": "Moraliste et écrivain français",
  "Naguib Mahfouz": "Écrivain égyptien, prix Nobel",
  "Proverbe breton": "Dicton traditionnel breton",
  "Groucho Marx": "Humoriste américain, membre des Marx Brothers",
  "Roger Nimier": "Écrivain français du mouvement Hussard",
  "Eric Chevillard": "Écrivain français au style expérimental",
  "Guy Mouminoux": "Dessinateur et auteur de BD français",
  "Marie-Lyse Aston": "",
  "Anonym": "Auteur non identifié",
  "Proverbe romain": "Dicton issu de la tradition romaine",
  "Inspecteur Gordon": "Personnage de littérature jeunesse suédoise",
  "Horace": "Poète latin de l’époque augustéenne",
  "Jean Fourastié": "Économiste et sociologue français",
  "Anne de Bartillat": "Écrivaine française contemporaine",
  "André Laurendeau": "Écrivain et journaliste québécois",
  "Jacques Bainville": "Historien et journaliste français",
  "Louis Philipe compte de Ségur": "Diplomate et écrivain français",
  "Michel Bouthot": "Auteur de citations et aphorismes",
  "Proverbe marocain": "Dicton issu de la tradition marocaine",
  "Jacques Ferron": "Écrivain et médecin québécois",
  "Encyclopédie": "Ouvrage de référence rassemblant des savoirs",
  "Françoise Giroud": "Journaliste, écrivaine et femme politique française",
  "Jean Dion": "Chroniqueur et journaliste québécois",
  "Cliff Fadiman": "Écrivain, critique et anthologiste américain",
  "George S. Patton": "Général américain de la Seconde Guerre mondiale",
  "Juvénal": "Poète satirique latin",
  "Abbas Kiarostami": "Cinéaste iranien renommé",
  "Paulo Coelho": "Écrivain brésilien, auteur de l’Alchimiste",
  "Zoé Valdés": "Romancière cubaine",
  "Hervé Bazin": "Écrivain français, auteur de Vipère au poing"
}