export default [
  "Palimpsest - ein Manuskript oder Dokument, dessen ursprünglicher Text entfernt und überschrieben wurde, wobei jedoch Spuren des früheren Textes erhalten bleiben und eine Rekonstruktion der zugrunde liegenden Bedeutungsebenen ermöglichen.",
  "Allgegenwärtig - vorhanden oder überall gleichzeitig anzutreffen, so sehr, dass seine Präsenz eher angenommen als wahrgenommen wird, wie bei digitaler Vernetzung oder Hintergrundgeräuschen in Städten.",
  "Schleimer - eine Person, die diejenigen in Machtpositionen schmeichelt, um Gunst oder Vorteile zu erlangen, oft auf Kosten von Aufrichtigkeit oder Integrität, wodurch ein verzerrtes soziales Umfeld um die Autorität entsteht.",
  "Entropie - ein Maß für Unordnung oder Zufälligkeit in einem System, das verwendet wird, um die natürliche Tendenz von Systemen zu beschreiben, sich von geordneten Zuständen zu wahrscheinlicheren und weniger organisierten Konfigurationen zu bewegen.",
  "Anhedonie - die verminderte Fähigkeit, Freude an Aktivitäten zu empfinden, die normalerweise als angenehm empfunden werden, oft verbunden mit depressiven Zuständen oder neurologischen Funktionsstörungen.",
  "Obfuskieren - etwas absichtlich unklar, verwirrend oder schwer verständlich machen, insbesondere um Kritik zu verhindern oder Verantwortung in Kommunikation oder Entscheidungsprozessen zu vermeiden.",
  "Cynosure - etwas oder jemand, der zum zentralen Fokus der Aufmerksamkeit oder Bewunderung wird, nicht nur sichtbar, sondern auch fesselnd, der die Blicke und Absichten anderer auf sich zieht.",
  "Ephemer - von sehr kurzer Dauer, bevor sie schnell verblassen oder verschwinden, typischerweise verwendet, um Zustände, Erfahrungen oder Phänomene zu beschreiben, die nicht vollständig erfasst oder bewahrt werden können.",
  "Maelstrom – ein mächtiger und gewaltiger Strudel, der Dinge in sein Zentrum zieht, wird metaphorisch für chaotische Situationen verwendet, die Struktur oder Stabilität zerstören.",
  "Apathie – ein Zustand emotionaler Gleichgültigkeit, bei dem Reize, die normalerweise Interesse oder Besorgnis hervorrufen, keine Motivation, kein Engagement oder keine Reaktion beim Individuum auslösen.",
  "Irideszent – zeigt leuchtende Farben, die je nach Blickwinkel zu wechseln oder sich zu verändern scheinen, wie bei Seifenblasen, Vogelfedern oder bestimmten Mineraloberflächen zu sehen ist.",
  "Petrichor - das unverwechselbare und angenehme erdige Aroma, das aus trockenem Boden aufsteigt, wenn der erste Regen fällt, verursacht durch Öle, die von Pflanzen freigesetzt werden, und Verbindungen, die von Mikroben gebildet werden.",
  "Veraltet - nicht mehr allgemein gebräuchlich oder relevant, da es durch etwas Neueres oder Effektiveres ersetzt wurde, obwohl es möglicherweise in Archiven oder Altsystemen weiterhin vorhanden ist.",
  "Metamorphose - eine tiefgreifende Veränderung in Form, Struktur oder Charakter, biologisch bei Insekten zu beobachten und metaphorisch in Prozessen persönlicher oder gesellschaftlicher Transformation.",
  "Barometer - ein Instrument, das den atmosphärischen Druck misst, verwendet zur Vorhersage kurzzeitiger Wetteränderungen und im übertragenen Sinne zur Erfassung von Meinungs- oder Zustandsveränderungen.",
  "Sparsamkeit – extreme Unwilligkeit, Ressourcen zu verwenden, sei es Geld, Mühe oder Worte, was oft zu minimalen, aber funktionalen Ergebnissen auf Kosten von Großzügigkeit oder Reichhaltigkeit führt.",
  "Mercurial - gekennzeichnet durch schnelle und unvorhersehbare Stimmungs- oder Verhaltensänderungen, die an die wechselhafte Natur von Quecksilber erinnern und es schwierig machen, Erwartungen zu haben oder Vertrauen zu gewinnen.",
  "Rachsüchtig - den Wunsch habend oder zeigend, Rache zu nehmen, nicht nur ein Unrecht zu erinnern, sondern aktiv darauf abzuzielen, zu bestrafen oder Schaden zuzufügen.",
  "Lakonisch - Ideen mit sehr wenigen Worten ausdrückend, was zu einer Rede führt, die so knapp ist, dass sie als streng wahrgenommen wird und oft als selbstbewusst, kalt oder abschätzig interpretiert wird.",
  "Wechselhaftigkeit - eine Veränderung der Umstände oder des Schicksals, insbesondere eine, die unerwünscht ist oder außerhalb der eigenen Kontrolle liegt, wobei die Instabilität als ein natürliches Merkmal des Lebens betont wird.",
  "Eiferer - eine Person, die eine extreme und kompromisslose Hingabe an einen Glauben oder eine Sache zeigt, dabei oft Mäßigung ablehnt und gegensätzliche Perspektiven oder Konsequenzen ignoriert.",
  "Gebildet - umfassendes Wissen besitzend oder zeigend, das durch Lesen und Studium erworben wurde, nicht nur informiert, sondern tiefgehend gelernt in einer Weise, die Ausdruck und Analyse prägt.",
  "Dogmatisch - geneigt, Meinungen als unbestreitbare Wahrheiten darzustellen, Widerstand gegen Fragestellungen oder alternative Ansichten zu leisten und dadurch offene Untersuchungen im Diskurs oder in Institutionen zu verringern.",
  "Vorübergehend - nur für eine kurze Zeit andauernd, bevor es vergeht, insbesondere im Hinblick auf Zustände oder Populationen, die nur kurz existieren und nach einer Veränderung der Bedingungen nur begrenzte Spuren hinterlassen.",
  "Widerrufen - eine Entscheidung, ein Gesetz oder eine Vereinbarung aufheben, annullieren oder rückgängig machen, um den vorherigen Zustand wiederherzustellen oder zuvor geltende Verpflichtungen für nichtig zu erklären.",
  "Melancholie – eine tiefe, anhaltende Form der Traurigkeit, die nicht an unmittelbare Ursachen gebunden ist, historisch als Temperament beschrieben und heute mit depressiver Stimmung in Verbindung gebracht.",
  "Synekdoche – eine rhetorische Figur, bei der ein Teil für das Ganze oder das Ganze für einen Teil steht, wodurch die Perspektive durch die Veränderung des Repräsentationsmaßstabs verschoben wird.",
  "Panacea - ein hypothetisches Allheilmittel, das in der Lage ist, jede Krankheit oder jedes Problem zu beheben, oft rhetorisch verwendet, um naive oder vereinfachte Lösungen zu kritisieren.",
  "Unveränderlich - nicht in der Lage, im Laufe der Zeit verändert oder abgeändert zu werden, sei es absichtlich oder durch äußere Einflüsse, häufig verwendet, um Prinzipien, mathematische Wahrheiten oder Zustände von Code zu beschreiben.",
  "Gelassenheit – ein Zustand psychischer Ausgeglichenheit und Stabilität unter Stress oder Konflikten, bei dem emotionale Reaktionen maßvoll bleiben und nicht volatil oder extrem sind.",
  "Ambivalenz – ein Zustand, in dem eine Person gleichzeitig zwei entgegengesetzte Gefühle oder Überzeugungen hegt, was zu Zögern und Schwierigkeiten bei der Entscheidung oder der Festlegung auf eine einzige Vorgehensweise führt.",
  "Conflate - zwei oder mehr Ideen, Themen oder Informationsstücke zu einer Einheit zusammenzuführen, sodass deren Unterschiede verwischt werden und dies zu einer irreführenden Interpretation oder Analyse führen kann.",
  "Denouement - die abschließende Phase einer Erzählung, in der komplexe Handlungsstränge aufgelöst und Spannungen gelöst werden, wodurch die Folgen, die dem Höhepunkt folgen, offenbart werden.",
  "Equivocate - absichtlich vage oder mehrdeutig sprechen, um eine klare Position zu vermeiden oder irrezuführen, ohne eine direkte Unwahrheit zu sagen.",
  "Pingelig – zeigt extreme Aufmerksamkeit für Details und Genauigkeit, oft kombiniert mit einer starken Vorliebe für Ordnung oder Sauberkeit und einer niedrigen Toleranz für Fehler.",
  "Gregoriate – eine Struktur des Denkens, der Politik oder des Verhaltens gemäß einem neuen dominanten Prinzip neu organisieren oder umgestalten, wobei oft das zuvor Festgefahrene ersetzt wird.",
  "Heuristik - eine praktische Methode zur Problemlösung oder Entscheidungsfindung, die erfahrungsbasierte Strategien statt erschöpfender Logik oder garantierter Genauigkeit verwendet.",
  "Undurchschaubar – unmöglich zu interpretieren oder zu verstehen aufgrund der Undurchsichtigkeit von Motiv, Ausdruck oder Struktur, wodurch Beobachter über die zugrunde liegende Bedeutung im Unklaren gelassen werden.",
  "Juxtaposition – die Platzierung von zwei Elementen nebeneinander, um Kontraste, Ähnlichkeiten oder Spannungen hervorzuheben, die nur durch ihre Nähe entstehen.",
  "Kaleidoskopisch - sich schnell ändernd in Muster oder Erscheinung auf eine Weise, die ein Gefühl ständiger Neuformung erzeugt, wie die sich verändernden Spiegel in einem Kaleidoskop.",
  "Liminal - bezogen auf eine Grenze oder Schwelle zwischen zwei Zuständen, Phasen oder Identitäten, an der Transformation, Mehrdeutigkeit oder Instabilität natürlicherweise konzentriert sind.",
  "Manifest - eine formelle schriftliche Erklärung, die die Grundsätze, Absichten oder Forderungen einer Bewegung oder Einzelperson bekanntgibt und darauf abzielt, Meinungen zu beeinflussen oder Veränderungen einzuleiten.",
  "Nihilismus – der Glaube, dass das Leben keinen inhärenten Sinn, Zweck oder Wert besitzt, oft verbunden mit Skepsis gegenüber moralischen, religiösen oder politischen Wahrheitsansprüchen.",
  "Unterwürfig - zeigt eine übertriebene und übermäßige Bereitschaft zu dienen oder zu gehorchen, insbesondere gegenüber Mächtigen, was oft als demütigend oder manipulativ wahrgenommen wird.",
  "Paradoxon - eine Aussage oder Situation, die auf den ersten Blick widersprüchlich oder absurd erscheint, aber bei genauerer Betrachtung eine zugrunde liegende Wahrheit enthalten kann.",
  "Quixotisch - getrieben von idealistischen, aber unrealistischen Hoffnungen oder Zielen, oft praktische Zwänge ignorierend und zu edlem, aber ineffektivem Handeln führend.",
  "Neu kalibrieren - die Parameter eines Systems, einer Messung oder einer Strategie anzupassen oder neu zu konfigurieren, um Genauigkeit wiederherzustellen oder sich an veränderte Bedingungen anzupassen.",
  "Salient - auffallend auf eine Weise, die aufgrund von Hervorhebung, Relevanz oder Klarheit die Aufmerksamkeit auf sich zieht und somit das erste wahrgenommene oder erinnerte Merkmal ist.",
  "Transzendenz – der Akt, gewöhnliche Grenzen von Erfahrung, Gedanken oder Zuständen zu überschreiten, oft verbunden mit spirituellem, intellektuellem oder künstlerischem Aufstieg.",
  "Umbrage – ein Gefühl von Groll oder Verletztheit, ausgelöst durch eine implizite Kränkung oder Beleidigung, selbst wenn die Provokation subtil oder mehrdeutig ist.",
  "Wahrscheinlichkeit – das Erscheinungsbild von Wahrheit oder Realismus in Kunst, Argumentation oder Erzählung, wodurch etwas Fiktives oder Konstruiertes überzeugend authentisch wirkt.",
  "Launisch - gekennzeichnet durch spielerische Unvorhersehbarkeit oder phantasievolle Vorstellungskraft, manchmal charmant und manchmal unberechenbar oder unpraktisch in den Folgen.",
  "Fremdenfeindlichkeit – Angst oder Feindseligkeit gegenüber Ausländern oder wahrgenommenen Außenseitern, ausgedrückt durch Misstrauen, Ablehnung oder aggressives Verhalten auf sozialer oder politischer Ebene.",
  "Joch - zwei Einheiten physisch oder metaphorisch miteinander zu verbinden, auf eine Weise, die die Unabhängigkeit einschränkt oder eine Ausrichtung unter geteiltem Druck oder Autorität erzwingt.",
  "Zeitgeist – der prägende Geist oder das intellektuelle Klima einer Epoche, das sich in ihren dominanten Werten, Ängsten und kulturellen Ausdrucksformen widerspiegelt.",
  "Verbessern - etwas Schlechtes oder Unbefriedigendes besser oder erträglicher zu machen, nicht durch Beseitigung der Ursache, sondern durch Verringerung seiner negativen Auswirkungen.",
  "Kapitulieren – sich ergeben oder nach Widerstand nachgeben, normalerweise unter Druck oder Unvermeidlichkeit, wobei der Verlust der Handlungsfähigkeit oder der strategischen Position anerkannt wird.",
  "Debakel - ein plötzlicher und katastrophaler Misserfolg, der eine Struktur, einen Plan oder einen Ruf zum Einsturz bringt, Unordnung hinterlässt und zugrunde liegende Schwächen offenbart.",
  "Ennui – ein Gefühl tiefer Langeweile und Müdigkeit, das durch einen Mangel an Beschäftigung oder Anregung entsteht und oft von einem Gefühl der Sinnlosigkeit begleitet wird.",
  "Heimlich – sich auf geheime oder verstohlene Weise verhaltend, um Entdeckung oder Überprüfung zu vermeiden, mit der Implikation, dass die verborgene Handlung Bei Bekanntwerden Missbilligung hervorrufen würde.",
  "Grandios – imposant wirkend oder beabsichtigt, imposant, prächtig oder wichtiger zu erscheinen, als es realistisch ist, oft spiegelbildlich für übertriebene Ambitionen oder aufgeblasene Selbstwahrnehmung.",
  "Hegemonie – die Vorherrschaft eines Staates, einer Ideologie oder einer sozialen Gruppe über andere, die nicht nur durch Gewalt, sondern auch durch kulturellen Einfluss, Normen und die Zustimmung der Beherrschten aufrechterhalten wird.",
  "Ikonoklast - eine Person, die etablierte Überzeugungen, Traditionen oder verehrte Institutionen angreift oder ablehnt und somit das in Frage stellt, was andere für unantastbar oder heilig halten.",
  "Umsichtig - zeigt gesundes Urteilsvermögen, das auf Vernunft, Vorsicht und Weitblick basiert, anstatt auf Impulsivität, was sich oft in Entscheidungen unter Unsicherheit widerspiegelt.",
  "Kafkaesk – ähnlich den absurd unterdrückenden, unlogischen und alptraumhaften Situationen in Kafkas Werken, in denen Individuen in sinnloser Bürokratie gefangen sind.",
  "Lugubriös - übertrieben traurig oder düster im Verhalten, Ton oder in der Atmosphäre auf eine Weise, die schwer, theatralisch oder in die Länge gezogen wirkt.",
  "Monolithisch – groß, einheitlich und starr in Struktur oder Ideologie, widersteht Veränderungen und unterdrückt interne Vielfalt oder Meinungsverschiedenheiten.",
  "Nebulös – fehlend an klarer Form, Begrenzung oder Definition, sei es in Bezug auf physische Gestalten, argumentativen Aufbau oder unscharfe Ideen.",
  "Ontologie - der Zweig der Philosophie, der sich mit dem Wesen des Seins, Existenzkategorien und der grundlegenden Struktur der Realität beschäftigt.",
  "Perfunktoriös – mit minimalem Aufwand oder Überlegung ausgeführt, lediglich um eine Pflicht oder Erwartung zu erfüllen, und dabei ein Mangel an Engagement oder Aufrichtigkeit zeigend.",
  "Quintessenz – die reinste oder vollkommenste Verkörperung einer Eigenschaft oder Klasse, die als definierendes Beispiel dient, an dem andere gemessen werden.",
  "Auswirkung - eine Folge oder sekundäre Wirkung, die sich aus einer anfänglichen Handlung oder Entscheidung verzweigt und oft komplexe Ketten von Auswirkungen erzeugt.",
  "Scheinheilig – moralische Überlegenheit oder Rechtschaffenheit auf eine heuchlerische oder zur Schau gestellte Weise zur Schau stellen, die eher Irritation als Respekt hervorruft.",
  "Drehmoment – eine rotierende Kraft, die Verdrehung oder Drehung verursacht, die wörtlich in der Mechanik verwendet wird und metaphorisch für Kräfte steht, die Meinung oder Politik beeinflussen.",
  "Untertreiben - etwas so zu beschreiben oder darzustellen, dass es kleiner oder weniger ernst wirkt, als es tatsächlich ist, oft um die Wirkung abzuschwächen, die Erzählung zu kontrollieren oder Alarm zu vermeiden.",
  "Vanguard - die Vorhut einer Bewegung, Innovation oder Transformation, bestehend aus denen, die handeln oder Veränderungen herbeiführen, bevor andere folgen.",
  "Gewährleistung - eine Handlung oder einen Glauben durch die Bereitstellung angemessener Gründe, Legitimität oder Notwendigkeit zu rechtfertigen oder zu autorisieren, um ihn anzunehmen oder auszuführen.",
  "Xerisch - gekennzeichnet durch extrem trockene Bedingungen mit minimaler Feuchtigkeit, typischerweise verwendet für Lebensräume, Böden oder adaptive biologische Strategien.",
  "Nachgeben – sich einer Kraft, einem Argument oder einer Umständen fügen oder im Laufe der Zeit ein messbares Ergebnis als Reaktion auf einen Input erzeugen.",
  "Zenit - der höchste oder erfolgreichste Punkt, der von einer Person, einem Prozess oder einem Phänomen erreicht wird, bevor ein Rückgang oder eine Transformation beginnt.",
  "Mehrdeutig - offen für mehr als eine Interpretation aufgrund von Mehrdeutigkeit oder struktureller Doppelbedeutung, was Unsicherheit bei der Schlussfolgerung oder Reaktion erzeugt.",
  "Byzantinisch – hochgradig kompliziert, vielschichtig und schwer zu durchschauen aufgrund übermäßiger Details, Verfahren oder Verschleierung der Absicht.",
  "Rätsel - ein schwieriges Problem oder eine Frage ohne klare Lösung, oft erschwert durch widersprüchliche Einschränkungen oder fehlende Informationen.",
  "Didaktisch - dazu bestimmt, zu lehren oder Anweisungen zu vermitteln, manchmal mit einem Ton, der moralistisch, vorschreibend oder ästhetisch schwer wirkt.",
  "Extrapolieren - daraus schließen oder vorhersagen, was über bekannte Daten hinausgeht, indem beobachtete Muster erweitert werden, wobei mit zunehmender Entfernung auch die Unsicherheit steigt.",
  "Treue – Loyalität oder Treue zu einer Person, einem Standard oder einer Verpflichtung oder der Grad der Genauigkeit, mit dem etwas ein Original wiedergibt.",
  "Glazial - extrem langsam im Tempo oder Fortschritt oder kalt und distanziert im emotionalen Ton, was die Bewegung und Kälte von echtem Eis hervorruft.",
  "Hypothese - eine vorläufige erklärende Aussage, die durch Beobachtung, Experiment oder logische Deduktion getestet oder widerlegt werden kann.",
  "Trägheit – die Neigung eines Systems, einer Änderung seines Zustands oder seiner Bewegung zu widerstehen und in der bestehenden Bahn fortzufahren, es sei denn, es wird von einer äußeren Kraft beeinflusst.",
  "Gegenüberstellen - Elemente nebeneinander zu platzieren, sodass Kontraste oder Übereinstimmungen erst durch ihre Nähe wahrnehmbar werden.",
  "Urteilen - eine formelle Entscheidung oder ein Urteil über einen Streitfall oder Anspruch zu fällen, typischerweise innerhalb eines rechtlichen oder institutionellen Rahmens, der dem Entscheidungsträger Autorität verleiht.",
  "Antagonist - eine Person, Kraft oder Prinzip, die aktiv einem anderen Akteur oder Protagonisten entgegenwirkt oder Konflikte schafft und somit die Dynamik von Kampf oder Widerstand gestaltet.",
  "Kämpferisch – zeigt die Bereitschaft zu kämpfen oder sich an Konflikten zu beteiligen, sei es durch eine feindselige Haltung oder aktive Teilnahme an Kriegsführung oder aggressiven Auseinandersetzungen.",
  "Kakophonie – eine harte und dissonante Mischung von Klängen, die als unangenehm oder überwältigend empfunden wird, oft metaphorisch verwendet für chaotische oder nicht aufeinander abgestimmte Interaktionen.",
  "Kanonsieren - jemanden offiziell zum Heiligen zu erklären oder einen Text oder eine Figur innerhalb einer Tradition oder intellektuellen Linie als maßgeblich und unantastbar zu behandeln.",
  "Chiaroscuro – das Zusammenspiel von Licht und Schatten, das in der bildenden Kunst dramatische Kontraste erzeugt und Tiefe, Volumen sowie emotionale Intensität betont.",
  "Nötigung - die Handlung, jemanden durch Einsatz von Gewalt, Drohungen oder Druck zu zwingen, gegen seinen Willen zu handeln, wodurch die Bedingung der freien Zustimmung aufgehoben wird.",
  "Konvaleszieren - die allmähliche Wiederherstellung von Kraft und Gesundheit nach Krankheit oder medizinischem Eingriff durch Ruhe, Stabilisierung und kontrollierte Aktivität.",
  "Ehrerbietung – respektvolle Unterwerfung unter das Urteil, die Meinung oder die Autorität einer anderen Person, motiviert durch die Anerkennung von Status, Fachwissen oder Hierarchie.",
  "Dogma – ein Prinzip oder eine Reihe von Überzeugungen, die innerhalb eines Systems als autoritativ und unumstößlich dargestellt werden und ohne Toleranz gegenüber Herausforderungen oder Überarbeitungen aufrechterhalten werden.",
  "Emulieren - einem Vorbild oder Konkurrenten durch Nachahmung in Verbindung mit Verbesserung entsprechen oder es übertreffen, angetrieben von Ehrgeiz und nicht nur von bloßer Reproduktion.",
  "Epitaph - eine Inschrift oder ein kurzer Text, der zum Gedenken an eine verstorbene Person verfasst wird, typischerweise auf einem Grabstein eingraviert und die Identität oder das Vermächtnis zusammenfasst.",
  "Exegese - die kritische Interpretation eines Textes, insbesondere eines religiösen oder kanonischen, mit dem Ziel, durch begründete Analyse die beabsichtigte Bedeutung zu erschließen.",
  "Falsifizierbar – die Fähigkeit, durch Beobachtung oder Experiment widerlegt zu werden, wodurch eine Behauptung als wissenschaftlich überprüfbar und nicht nur als bloße Aussage gekennzeichnet wird.",
  "Gravitas – eine ernste und gewichtige Art, die intellektuelle Tiefe, soziale Autorität oder moralische Bedeutung in Rede, Haltung oder Entscheidung vermittelt.",
  "Unglücklich - anhaltendes Unglück oder Misserfolg erlebend, trotz des Fehlens von Absicht oder Schuld, wodurch die Umstände anstelle der Kompetenz in den Vordergrund gerückt werden.",
  "Ketzerei – ein Glaube oder eine Behauptung, die von der etablierten Doktrin innerhalb einer Tradition abweicht und als Bedrohung für die Orthodoxie oder die institutionelle Kohärenz wahrgenommen wird.",
  "Homogen – zusammengesetzt aus Teilen oder Mitgliedern, die in ihrer Natur oder ihren Eigenschaften ähnlich sind, wodurch die interne Variation reduziert und ein einheitliches Verhalten erzeugt wird.",
  "Unaussprechlich - zu groß, intensiv oder subtil, um angemessen in Worten ausgedrückt zu werden, und steht jenseits der Grenzen sprachlicher Darstellung.",
  "Inveigh – mit großer Feindseligkeit oder Entrüstung gegen etwas, das als falsch empfunden wird, zu sprechen oder zu schreiben, indem man kraftvolle Anschuldigungen oder Verurteilungen verwendet.",
  "Jurisprudenz – die Theorie oder Philosophie des Rechts, die die Prinzipien, Quellen und die Logik untersucht, welche den Rechtssystemen und der Rechtsbegründung zugrunde liegen.",
  "Linearize - ein Phänomen zu vereinfachen, indem sein Verhalten als linear angenähert wird, wodurch die Komplexität für die Analyse reduziert wird, jedoch auf Kosten der nuancierten Genauigkeit.",
  "Litotes - ein rhetorisches Stilmittel, bei dem eine bejahende Aussage durch die Verneinung ihres Gegenteils zum Ausdruck gebracht wird, wodurch eine Untertreibung als Betonungsform entsteht.",
  "Makaber - eine düstere oder verstörende Eigenschaft, die mit Tod, Verfall oder grotesken Bildern verbunden ist und eine Faszination hervorruft, die mit Unbehagen verknüpft ist.",
  "Mnemonisch - eine Methode oder ein Hilfsmittel, das dazu verwendet wird, das Behalten von Informationen zu unterstützen, indem Informationen mit Mustern verbunden werden, die leichter zu erinnern sind als die rohen Daten selbst.",
  "Normativ – beschäftigt mit der Festlegung von Maßstäben dessen, was sein sollte, anstatt zu beschreiben, was ist, und schreibt Ideale vor, anstatt Fakten zu erfassen.",
  "Ontogenie – die Entwicklung eines einzelnen Organismus von seinem frühesten Stadium bis zur Reife, wobei strukturelle und funktionelle Veränderungen im Laufe der Zeit verfolgt werden.",
  "Pathos – eine Eigenschaft in der Kommunikation, die Mitleid, Trauer oder tiefe Emotionen beim Publikum hervorruft, indem sie auf Verwundbarkeit und gemeinsame menschliche Schwäche appelliert.",
  "Mehrjährig – dauerhaft oder wiederholt über einen langen Zeitraum ohne wesentlichen Rückgang, sei es in Bezug auf Pflanzen, Debatten oder strukturelle Probleme.",
  "Beweisführend – die Eigenschaft, etwas zu beweisen oder zu demonstrieren, insbesondere Beweismaterial, das relevant und ausreichend ist, um eine rechtliche oder rationale Schlussfolgerung zu beeinflussen."
];
