export default [
  "Palimpseste - un manuscrit ou document dont l'écriture originale a été effacée et réécrite, mais des traces du texte antérieur subsistent et permettent la reconstruction des couches de sens sous-jacentes.",
  "Omniprésent - existant ou rencontré partout à la fois, au point que sa présence devient supposée plutôt que remarquée, comme avec la connectivité numérique ou le bruit de fond dans les villes.",
  "Flatteur - une personne qui flatte ceux qui détiennent le pouvoir pour obtenir des faveurs ou des avantages, souvent au détriment de la sincérité ou de l'intégrité, créant ainsi un environnement social déformé autour de l'autorité.",
  "L'entropie - une mesure du désordre ou de l'aléa dans un système, utilisée pour décrire la tendance naturelle des systèmes à passer d'états ordonnés à des configurations plus probables et moins organisées.",
  "Anhédonie - la diminution de la capacité à éprouver du plaisir lors d'activités normalement considérées comme agréables, souvent associée à des états dépressifs ou à un dysfonctionnement neurologique.",
  "Obscurcir - rendre délibérément quelque chose flou, confus ou difficile à comprendre, en particulier pour empêcher les critiques ou éviter la responsabilité dans la communication ou la prise de décision.",
  "Cynosure - quelque chose ou quelqu'un qui devient le centre d'attention ou d'admiration, non seulement visible mais captivant, attirant les regards et les intentions des autres vers lui.",
  "Éphémère - qui dure très peu de temps avant de s’effacer ou de disparaître rapidement, généralement utilisé pour décrire des états, des expériences ou des phénomènes qui ne peuvent être entièrement capturés ou conservés.",
  "Maelström - un tourbillon puissant et violent capable d'attirer des objets en son centre, utilisé métaphoriquement pour désigner des situations chaotiques détruisant la structure ou la stabilité.",
  "L'apathie - un état d'indifférence émotionnelle où des stimuli qui provoqueraient habituellement de l'intérêt ou de l'inquiétude ne suscitent chez l'individu aucune motivation, aucun engagement ni aucune réaction.",
  "Irisé - montrant des couleurs lumineuses qui semblent se déplacer ou changer lorsqu'on les observe sous différents angles, comme on peut le voir dans les bulles de savon, les plumes d'oiseaux ou certaines surfaces minérales.",
  "Pétrichor - l'arôme distinctif et agréable de terre humide qui s'élève du sol sec lorsque la pluie commence à tomber, causé par des huiles libérées par les plantes et des composés formés par les microbes.",
  "Obsolète - qui n'est plus en usage général ni pertinent car il a été remplacé par quelque chose de plus récent ou plus efficace, bien qu'il puisse persister dans des archives ou des systèmes hérités.",
  "Métamorphose - un changement profond de forme, de structure ou de caractère, observé biologiquement chez les insectes et métaphoriquement dans les processus de transformation personnelle ou sociale.",
  "Baromètre - un instrument qui mesure la pression atmosphérique, utilisé pour prévoir les changements météorologiques à court terme et métaphoriquement pour évaluer les variations d'opinion ou de conditions.",
  "Parcimonie - une réticence extrême à dépenser des ressources, qu'il s'agisse d'argent, d'efforts ou de mots, produisant souvent des résultats minimaux mais fonctionnels au détriment de la générosité ou de la richesse.",
  "Mercurial - caractérisé par des changements rapides et imprévisibles d'humeur ou de comportement, rappelant la nature changeante du mercure, ce qui rend difficile toute anticipation ou confiance.",
  "Vindicatif - ayant ou montrant un désir de chercher à se venger, ne se contentant pas de se souvenir d'un tort mais visant activement à punir ou infliger un dommage en retour.",
  "Laconique - exprimer des idées en utilisant très peu de mots, ce qui donne un discours concis à l'extrême, souvent interprété comme sûr de soi, froid ou méprisant.",
  "Vicissitude - un changement de circonstances ou de fortune, en particulier un changement indésirable ou indépendant de la volonté de quelqu'un, mettant en avant l'instabilité comme une caractéristique naturelle de la vie.",
  "Zélote - une personne qui montre un dévouement extrême et intransigeant envers une croyance ou une cause, rejetant souvent la modération et ignorant les perspectives opposées ou les conséquences.",
  "Erudit - possédant ou montrant une connaissance approfondie acquise par la lecture et l'étude, non seulement informé mais profondément instruit d'une manière qui façonne l'expression et l'analyse.",
  "Dogmatique - enclin à présenter des opinions comme des vérités incontestables, résistant aux remises en question ou aux points de vue alternatifs, diminuant la libre enquête dans le discours ou les institutions.",
  "Passager - ne durant qu'une courte période avant de disparaître, en particulier pour des états ou des populations qui existent brièvement et laissent une trace limitée une fois que les conditions changent.",
  "Révoquer - annuler, abroger ou inverser une décision, une loi ou un accord, en restaurant l'état antérieur ou en annulant les obligations précédemment en vigueur.",
  "Mélancolie - une forme profonde et persistante de tristesse non liée à des causes immédiates, historiquement décrite comme un tempérament et aujourd'hui associée à un affect dépressif.",
  "Synecdoque - une figure de style dans laquelle une partie représente le tout ou le tout représente une partie, modifiant la perspective en changeant l'échelle de représentation.",
  "Panacée - un remède hypothétique universel capable de traiter toutes les maladies ou problèmes, souvent invoqué de manière rhétorique pour critiquer des solutions naïves ou simplistes.",
  "Immutable - incapable d'être modifié ou altéré au fil du temps, que ce soit intentionnellement ou par la force, souvent utilisé pour décrire des principes, des vérités mathématiques ou des états de code.",
  "Équanimité - un état de calme psychologique et de stabilité face au stress ou au conflit, où les réactions émotionnelles restent mesurées plutôt que volatiles ou extrêmes.",
  "Ambivalence - un état dans lequel une personne éprouve simultanément deux sentiments ou croyances opposés, créant ainsi de l'hésitation et des difficultés à prendre des décisions ou à s'engager dans une seule voie.",
  "Conflate - fusionner deux idées, questions ou informations ou plus en une seule de manière à obscurcir leurs distinctions et pouvant induire en erreur l'interprétation ou l'analyse.",
  "Dénouement - la phase finale d'un récit dans laquelle les intrigues complexes sont résolues et les tensions relâchées, révélant les conséquences qui suivent le climax.",
  "Équivoquer - parler de manière intentionnellement vague ou ambiguë afin d'éviter de prendre une position claire ou de tromper sans raconter un mensonge direct.",
  "Pointilleux - montrant une extrême attention aux détails et à la précision, souvent combinée à une forte préférence pour l'ordre ou la propreté et une faible tolérance à l'erreur.",
  "Gregoriate - réorganiser ou remodeler une structure de pensée, de politique ou de comportement conformément à un nouveau principe dominant, remplaçant souvent ce qui était auparavant ancré.",
  "Heuristique - une méthode pratique pour résoudre des problèmes ou prendre des décisions en utilisant des stratégies basées sur l'expérience plutôt que sur une logique exhaustive ou une précision garantie.",
  "Impréhensible - impossible à interpréter ou à comprendre en raison de l'opacité du motif, de l'expression ou de la structure, laissant les observateurs incertains quant à la signification sous-jacente.",
  "Juxtaposition - le placement de deux éléments côte à côte afin de mettre en évidence un contraste, une similitude ou une tension qui n’émerge que par leur proximité.",
  "Kaléidoscopique - changeant rapidement de motif ou d'apparence de manière à créer une sensation de recomposition continue, comme les miroirs changeants dans un kaléidoscope.",
  "Liminal - relatif à une frontière ou un seuil entre deux états, phases ou identités, où la transformation, l'ambiguïté ou l'instabilité sont naturellement concentrées.",
  "Manifeste - une déclaration écrite formelle annonçant les principes, les intentions ou les revendications d'un mouvement ou d'un individu, destinée à influencer l'opinion ou à initier un changement.",
  "Le nihilisme - la croyance que la vie est dépourvue de sens, de but ou de valeur inhérents, souvent accompagnée d'un scepticisme envers les revendications morales, religieuses ou politiques de vérité.",
  "Obséquieux - manifestant une volonté exagérée et excessive de servir ou d'obéir, en particulier envers ceux qui détiennent le pouvoir, souvent perçu comme humiliant ou manipulateur.",
  "Paradoxe - une déclaration ou une situation qui semble auto-contradictoire ou absurde mais qui peut contenir une vérité sous-jacente lorsqu'on l'examine sous un angle plus profond.",
  "Quichottesque - motivé par des espoirs ou des objectifs idéalistes mais irréalistes, souvent en ignorant les contraintes pratiques et conduisant à une action noble mais inefficace.",
  "Recalibrer - ajuster ou reconfigurer les paramètres d'un système, d'une mesure ou d'une stratégie afin de restaurer la précision ou de s'adapter aux conditions modifiées.",
  "Saillant - se démarquant d'une manière qui attire l'attention en raison de sa proéminence, sa pertinence ou sa clarté, en faisant la première caractéristique perçue ou rappelée.",
  "Transcendance - l'acte de dépasser les limites ordinaires de l'expérience, de la pensée ou de la condition, souvent associé à une élévation spirituelle, intellectuelle ou artistique.",
  "Umbrage - un sentiment de rancune ou d'offense provoqué par un léger affront ou une insulte implicite, même lorsque la provocation est subtile ou ambiguë.",
  "Vraisemblance - l'apparence de vérité ou de réalisme dans l'art, l'argumentation ou le récit, faisant en sorte qu'un élément fictif ou construit paraisse de manière convaincante authentique.",
  "Capricieux - caractérisé par une imprévisibilité ludique ou une imagination fantasque, parfois charmante et parfois erratique ou peu pratique en conséquence.",
  "Xénophobie - peur ou hostilité envers les étrangers ou les personnes perçues comme étrangères, exprimée par la méfiance, le rejet ou un comportement agressif aux niveaux social ou politique.",
  "Yoke - attacher deux entités ensemble, physiquement ou métaphoriquement, d'une manière qui restreint l'indépendance ou impose une alignement sous un fardeau ou une autorité partagée.",
  "Zeitgeist - l'esprit dominant ou le climat intellectuel d'une époque, reflété dans ses valeurs, ses angoisses et ses expressions culturelles prédominantes.",
  "Améliorer - rendre quelque chose de mauvais ou d'insatisfaisant meilleur ou plus tolérable, non pas en éliminant la cause, mais en réduisant son impact négatif.",
  "Capituler - se rendre ou céder après une résistance, généralement sous la pression ou l'inévitabilité, en reconnaissant la perte d'autonomie ou de position stratégique.",
  "Débâcle - un échec soudain et désastreux qui fait s'effondrer une structure, un plan ou une réputation, laissant le désordre et exposant des faiblesses sous-jacentes.",
  "L'ennui - un sentiment de profonde lassitude et d'ennui résultant d'un manque d'occupation ou de stimulation, souvent accompagné d'un sentiment d'absurdité.",
  "Furtif - se comporter de manière secrète ou furtive pour éviter d'être découvert ou examiné, impliquant que l'action dissimulée provoquerait la désapprobation si elle était révélée.",
  "Grandiose - qui paraît ou est destiné à paraître impressionnant, magnifique ou plus important qu'il ne l'est en réalité, reflétant souvent une ambition exagérée ou une perception de soi surdimensionnée.",
  "Hégémonie - la domination d'un État, d'une idéologie ou d'un groupe social sur les autres, maintenue non seulement par la force mais aussi par l'influence culturelle, les normes et le consentement des gouvernés.",
  "Iconoclaste - une personne qui attaque ou rejette les croyances établies, les traditions ou les institutions vénérées, remettant en cause ce que les autres considèrent comme intouchable ou sacré.",
  "Judicieux - faisant preuve d'un jugement sain basé sur la raison, la prudence et la prévoyance plutôt que sur l'impulsivité, souvent visible dans les décisions prises en situation d'incertitude.",
  "Kafkaïen - ressemblant aux situations absurde, oppressantes, illogiques et cauchemardesques que l'on trouve dans les œuvres de Kafka, où les individus sont piégés dans une bureaucratie insensée.",
  "Lugubre - excessivement mélancolique ou sombre dans la manière, le ton ou l'atmosphère, de manière à sembler lourde, théâtrale ou prolongée.",
  "Monolithique - grand, uniforme et rigide dans sa structure ou son idéologie, résistant à la modification et supprimant la diversité ou la dissidence internes.",
  "Nébuleux - manquant de forme claire, de limites ou de définition, que ce soit en référence à des formes physiques, des structures d'arguments ou des idées floues.",
  "Ontologie - la branche de la philosophie qui s'intéresse à la nature de l'être, aux catégories de l'existence et à la structure fondamentale de la réalité.",
  "Superficiel - réalisé avec un effort ou une réflexion minimal uniquement pour remplir un devoir ou une attente, témoignant d'une absence d'implication ou de sincérité.",
  "Quintessence - l'incarnation la plus pure ou la plus parfaite d'une qualité ou d'une catégorie, servant d'exemple définitif contre lequel les autres sont mesurés.",
  "Conséquence - une répercussion ou un effet secondaire qui découle d'une action ou décision initiale, créant souvent des chaînes d'impact complexes.",
  "Sanctimonieux - affichant une supériorité morale ou une rectitude de manière hypocrite ou performative qui suscite l'irritation plutôt que le respect.",
  "Couple - une force de rotation qui provoque un torsion ou un mouvement de rotation, utilisée littéralement en mécanique et métaphoriquement pour des forces qui font pivoter une opinion ou une politique.",
  "Minimiser - décrire ou présenter quelque chose comme étant plus petit ou moins grave qu'il ne l'est en réalité, souvent pour atténuer l'impact, contrôler le récit ou éviter l'alarme.",
  "Avant-garde - l'avant-garde d'un mouvement, d'une innovation ou d'une transformation, composée de ceux qui agissent ou changent avant que les autres ne suivent.",
  "Garantie - justifier ou autoriser une action ou une croyance en fournissant des raisons adéquates, une légitimité ou une nécessité pour l'accepter ou la réaliser.",
  "Xérique - caractérisé par des conditions extrêmement sèches avec une humidité minimale, généralement utilisé pour désigner des habitats, des sols ou des stratégies biologiques adaptatives.",
  "Céder - se soumettre ou céder à une force, un argument ou une circonstance, ou produire un résultat mesurable en réponse à une entrée au fil du temps.",
  "Zénith - le point le plus haut ou le plus réussi atteint par une personne, un processus ou un phénomène avant que le déclin ou la transformation ne commence.",
  "Ambigu - susceptible de plusieurs interprétations en raison d'une certaine imprécision ou d'une dualité structurelle, générant une incertitude dans l'inférence ou la réponse.",
  "Byzantin - hautement compliqué, stratifié et difficile à naviguer en raison d'un excès de détails, de procédures ou de dissimulation d'intentions.",
  "Conundrum - un problème ou une question difficile sans solution évidente, souvent compliquée par des contraintes contradictoires ou des informations manquantes.",
  "Didactique - destiné à enseigner ou à transmettre des instructions, parfois avec un ton qui peut sembler moralisateur, prescriptif ou esthétiquement lourd.",
  "Extrapoler - inférer ou prédire au-delà des données connues en prolongeant les motifs observés, en acceptant une incertitude accrue à mesure que la distance augmente.",
  "Fidélité - loyauté ou fidélité envers une personne, une norme ou une obligation, ou le degré de précision avec lequel quelque chose reproduit un original.",
  "Glacial - extrêmement lent dans son rythme ou sa progression, ou froid et distant dans le ton émotionnel, évoquant le mouvement et la froideur de la glace littérale.",
  "Hypothèse - une proposition explicative provisoire qui peut être testée ou réfutée par l'observation, l'expérience ou la déduction logique.",
  "L'inertie - la tendance d'un système à résister au changement de son état ou de son mouvement, persistant dans sa trajectoire existante à moins d'être soumis à une force externe.",
  "Juxtaposer - placer des éléments côte à côte de manière à ce que le contraste ou la correspondance ne devienne perceptible qu'à travers leur voisinage.",
  "Adjuger - rendre un jugement ou une décision formelle concernant un litige ou une réclamation, généralement dans un cadre juridique ou institutionnel qui confère une autorité au décideur.",
  "Antagoniste - une personne, une force ou un principe qui s'oppose activement ou crée un conflit pour un autre agent ou protagoniste, façonnant la dynamique de la lutte ou de la résistance.",
  "Belliqueux - montrant une disposition à se battre ou à s'engager dans un conflit, soit par une attitude hostile, soit par une participation active à la guerre ou à une confrontation agressive.",
  "Cacophonie - un mélange âpre et discordant de sons perçus comme désagréables ou accablants, souvent utilisé métaphoriquement pour des interactions chaotiques ou mal alignées.",
  "Canoniser - déclarer officiellement quelqu'un saint ou traiter un texte ou une figure comme faisant autorité et au-delà de la critique au sein d'une tradition ou d'une lignée intellectuelle.",
  "Clair-obscur - l'interaction de la lumière et de l'ombre qui produit un contraste dramatique dans l'art visuel, mettant en valeur la profondeur, le volume et l'intensité émotionnelle.",
  "La coercition - l'acte de contraindre quelqu'un à agir contre sa volonté par l'utilisation de la force, de menaces ou de pressions qui éliminent la condition du consentement libre.",
  "Convalescence - se rétablir progressivement en force et en santé après une maladie ou une intervention médicale grâce au repos, à la stabilisation et à une activité contrôlée.",
  "Déférence - soumission respectueuse au jugement, à l'opinion ou à l'autorité d'une autre personne, motivée par la reconnaissance du statut, de l'expertise ou de la hiérarchie.",
  "Dogme - un principe ou un ensemble de croyances présentés comme faisant autorité et incontestables au sein d'un système, défendus sans tolérance pour la remise en question ou la révision.",
  "Émuler - égaler ou surpasser un modèle ou un concurrent par l'imitation combinée à l'amélioration, motivée par l'ambition plutôt que par la simple reproduction.",
  "Épitaphe - une inscription ou un texte bref écrit en mémoire d'une personne décédée, généralement gravé sur une pierre tombale et résumant son identité ou son héritage.",
  "Exégèse - l'interprétation critique d'un texte, en particulier d'un texte à statut religieux ou canonique, visant à extraire le sens voulu par une analyse raisonnée.",
  "Falsifiable - capable d'être réfuté par l'observation ou l'expérimentation, ce qui rend une affirmation testable scientifiquement plutôt que simplement énoncée.",
  "Gravitas - une manière sérieuse et solennelle qui transmet une profondeur intellectuelle, une autorité sociale ou une importance morale dans le discours, la posture ou la décision.",
  "Malchanceux - subissant une malchance ou un échec persistant malgré l'absence d'intention ou de faute, mettant en lumière les circonstances plutôt que la compétence.",
  "Hérésie - une croyance ou une affirmation qui s'écarte de la doctrine établie au sein d'une tradition, perçue comme une menace pour l'orthodoxie ou la cohérence institutionnelle.",
  "Homogène - composé de parties ou de membres similaires par leur nature ou leurs caractéristiques, ce qui réduit la variation interne et produit un comportement uniforme.",
  "Ineffable - trop grand, intense ou subtil pour être adéquatement exprimé en mots, dépassant les limites de la représentation linguistique.",
  "Inveigh - parler ou écrire avec une grande hostilité ou indignation contre quelque chose perçu comme injuste, en utilisant une accusation ou une dénonciation vigoureuse.",
  "La jurisprudence - la théorie ou philosophie du droit qui examine les principes, les sources et la logique sous-jacents aux systèmes juridiques et au raisonnement juridique.",
  "Linéariser - simplifier un phénomène en approximant son comportement comme linéaire, réduisant la complexité pour l’analyse tout en sacrifiant une précision nuancée.",
  "La litote est une figure de style dans laquelle une idée affirmative est exprimée en niant son contraire, produisant une atténuation comme mode d'accentuation.",
  "Macabre - ayant une qualité sombre ou troublante liée à la mort, à la décomposition ou à des images grotesques, provoquant une fascination mêlée à un malaise.",
  "Mnémonique - une méthode ou un dispositif utilisé pour aider à la rétention de la mémoire en associant des informations à des motifs plus faciles à rappeler que les données brutes elles-mêmes.",
  "Normatif - concerné par l'établissement de normes de ce qui devrait être plutôt que par la description de ce qui est, prescrivant des idéaux plutôt qu'enregistrant des faits.",
  "Ontogenèse - le développement d'un organisme individuel depuis ses premiers stades jusqu'à la maturité, retraçant les transformations structurelles et fonctionnelles au fil du temps.",
  "Le pathos - une qualité dans la communication qui évoque la pitié, la tristesse ou une émotion profonde chez un public en faisant appel à la vulnérabilité et à la fragilité humaine partagée.",
  "Pérenne - qui dure ou se répète de manière continue sur une longue période sans déclin significatif, que ce soit en référence aux plantes, aux débats ou aux problèmes structurels.",
  "Probant - ayant la qualité de prouver ou de démontrer quelque chose, en particulier une preuve pertinente et suffisante pour influencer une conclusion juridique ou rationnelle."
];
