export default {
  "Sprichwort": "Kurzer, einprägsamer Satz mit allgemeiner Lebensweisheit.",
  "Henry Kissinger": "US-amerikanischer Politiker und Diplomat, Friedensnobelpreisträger",
  "Deutsches Sprichwort": "Kurzer, prägnanter Satz mit allgemeiner Lebensweisheit.",
  "Joanne K. Rowling": "Britische Autorin, bekannt für die Harry-Potter-Buchreihe",
  "Novalis": "Deutscher Dichter und Philosoph der Romantik",
  "Katechismus des Ingenieurs": "Lehrbuch für technische Grundlagen und ethische Prinzipien der Ingenie",
  "Erich Fried": "österreichischer Dichter und Übersetzer",
  "Beatrix Nutz": "Österreichische Historikerin und Archäologin",
  "Transformers": "Beliebte Sci-Fi-Filmreihe über gestaltwandelnde Roboter",
  "Hans-Joachim Kulenkampff": "Deutscher Fernsehmoderator und Entertainer",
  "Karl Lagerfeld": "Berühmter Modedesigner und Kreativdirektor, bekannt für Chanel.",
  "unbekannt": "",
  "Art van Rheyn": "Künstler und Illustrator bekannt für fantasy-inspirierte Werke.",
  "Ernst Zacharias": "Deutscher Komponist und Musiker, bekannt für Instrumentalstücke.",
  "Theodor W. Adorno": "Deutscher Philosoph und Soziologe, Mitbegründer der Frankfurter Schule",
  "Colette": "Französische Schriftstellerin, bekannt für Romane und Essays.",
  "Michel de Mantaigne": "Französischer Philosoph und Schriftsteller der Renaissance",
  "Napoleon": "Französischer Militärführer und Kaiser, bekannt für seine Eroberungen.",
  "Christian Friedrich Hebbel": "Deutscher Dramatiker und Lyriker des 19. Jahrhunderts",
  "Der längste Tag": "Film über die Ereignisse am Tag der alliierten Invasion in der Normand",
  "Wikipedia": "Kostenlose Online-Enzyklopädie mit nutzergenerierten Inhalten",
  "Carl Ludwig Schleich": "Deutscher Arzt und Erfinder der Lokalanästhesie-Techniken.",
  "Alvin Toffler": "US-amerikanischer Autor und Futurist, bekannt für Zukunftsstudien",
  "Salvador Dali": "Spanischer surrealistischer Maler und Bildhauer",
  "Two and a Half Men": "US-Sitcom über zwei Brüder und den Sohn eines von ihnen",
  "David Ben Gurion": "Gründervater Israels und erster Ministerpräsident",
  "Unbekannt": "",
  "Jean Paul": "Deutscher Schriftsteller, bekannt für humoristische Romane.",
  "Gabriel Laub": "Journalist und Satiriker mit Fokus auf Politik und Gesellschaft.",
  "Wolfram Siebeck": "Deutscher Journalist und Feinschmecker, bekannt für seine Gastronomiek",
  "3 Engel für Charlie": "Actionserie über drei Detektivinnen, die für Charlie arbeiten.",
  "Fred Allen": "Amerikanischer Komiker und Radio-Moderator",
  "Chinesisches Sprichwort": "Traditionelles chinesisches Weisheitswort oder Redensart",
  "Christian Morgenstern": "Deutscher Dichter, bekannt für humorvolle und skurrile Gedichte",
  "Francis Bacon": "Englischer Maler, bekannt für expressionistische Figuren und Porträts.",
  "Edgar Allan Poe": "US-amerikanischer Schriftsteller, bekannt für mysteriöse Kurzgeschicht",
  "aus dem Pommernlied": "Traditionelles deutsches Volkslied aus Pommern.",
  "Woody Allen": "US-amerikanischer Regisseur, Autor und Schauspieler",
  "Lothar Matthäus": "Deutscher Fußballspieler und Trainer, bekannt für viele Einsätze in de",
  "Data": "Künstliche Intelligenz und Android aus Star Trek: The Next Generation",
  "David Russel": "Britischer klassischer Gitarrist und Musiker",
  "Christian Friedrich Daniel Schubart": "Deutscher Dichter, Musiker und Publizist des 18. Jahrhunderts",
  "Emanuel Geibel": "Deutscher Lyriker und Dramatiker des 19. Jahrhunderts.",
  "Gottfried Keller": "Schweizer Schriftsteller, bekannt für realistische Romane und Novellen",
  "William Shakespeare": "Englischer Dramatiker und Dichter, bekannt für klassische Werke.",
  "Possessed": "US-amerikanischer Horrorfilm über Dämonenbesessenheit.",
  "Heinrich Heine": "Deutscher Dichter und Schriftsteller, bekannt für Lyrik und Prosa.",
  "von Friedrich von Schiller": "Deutscher Dichter, Dramatiker und Philosoph der Aufklärung",
  "Bloodsport": "Actionfilm über einen illegalen Kampfsportwettbewerb.",
  "John Carrick": "Schottischer Schriftsteller und Dramatiker.",
  "Winston Churchill": "Britischer Politiker und Premierminister im Zweiten Weltkrieg",
  "Mark Twain": "US-amerikanischer Schriftsteller, bekannt für humorvolle Literatur",
  "Sigmund Freud": "Begründer der Psychoanalyse und Pionier der Psychotherapie",
  "Obi-Wan Kenobi": "Jedi-Meister aus dem Star-Wars-Universum",
  "aus der Ukraine": "Bezieht sich auf originär aus der Ukraine stammend",
  "aus Gabun": "Land in Zentralafrika mit vielfältiger Tierwelt und Regenwald",
  "Konfuzius": "Chinesischer Philosoph und Begründer des Konfuzianismus.",
  "Twister": "US-Film über Sturmjäger und Tornadoforschung",
  "Josephine Baker": "Amerikanisch-französische Tänzerin, Sängerin und Bürgerrechtlerin",
  "Peter Sirius": "",
  "Matth. 26,41": "Bibellstelle im Matthäusevangelium über Wachsamkeit im Gebet",
  "Al Capone": "Berüchtigter US-amerikanischer Gangster und Verbrecherboss",
  "Pindar": "Griechischer Dichter, bekannt für seine Siegessäle und Oden.",
  "Georg Christoph Lichtenberg": "Deutscher Physiker und Schriftsteller, bekannt für Aphorismen.",
  "Hans Krailsheimer": "Literaturwissenschaftler und Übersetzer aus Deutschland",
  "Phil Bosmans": "Belgischer Priester und Autor, bekannt für lebensbejahende Botschaften",
  "A-Team (Film)": "Actionfilm über eine Elite-Söldnergruppe, die Unschuldige verteidigt.",
  "Wolfgang Herbs": "Deutscher Schauspieler und Synchronsprecher.",
  "Chamfort": "Französischer Schriftsteller und Philosoph, bekannt für Aphorismen.",
  "Heinrich Böll": "Deutscher Schriftsteller, bekannt für gesellschaftskritische Romane",
  "John Keats": "Englischer Romantik-Dichter bekannt für gefühlvolle und sinnliche Werk",
  "Janusz Oseka": "Polnischer Schriftsteller",
  "Franz Kafka": "Deutschsprachiger Schriftsteller, bekannt für surreale Erzählungen.",
  "Die 3 Musketiere": "Ein Roman über Abenteuer und Freundschaft im Frankreich des 17. Jahrhu",
  "Henry David Thoreau": "Amerikanischer Schriftsteller und Philosoph, bekannt für 'Walden'",
  "Martin Luther": "Deutscher Theologe, Begründer der protestantischen Reformation.",
  "Werner Mitsch": "Deutscher Politiker und Mitglied des Bundestags",
  "John Knittel": "Schweizer Schriftsteller bekannt für Romane und Reiseliteratur.",
  "J. L. Burkhardt": "Schweizer Schriftsteller und Übersetzer, bekannt für Reiseberichte.",
  "Daniel Mühlemann": "Schweizer Unternehmer und Kommunikationsberater",
  "Holländisches Sprichwort": "Traditioneller deutscher Ausdruck mit praktischer Lebensweisheit",
  "Andre Gide": "Französischer Schriftsteller und Nobelpreisträger",
  "Willi Walgenbach": "Deutscher Politiker und Gewerkschafter",
  "Bauernweisheit": "Traditionelle Sprichwörter und Lehren der Landwirte",
  "Heinrich Laube": "Deutscher Schriftsteller und Theaterregisseur des 19. Jahrhunderts",
  "Alan Key": "Symbolischer Programmierwerkzeug zum Einrasten von Elementen",
  "Immanuel Kant": "Deutscher Philosoph, bekannt für seine Werke zur Erkenntnistheorie und",
  "Robert Musil": "Österreichischer Schriftsteller, bekannt für \"Der Mann ohne Eigenschaf",
  "Siegfried Wache": "Deutscher Schauspieler und Synchronsprecher.",
  "Linus Pauling": "Doppel-Nobelpreisträger und bedeutender Chemiker und Friedensaktivist",
  "Werner Heisenberg": "Deutscher Physiker, Begründer der Quantenmechanik und Unschärferelatio",
  "Der Kindergarten-Daddy": "Deutscher Film über einen Mann, der im Kindergarten arbeitet.",
  "Otto von Bismarck": "Preußischer Staatsmann und erster Reichskanzler des Deutschen Reichs",
  "Jürgen Polz": "Deutscher Biologe spezialisiert auf Mikrobiologie und Genetik",
  "Französisches Sprichwort": "Traditionelles Sprichwort aus Frankreich",
  "Oliver Hassencamp": "Deutscher Autor, Schauspieler und Musiker",
  "Marie Freifrau von Ebner-Eschenbach": "Österreichische Schriftstellerin, bekannt für psychologische Romane.",
  "Albert Gobat": "Schweizer Friedensnobelpreisträger und Politiker",
  "Henri Cartier-Bresson": "Französischer Fotograf, Pionier der Straßenfotografie und des Fotojour",
  "Alexandre Dumas": "Französischer Schriftsteller, bekannt für Abenteuerromane wie ‚Die dre",
  "Martin Gerhard Reisenberg": "Deutscher Chemiker, bekannt für Studien zur organischen Chemie.",
  "Theodor Heuss": "Erster Bundespräsident der Bundesrepublik Deutschland.",
  "Henry Ford": "US-amerikanischer Industrieller und Gründer der Ford Motor Company",
  "Paul Adolph Volker": "Deutscher Kirchenhistoriker und Theologe",
  "Hackers": "Film über junge Computergenies und Cyberkriminalität.",
  "Jacques Prévert": "Französischer Dichter und Drehbuchautor, bekannt für Lyrik und Filme",
  "Gerhard Uhlenbruck": "Deutscher Ingenieur und Forscher im Bereich Fahrzeugtechnik",
  "J.-P. Sartre": "Französischer Philosoph, Schriftsteller und Existenzialist",
  "Reiner Klüting": "Deutscher Schriftsteller und Autor von Theaterstücken.",
  "Franz von Assisi": "Italienischer Heiliger und Gründer des Franziskanerordens",
  "Edmund Burke": "Britischer Philosoph und Politiker, Begründer des Konservatismus",
  "Hermann Hesse": "Deutscher Schriftsteller, bekannt für Werke wie 'Siddhartha' und 'Der ",
  "Benjamin Franklin": "Amerikanischer Staatsmann, Erfinder und Gründervater der USA",
  "Wilhelm Busch": "Deutscher Dichter und Zeichner, bekannt für humorvolle Bildergeschicht",
  "Peter Bamm": "Deutscher Arzt und Schriftsteller, bekannt für Reiseberichte.",
  "Wieslaw Brudzinski": "",
  "Marie von Ebner-Eschenbach": "Österreichische Schriftstellerin, bekannt für psychologische Romane",
  "Theodor Fontane": "Deutscher Schriftsteller, bekannt für seine realistischen Romane.",
  "Francesco Petrarca": "Italienischer Dichter und Humanist, bekannt als Vater des Humanismus",
  "Thomas Jefferson": "Dritter Präsident der USA und Hauptautor der Unabhängigkeitserklärung",
  "George Gordon Byron": "Britischer Dichter und führender Vertreter der Romantik",
  "Dieter Bohlen": "Deutscher Musiker, Produzent und Fernsehpersönlichkeit",
  "R. W. Emerson": "US-amerikanischer Essayist und Philosoph, Prägung des Transzendentalis",
  "Edward Stanley Gibbons": "Gründer von Stanley Gibbons, einem führenden Briefmarkenhandelshaus.",
  "Robert Lembke": "Deutscher Journalist, Fernsehmoderator und Quizmaster",
  "Operation: Broken Arrow": "Film über den Diebstahl von US-Atombomben.",
  "Friedrich Hebbel": "Deutscher Dramatiker und Lyriker des 19. Jahrhunderts.",
  "Abraham Lincoln": "16. Präsident der USA, bekannt für die Abschaffung der Sklaverei.",
  "Lü Buwei": "Chinesischer Staatsmann und Gelehrter der Qin-Dynastie",
  "Kurt Tucholsky": "Deutscher Schriftsteller und Satiriker, bekannt für Gesellschaftskriti",
  "Max Böhm": "Deutscher Maler bekannt für seine impressionistischen Werke.",
  "Thomas Huxley": "Britischer Biologe und Verteidiger der Evolutionstheorie",
  "Blaise Pascal": "Französischer Mathematiker, Physiker und Philosoph",
  "Bibel": "Heiliges Buch der Christen und Juden mit religiösen Texten",
  "Aurelius Augustinus": "Christlicher Theologe und Philosoph, bekannt als Augustinus von Hippo.",
  "aus Bulgarien": "Bezieht sich auf Dinge oder Personen aus Bulgarien",
  "Bibel (Matthäus 6,24)": "Ein Vers aus dem Matthäusevangelium über Gottes- oder Geldesdienst.",
  "A. de Saint-Exupery": "Französischer Schriftsteller und Pilot, bekannt für ‚Der kleine Prinz‘",
  "2 Tage Paris (Film)": "Deutsche Komödie über einen chaotischen Aufenthalt in Paris.",
  "Michael Josef Sommer": "Deutscher Politiker, Mitglied der SPD.",
  "J. W. von Goethe": "Deutscher Dichter und Schriftsteller, bekannt für 'Faust'.",
  "Klabund": "Deutscher Schriftsteller und Dichter, bekannt für Lyrik und Theater",
  "Ghostbusters": "Film über ein Team, das Geister jagt und paranormalen Aktivitäten bege",
  "Lateinisches Sprichwort": "Kurzer, prägnanter Satz mit allgemeiner Weisheit in Latein.",
  "Hugo von Hofmannsthal": "Österreichischer Schriftsteller und Dramatiker der Moderne",
  "Mao Tse-tung": "Kommunistischer Revolutionär und Führer der Volksrepublik China",
  "Otto Lilienthal": "Pionier der Luftfahrt und deutscher Gleiterflieger.",
  "Hiram Johnson": "US-amerikanischer Politiker und Gouverneur von Kalifornien",
  "Ambrose Bierce": "US-amerikanischer Schriftsteller und Satiriker",
  "Richard P. Feynman": "US-amerikanischer Physiker, bekannt für Quantenmechanik und Wissenscha",
  "Ed Wood": "Amerikanischer Filmemacher, bekannt für Low-Budget- und Kultfilme.",
  "Jean-Jacques Rousseau": "Französisch-schweizerischer Philosoph und Schriftsteller der Aufklärun",
  "KarlHeinz Karius": "Deutscher Fußballtorwart, bekannt für seine Zeit bei Liverpool FC.",
  "Isaac Abella": "US-amerikanischer Schriftsteller und Dichter",
  "Johann Wolfgang von Goethe": "Deutscher Dichter, Schriftsteller und Naturforscher",
  "Thomas Morus": "Englischer Staatsmann und Philosoph, bekannt für \"Utopia\".",
  "Robert Luis Stevenson": "Schottischer Schriftsteller, bekannt für Abenteuerromane wie 'Die Scha",
  "Samuel Smiles": "Britischer Schriftsteller und Reformpädagoge, bekannt für Selbsthilfel",
  "Albert Einstein": "Theoretischer Physiker, bekannt für Relativitätstheorie.",
  "Anatole France": "Französischer Schriftsteller und Literaturnobelpreisträger",
  "Nigerianisches Sprichwort": "Traditionelles Sprichwort aus Nigeria mit kultureller Bedeutung",
  "Niels Bohr": "Dänischer Physiker, Begründer des Atommodells mit Quantensprüngen",
  "Neil Armstrong": "Erster Mensch auf dem Mond, US-amerikanischer Astronaut",
  "Friedrich Hölderlin": "Deutscher Dichter, geprägt von Romantik und Klassik",
  "Johann Kaspar Lavater": "Schweizer Theologe und Physiognomiker, bekannt für Gesichtsdeutung",
  "Thomas Häntsch": "Deutscher Politiker und Mitglied der Linken",
  "Sepp Wejwar": "",
  "Full Metal Jacket": "Anti-Kriegsfilm von Stanley Kubrick über Vietnamkriegssoldaten.",
  "John Dryden": "Englischer Dichter und Kritiker des 17. Jahrhunderts",
  "Lukas 12,34": "Bibelvers im Lukas-Evangelium über Schätze im Himmel",
  "aus Spanien": "Land in Südwesteuropa auf der Iberischen Halbinsel",
  "Der Soldat James Ryan": "Kriegfilm über die Suche nach einem Soldaten im Zweiten Weltkrieg",
  "Jüdisches Sprichwort": "Traditionelle Weisheit und Lebensregeln aus der jüdischen Kultur.",
  "Honore de Balzac": "Französischer Schriftsteller, bekannt für die Sammlung 'La Comédie Hum",
  "Arthur Schnitzler": "Österreichischer Schriftsteller und Dramatiker, bekannt für psychologi",
  "Queen Elizabeth": "Ehemalige Königin von Großbritannien und Nordirland.",
  "Jeannette Rankin": "Erste US-Kongressabgeordnete und Friedensaktivistin",
  "J. Grimm": "Deutscher Sprachwissenschaftler und Sammler von Märchen",
  "Conrad Singer": "US-amerikanischer Literaturwissenschaftler und Übersetzer",
  "Dragoslav Stepanovic": "Serbischer Fußballtrainer und ehemaliger Spieler",
  "Douglas MacArthur": "US-General, spielte bedeutende Rolle im Pazifikkrieg im Zweiten Weltkr",
  "Bertolt Brecht": "Deutscher Dramatiker und Lyriker, bekannt für episches Theater.",
  "Needful Things": "Roman von Stephen King über ein Geschäft mit verführerischen Angeboten",
  "Joseph Joubert": "Französischer Essayist und Moralphilosoph",
  "aus Irland": "Bezieht sich auf etwas, das aus Irland stammt oder mit Irland zu tun h",
  "Guybrush Threepwood": "Hauptcharakter der Monkey Island Adventures, ein Pirat.",
  "Václav Havel": "Tschechischer Dramatiker, Politiker und Staatspräsident",
  "Lothar Peppel": "Deutscher Schauspieler bekannt für Theater- und Fernsehrollen",
  "Meister Eckhart": "Deutscher Mystiker, Theologe und Philosoph des Mittelalters",
  "Klaus Kornwachs": "Deutscher Biologe und Wissenschaftskommunikator",
  "Michael Rumpf": "Deutscher Schriftsteller und Übersetzer",
  "Franz Grillparzer": "Österreichischer Dramatiker und Dichter des 19. Jahrhunderts",
  "Mahatma Gandhi": "Indischer Führer der Gewaltlosigkeit und Unabhängigkeitsbewegung",
  "Rupert Schützbach": "",
  "Franz Beckenbauer": "Deutscher Fußballspieler und -trainer, bekannt als \"Der Kaiser\".",
  "Danny Kaye": "US-amerikanischer Schauspieler, Sänger und Entertainer",
  "Arthur Schopenhauer": "Deutscher Philosoph, bekannt für Pessimismus und Wille zur Macht.",
  "Heinrich Schliemann": "Deutscher Archäologe, bekannt für Ausgrabungen in Troja.",
  "Zwei bärenstarke Typen": "Deutscher Action-Krimi-Film mit Comedy-Elementen.",
  "Hermann Stehr": "Deutscher Schriftsteller und Lyriker",
  "Harald Schmidt": "Deutscher Fernsehmoderator, Entertainer und Schauspieler",
  "Michael Ende": "Deutscher Schriftsteller, bekannt für 'Die unendliche Geschichte'.",
  "Billy": "Männlicher Vorname, oft als Kurzform von William verwendet",
  "James Branch Cabell": "Amerikanischer Schriftsteller, bekannt für phantastische Literatur.",
  "John Steinbeck": "US-amerikanischer Schriftsteller, bekannt für 'Früchte des Zorns'",
  "Leo Tolstoi": "Russischer Schriftsteller, bekannt für 'Krieg und Frieden'.",
  "Naguib Mahfouz": "Ägyptischer Schriftsteller und Nobelpreisträger für Literatur.",
  "Andreas Tenzer": "Deutscher Physiker und Hochschullehrer an der Universität Duisburg-Ess",
  "Dante Alighieri": "Italienischer Dichter, bekannt für die Göttliche Komödie.",
  "Charles Dickens": "Britischer Schriftsteller, bekannt für sozialkritische Romane",
  "William Schroeder": "Name ohne eindeutige öffentliche Bekanntheit.",
  "Philipp Fürchtegott Reemstma": "Deutscher Industrieller und Unternehmer der Tabakindustrie.",
  "Wissenswertes": "Informationen oder Fakten zu verschiedenen Themen",
  "Giovanni Guareschi": "Italienischer Schriftsteller und Journalist, bekannt für Don Camillo.",
  "Sigmund Graff": "",
  "Henry Louis Mencken": "Amerikanischer Journalist, Essayist und Kritiker",
  "Berthold Auerbach": "Deutscher Schriftsteller, bekannt für realistische Dorfgeschichten.",
  "Charles Péguy": "Französischer Dichter und Essayist, bekannt für patriotische Werke.",
  "aus Japan": "Land in Ostasien, bekannt für Technologie und Kultur.",
  "\"\"Das letzte Einhorn\"\"": "Ein Fantasy-Roman über ein Einhorn, das seine Art sucht.",
  "Sigismund von Radecki": "Preußischer General und Militärschriftsteller",
  "Hieronimus": "Vorname mit biblischem Ursprung, oft in Deutschland verwendet",
  "Plato": "Griechischer Philosoph, Begründer der abendländischen Philosophie.",
  "Ottokar Kernstock": "Österreichischer Dichter und Priester, bekannt für patriotische Lieder",
  "Dwight D. Eisenhower": "US-General und Präsident, führte Alliierte im Zweiten Weltkrieg",
  "Romain Gary": "Französischer Schriftsteller und Diplomat mit polnischen Wurzeln",
  "Voltaire": "Französischer Philosoph und Aufklärer, bekannt für Satire und Kritik.",
  "Lilo Keller": "Schweizer Skispringerin",
  "Aristoteles": "Griechischer Philosoph, begründete Logik und Wissenschaftstheorie",
  "Franziska zu Reventlow": "Deutsche Schriftstellerin und Künstlerin, Teil der Boheme in München",
  "Scarie Movie": "Parodiefilm, die Horrorfilme humorvoll verarbeitet.",
  "Alberto Sordi": "Italienischer Schauspieler und Komiker, bekannt für komische Rollen.",
  "Friedrich Schlegel": "Deutscher Schriftsteller und Philosoph, Mitbegründer der Romantik",
  "Augustinus Aurelius": "Bischof von Hippo und bedeutender Kirchenvater der frühen Christentum.",
  "Greg Behrendt": "US-amerikanischer Autor und Comedian, bekannt für Beziehungstipps.",
  "Giordano Bruno": "Italienischer Philosoph und Kosmologe, bekannt für kosmische Theorien.",
  "Sir Winston Churchill": "Britischer Politiker und Premierminister während des Zweiten Weltkrieg",
  "U-Boot in Not": "Deutscher Spielfilm über ein deutsches U-Boot im Krieg.",
  "Lothar Schmidt": "Deutscher Name, mehrere Personen bekannt",
  "Denis Diderot": "Französischer Philosoph und Enzyklopädist der Aufklärung",
  "G. Hauptmann": "Deutscher Dramatiker und Schriftsteller des Naturalismus.",
  "Carl Friedrich Freiherr von Weizsäcker": "Deutscher Physiker und Philosoph, bekannt für Beiträge zur Quantenmech",
  "Laotse": "Legendärer chinesischer Philosoph und Begründer des Taoismus",
  "James Bond 007": "Fiktiver britischer Geheimagent, bekannt aus Romanen und Filmen.",
  "iBash": "Ein YouTube-Kanal für Musik, Comedy und Unterhaltung.",
  "Jeannine Luczak": "Französische Autorin und Journalistin",
  "Fuat Kaya": "Deutscher Musiker und Produzent, bekannt für Pop und Rap",
  "Friedrich Nietzsche": "Deutscher Philosoph, bekannt für Werke über Moral und Kultur",
  "The Dish": "Australischer Film über die Rolle eines Radioteleskops bei der Mondlan",
  "Ägyptisches Sprichwort": "Traditioneller Spruch aus der altägyptischen Kultur",
  "Isaac Asimov": "US-amerikanischer Autor von Science-Fiction und populärwissenschaftlic",
  "Hans Weigel": "Österreichischer Schriftsteller und Theaterkritiker",
  "alte Bauernweisheit": "Traditionelle Sprichwörter und Erfahrungen von Landwirten",
  "J.W.  Biermann": "Deutscher Schriftsteller und Musiker, bekannt für expressionistische W",
  "Graham Chapman": "Britischer Komiker und Mitglied der Monty-Python-Gruppe",
  "Suaheliweisheit": "Traditionelle Weisheit und Sprichwörter der Suaheli-Kultur",
  "William Rogers": "Englischer Name, häufig ohne Bezug auf spezifische Person",
  "Die Braut die sich nicht traut": "Deutscher Film über eine Frau, die Angst vor der Hochzeit hat",
  "National Geographic": "Wissenschafts-Magazin und TV-Kanal mit Natur- und Kulturdokus",
  "Antoine de Saint-Exupery": "Französischer Schriftsteller und Pilot, bekannt für 'Der Kleine Prinz'",
  "Joachim Ringelnatz": "Deutscher Schriftsteller und Kabarettist, bekannt für humorvolle Gedic",
  "Erich Kastner": "Deutscher Schriftsteller, bekannt für Kinderliteratur und Satiren.",
  "Edwin Chapin": "US-amerikanischer Prediger und Autor des 19. Jahrhunderts",
  "Oscar Wilde": "Irischer Schriftsteller und Dramatiker, bekannt für seinen Witz",
  "Friedrich Georg Jünger": "Deutscher Schriftsteller und Bruder von Ernst Jünger",
  "Georg Skrypzak": "",
  "Max Planck": "Deutscher Physiker, Begründer der Quantenphysik",
  "Miguel de Cervantes": "Spanischer Schriftsteller, bekannt für \"Don Quijote\".",
  "Friedrich II, der Große": "Preußischer König, bekannt für Militärführung und Aufklärung",
  "Claude-Adrien Helvetius": "Französischer Philosoph der Aufklärung, bekannt für materialistische A",
  "Laurence Sterne": "Englischer Schriftsteller, bekannt für 'Tristram Shandy'",
  "Afrikanisches Sprichwort": "Traditionelles Sprichwort aus der afrikanischen Kultur",
  "Pavel Kosorin": "Russischer Schriftsteller und Journalist",
  "Rabindranath Tagore": "Indischer Dichter, Philosoph und Nobelpreisträger für Literatur",
  "Arabisches Sprichwort": "Traditioneller Ausdruck mit lebensweisem Inhalt in der arabischen Kult",
  "Ron Kritzfeld": "Deutscher Schauspieler und Kabarettist",
  "Konrad Adenauer": "Erster Bundeskanzler der Bundesrepublik Deutschland nach dem Zweiten W",
  "Giacomo Casanova": "Italienischer Schriftsteller und Abenteurer, bekannt für Memoiren.",
  "J. G. Herder": "Deutscher Philosoph und Theologe, Begründer der Kulturphilosophie.",
  "James Wayner": "",
  "Ernst Ferstl": "Österreichischer Lyriker und Lehrer, bekannt für kurze Gedichte.",
  "aus der Türkei": "Bezieht sich auf Dinge oder Personen aus der Türkei"
};
