export default {
  "Henri Frederich Amiel": "Scrittore e filosofo svizzero noto per i suoi diari personali.",
  "Stanisław Jerzy Lec": "Scrittore e aforista polacco noto per i suoi motti pungenti.",
  "H.Ibsen": "Drammaturgo norvegese, padre del teatro moderno.",
  "Margaret Atwood": "Scrittrice canadese nota per i romanzi distopici e la poesia.",
  "Harvey Dent": "Personaggio DC Comics noto come Due Facce, avvocato e vigilante.",
  "C. Pavese": "Scrittore e poeta italiano noto per la sua letteratura esistenziale.",
  "Michel Zamacoïs": "Scrittore e giornalista francese noto per le sue opere teatrali e lett",
  "Cesare Augusto": "Primo imperatore romano, consolidò l'impero e la pace romana.",
  "Francesco Guccini": "Cantautore e scrittore italiano noto per testi poetici e impegno civil",
  "John Perry Barlow": "Attivista e paroliere statunitense, cofondatore di EFF.",
  "Robert ed Ellen Kaplan": "Autore e giornalista americano specializzato in politica e affari inte",
  "Noël Coward": "Drammaturgo, compositore e attore britannico noto per opere brillanti",
  "Kahlil Gibran": "Poeta, filosofo e artista libanese-americano famoso per \"Il Profeta\".",
  "Aleksandr Sergeevič Puškin": "Poeta e scrittore russo, fondatore della letteratura russa moderna.",
  "\"\"Blade Runner\"\" (film)": "Film di fantascienza su un cacciatore di replicanti in un futuro disto",
  "Isaac Asimov": "Scrittore e biochimico noto per la fantascienza e la divulgazione scie",
  "Motörhead": "Band rock britannica famosa per il suo stile heavy metal potente.",
  "David Frost": "Giornalista e conduttore televisivo britannico noto per interviste inc",
  "Isaac Bashevis Singer": "Scrittore americano di lingua yiddish, premio Nobel per la letteratura",
  "A.Artaud": "Poeta e drammaturgo francese noto per il teatro della crudeltà",
  "La torre nera, S. King": "Serie di romanzi fantasy di Stephen King ambientata in un mondo oscuro",
  "Ian Stewart": "Matematico e autore britannico specializzato in teoria dei numeri.",
  "Gene Gnocchi": "Comico e conduttore televisivo italiano noto per il cabaret.",
  "Sconosciuto": "Persona o entità non identificata o nota",
  "Fabrizio De André": "Cantautore italiano noto per le sue canzoni poetiche e impegnate",
  "Molière": "Drammaturgo e attore francese, celebre per le sue commedie teatrali.",
  "Arthas (\"\"Warcfaft\"\")": "Personaggio di Warcraft, principe che diventa il Cavaliere della Morte",
  "Vincenzo Cuoco": "Scrittore e patriota italiano noto per opere sul Risorgimento.",
  "Mel Brooks": "Regista e comico americano noto per film umoristici e parodie",
  "Anwar al Sadat": "Terzo presidente dell'Egitto, noto per la pace con Israele.",
  "Sigmund Freud": "Neurologo austriaco fondatore della psicoanalisi",
  "D.Barenboim": "Direttore d'orchestra e pianista noto per interpretazioni innovative",
  "Laozi": "Filosofo cinese antico, fondatore del taoismo e autore del Tao Te Chin",
  "Roland Barthes": "Saggio critico francese, studioso di linguistica e semiotica",
  "Blade (film)": "Film action su un cacciatore di vampiri mezzo umano e mezzo vampiro.",
  "Seymour Roger Cray": "Ingegnere americano noto per lo sviluppo di supercomputer.",
  "Funghi da Yuggoth": "Raccolta di racconti horror ispirati ai miti di Cthulhu.",
  "Karl Gustav Jacob Jacobi": "Matematico tedesco noto per contributi all'analisi e algebra",
  "Sinead O'Connor": "Cantautrice irlandese nota per la sua musica e il look iconico.",
  "Petronio Arbitro": "Scrittore e grammatico latino noto per opere letterarie e linguistiche",
  "Zhuangzi": "Filosofo cinese noto per i suoi insegnamenti taoisti e testi omonimi.",
  "Darkwing Duck": "Serie animata con un papero supereroe che combatte il crimine",
  "W.Gibson": "Scrittore canadese noto per il romanzo cyberpunk \"Neuromante\".",
  "Mark Reid": "Nome comune senza dettagli specifici noti",
  "Giordano Bruno": "Filosofo e scrittore italiano, noto per le sue idee sull'infinito.",
  "C.Dossi": "Pittore italiano noto per opere surrealiste e simboliste.",
  "Troy (film)": "Film epico basato sulla guerra di Troia nella mitologia greca",
  "Afterhours (band di rock)": "Band rock italiano noto per il loro stile alternativo e testi profondi",
  "Agente 007": "Personaggio immaginario, famoso agente segreto nei film di James Bond.",
  "Bernard Shaw": "Drammaturgo e critico irlandese, vincitore del premio Nobel",
  "T.Eliot": "Poeta e drammaturgo anglo-americano, figura chiave del modernismo",
  "Il pianeta del tesoro": "Film d'animazione Disney basato su \"L'isola del tesoro\"",
  "David Victor": "Nome comune senza informazioni specifiche disponibili.",
  "Wernher von Braun": "Ingegnere astronautico tedesco-americano, pioniere missilistico.",
  "Linus Torvalds": "Creatore del kernel Linux, influente sviluppatore di software open sou",
  "George Moore": "Scrittore irlandese noto per romanzi e racconti realistici.",
  "A.Loos": "Architetto e teorico olandese noto per il modernismo architettonico.",
  "Iginio Ugo Tarchetti": "Scrittore e poeta italiano dell'Ottocento, esponente del Verismo.",
  "Angelo Branduardi": "Cantautore e musicista italiano noto per la musica folk e medievale.",
  "W. Shakespeare": "Drammaturgo e poeta inglese, autore di numerose opere teatrali.",
  "Pittaco": "Antico poeta e legislatorie greco di Mielea",
  "Stanislao Nievo": "Scrittore e giornalista italiano noto per opere letterarie e reportage",
  "G. Fanciulli": "Produttore discografico e DJ italo-americano di musica elettronica.",
  "Anassagora": "Filosofo presocratico greco, noto per la teoria dell'archè come mente ",
  "Acchiappafantasmi (flm)": "Film comico su cacciatori di fantasmi e avventure soprannaturali.",
  "Nek": "Cantante e cantautore italiano di musica pop e rock.",
  "Georges Bernanos": "Scrittore francese noto per i suoi romanzi religiosi e filosofici.",
  "Louis Philippe de Ségur": "Diplomatico e storico francese noto per le sue memorie e opere.",
  "Rat-Man": "Fumetto italiano comico e satirico su un supereroe goffo.",
  "A.Clarke": "Scrittore di fantascienza britannico famoso per \"2001: Odissea nello s",
  "Mr.Freeze (Batman&Robin)": "Villain ghiacciato nel film Batman & Robin",
  "Giuseppe Fanciulli": "Compositore italiano conosciuto per le sue opere melodrammatiche.",
  "M.Perahia": "Pianista e direttore d'orchestra britannico di origine israeliana",
  "Niccolò Castiglioni": "Compositore italiano noto per musica contemporanea e sperimentale",
  "Isabel Allende": "Scrittrice cilena nota per romanzi che mescolano realismo e storia.",
  "Wikipedia": "Encyclopedia online collaborativa e gratuita in molte lingue.",
  "\"\"Fiori d' acciaio\"\" (film)": "Film italiano che narra la storia di cinque donne amiche.",
  "\"\"Rinaldo\"\" di G. F. Händel": "Opera barocca di Händel basata sul poema cavalleresco.",
  "Gianluca Bedini": "Gianluca Bedini, nome comune italiano, identità specifica sconosciuta",
  "Thomas Szasz": "Psichiatra e scrittore ungherese-americano critico della psichiatria t",
  "Antico Testamento": "Parte della Bibbia che contiene testi sacri e storici ebraici.",
  "A.E.Stevenson": "Scrittore e giornalista britannico noto per opere di narrativa.",
  "Giorgio di Gallipoli": "Santo italiano venerato nella tradizione cattolica.",
  "AC/DC": "Band rock australiana famosa per brani hard rock e heavy metal",
  "Giovanni Verga": "Scrittore italiano noto per il verismo e opere come \"I Malavoglia\".",
  "Albert Einstein": "Fisico teorico famoso per la teoria della relatività",
  "Alda Merini": "Poetessa italiana nota per la sua poesia intensa e autobiografica",
  "Avner": "Nome maschile ebraico significativo in vari contesti culturali.",
  "Dave Barry": "Scrittore umoristico e giornalista statunitense.",
  "\"\"Frankenstein Junior\"\" (film)": "Commedia che parodia il film horror classico di Frankenstein.",
  "Chuck Palahniuk": "Scrittore americano noto per romanzi di narrativa contemporanea e sati",
  "Graham Cluley": "Esperto britannico in sicurezza informatica e divulgatore tecnologico",
  "J.P.Riechter": "",
  "Apuleio": "Scrittore latino noto per \"Le metamorfosi\" o \"L'asino d'oro\".",
  "Théophile Gautier": "Scrittore e poeta francese del Romanticismo",
  "Proverbio pugliese": "Detto tradizionale della Puglia con saggezza popolare.",
  "Catherine Doherty": "Fondatrice di Madonna House, attivista cattolica per la giustizia soci",
  "Orson Welles": "Regista e attore americano, noto per 'Quarto potere'",
  "Lucio Battisti": "Cantautore italiano influente nella musica pop e rock",
  "Il Piccolo Principe": "Racconto filosofico di Antoine de Saint-Exupéry sugli aspetti della vi",
  "Goethe": "Scrittore e poeta tedesco, autore del Faust.",
  "Jean Rostand": "Biologo e scrittore francese noto per studi sulla genetica e l'epigene",
  "\"\"Acchiappafantasmi\"\" (film)": "Film italiano commedia con elementi soprannaturali",
  "Pirati dei Caribi (film)": "Film d'avventura con pirati e tesori nei Caraibi",
  "Brian Greene": "Fisico e divulgatore scientifico noto per la teoria delle stringhe.",
  "Erasmo da Rotterdam": "Umanista olandese, critico della Chiesa e autore di \"Elogio della foll",
  "Bob Hope": "Comico e attore britannico-americano noto per il suo umorismo e spetta",
  "Agnus Young (AC/DC)": "Chitarrista e cofondatore degli AC/DC, noto per il suo stile energico.",
  "D.Adams": "Autore britannico noto per la serie 'Guida galattica per autostoppisti",
  "Charles Péguy": "Poeta e saggista francese noto per le sue opere letterarie e filosofic",
  "\"\"Troy\"\" (film)": "Film epico sul conflitto tra Greci e Troiani basato sull'Iliade.",
  "Miguel de Unamuno": "Scrittore e filosofo spagnolo, esponente della Generazione del '98",
  "H. P. Lovecraft": "Scrittore americano noto per il genere horror e il mito di Cthulhu",
  "Barry Cryer": "Comico e scrittore britannico, noto per la sua satira e stand-up",
  "Frank Herbert": "Scrittore statunitense noto per il romanzo di fantascienza \"Dune\".",
  "Carla Bruni": "Cantautrice e ex modella francese, nota anche come First Lady d'Italia",
  "\"\"Demoni\"\" (film)": "Film horror italiano cult con temi sovrannaturali e possessione",
  "H.Hesse": "Scrittore e poeta tedesco, noto per opere come \"Siddhartha\".",
  "Stanislaw J. Lec": "Poeta e aforista polacco noto per i suoi aforismi filosofici.",
  "Odoardo Spadaro": "Cantautore e attore italiano noto per canzoni toscane.",
  "Socrate": "Filosofo greco antico, padre della filosofia occidentale.",
  "Italo Calvino": "Scrittore italiano noto per le sue opere di narrativa innovativa.",
  "G.Fanciulli": "Produttore e DJ di musica house italiano riconosciuto a livello intern",
  "Junio Valerio Borghese": "Militare e politico italiano noto per il suo ruolo durante la seconda ",
  "\"\"l gladiatore\"\" (film)": "Film epico su un generale romano diventato gladiatore.",
  "Pink Floyd": "Band rock britannico noto per album concettuali e sonorità psichedelic",
  "Simone de Beauvoir": "Scrittrice e filosofa francese, figura chiave del femminismo.",
  "José Saramago": "Scrittore portoghese noto per opere di narrativa e premi letterari",
  "Stephen King": "Scrittore americano noto per i suoi romanzi horror e thriller",
  "Fernando Pessoa": "Poeta e scrittore portoghese noto per le sue opere eterogenee.",
  "Elvis Presley": "Cantante e icona culturale statunitense, noto come il Re del Rock.",
  "S.Mangano": "",
  "R.Gervazo": "",
  "Ivan Fedele": "Compositore e direttore d'orchestra italiano contemporaneo.",
  "David Bidussa": "Filosofo e politologo francese, studioso di teoria politica.",
  "Re Salomone": "Re biblico noto per la sua saggezza e per il Tempio di Gerusalemme",
  "\"\"Apocalypse Now\"\" (film)": "Film di guerra che esplora il conflitto in Vietnam e la follia umana.",
  "U.Ughi": "Violinista italiano di fama internazionale",
  "Mario Cappolani": "Regista e sceneggiatore italiano specializzato in cinema e televisione",
  "Gaston Bachelard": "Filosofo francese noto per i suoi studi sull'epistemologia e la poetic",
  "C.Marchi": "Autore e studioso italiano contemporaneo",
  "Nino Rota (\"\"Il Padrino\"\" soundtrack)": "Compositore italiano famoso per colonne sonore di film, tra cui Il Pad",
  "Proverbio": "Breve frase con saggezza popolare o insegnamento morale.",
  "Marianne Moore": "Poetessa americana nota per la sua poesia moderna e tecnica innovativa",
  "\"\"Fight club\"\" (film)": "Film drammatico che esplora l'identità e la rivolta sociale",
  "Quinto Orazio Flacco": "Poeta romano noto per le sue odi e satire.",
  "Voltaire": "Filosofo e scrittore francese dell'Illuminismo",
  "Jules Verne": "Scrittore francese noto per i suoi romanzi di avventura e fantascienza",
  "\"\"Blade-2\"\" (film)": "Film d'azione e fantastico con protagonisti vampiri e cacciatori",
  "Attribuita a Maria Antonietta d'Asburgo-Lorena": "Regina di Francia, simbolo di eleganza e controversie storiche",
  "C. G. Jung": "Psicologo svizzero, fondatore della psicologia analitica.",
  "Corrado Guzzanti": "Attore, comico e satirico italiano noto per le sue imitazioni e parodi",
  "F.Bacone": "Filosofo e scienziato inglese, pioniere del metodo scientifico.",
  "J. C. de Flancy": "Poeta e sacerdote francese noto per opere simboliste e mistico-religio",
  "A.Maurois": "Scrittore e saggista francese famoso per biografie e romanzi.",
  "A.Bello": "",
  "Balle spaziali": "Film italiano comico che parodia la fantascienza.",
  "Robert Louis Stevenson": "Scrittore scozzese noto per avventure come \"Lo strano caso del dottor ",
  "Vittorio Giovanni Rossi": "Scrittore e giornalista italiano noto per opere sul mare e l'avventura",
  "Don Corleone": "Personaggio mafioso del romanzo Il Padrino di Mario Puzo",
  "Dennis Van Gerven": "Atleta olandese specializzato in corsa campestre e maratona",
  "Juan Baladán Gadea": "Politico e scrittore venezuelano",
  "R.Tagore": "Poeta e filosofo indiano, premio Nobel per la letteratura.",
  "Thích Nhất Hạnh": "Monaco buddhista vietnamita e autore di testi sulla mindfulness",
  "T. Adams": "",
  "Sopranommi di Sauron": "Titoli e soprannomi attribuiti a Sauron nell'universo de Il Signore de",
  "P.Picasso": "Pittore e scultore spagnolo, figura chiave del cubismo.",
  "F. Dostoevskij": "Scrittore russo noto per romanzi psicologici profonde",
  "Luis de Góngora": "Poeta spagnolo del Siglo de Oro, noto per la complessità del suo stile",
  "Lev Tolstoj": "Scrittore russo noto per romanzi come Guerra e Pace e Anna Karenina",
  "Adlai Ewing Stevenson I": "Politico e diplomatico statunitense del XX secolo.",
  "Yuri Temirkanov": "Direttore d'orchestra russo noto per le sue interpretazioni di musica ",
  "Woody Allen": "Regista, sceneggiatore e attore statunitense noto per film e commedie.",
  "M.Eliade": "Storico delle religioni e filosofo rumeno",
  "Lo strappo (film)": "Film italiano che esplora un viaggio e relazioni complesse.",
  "Callimaco": "Personaggio principale de \"Il Mandrake\" di Machiavelli.",
  "WH40K": "Universo fantascientifico distopico di Warhammer 40,000.",
  "Kowa Seki": "Doppiatrice e cantante giapponese",
  "Arthur Bloch": "Autore noto per la serie 'Legge di Murphy' e satira umoristica.",
  "Norma (Opera di Bellini)": "Opera tragica di Bellini basata sulla tragedia di Scribe.",
  "Proverbio navajo": "Detto tradizionale della cultura Navajo con saggezza popolare.",
  "Indro Montanelli": "Giornalista e scrittore italiano famoso per le sue cronache storiche.",
  "\"\"Final Destination 3\"\" (film)": "Film horror sul destino e la morte inevitabile",
  "Mahatma Gandhi": "Leader spirituale e politico indiano per l'indipendenza non violenta",
  "Dante, La vita nuova": "Opera di Dante che combina poesia e prosa sulla sua amata Beatrice.",
  "Mark Twain": "Scrittore e umorista americano noto per Le avventure di Tom Sawyer",
  "Ilona Staller": "Attrice e politica italo-ungherese, nota come Cicciolina.",
  "Richard Swanson": "Fondatore di Sunrise Technologies, noto per innovazioni nel solare.",
  "Stanislaw Dziwisz": "Cardinale e vescovo polacco, segretario di papa Giovanni Paolo II.",
  "Bob Jones": "Nome comune, può riferirsi a diverse persone",
  "Joseph Roth": "Scrittore e giornalista austriaco noto per romanzi storici e sociali",
  "Robert De Niro": "Attore e produttore cinematografico statunitense famosissimo",
  "G.Bruno": "Filosofo e matematico italiano noto per le sue idee eretiche",
  "\"\"Fahrenheit 451\"\" (film)": "Adattamento cinematografico del romanzo distopico di Ray Bradbury.",
  "John Keats": "Poeta inglese del Romanticismo, noto per le sue odi e poesie liriche",
  "\"\"Rambo\"\" (film)": "Film d'azione con protagonista un veterano di guerra in conflitto",
  "Karl Kraus": "Scrittore e satirico austriaco noto per la critica sociale e culturale",
  "M.Pagnol": "Scrittore e regista francese, noto per opere teatrali e film",
  "Maitri Upanisad": "Antico testo sacro indù che fa parte degli Upanishad",
  "Theodor Fontane": "Scrittore tedesco noto per i suoi romanzi realistici",
  "Umberto Eco": "Scrittore e semiologo italiano noto per il romanzo \"Il nome della rosa",
  "Pablo Picasso": "Pittore e scultore spagnolo, tra i fondatori del cubismo.",
  "A.Accatino": "",
  "K.Kraus": "Scrittore e critico austriaco noto per la satira e il teatro.",
  "Isaac Babel'": "Scrittore e giornalista russo noto per racconti brevi e reportage",
  "Giuseppe Genna": "Scrittore italiano noto per i suoi romanzi contemporanei.",
  "Douglas MacArthur": "Generale americano noto per il ruolo nella Seconda guerra mondiale",
  "François Mauriac": "Scrittore e giornalista francese noto per opere sul cattolicesimo.",
  "Carlo Porta": "Poeta milanese noto per la satira in dialetto lombardo.",
  "\"\"Die Hard\"\" (film)": "Film d'azione americano con Bruce Willis come poliziotto sfidante crim",
  "J.-P. Sartre": "Filosofo francese, fondatore dell'esistenzialismo moderno.",
  "Christopher Reich": "Scrittore americano noto per thriller finanziari e legali.",
  "Paracelso": "Medico e alchimista svizzero noto per la medicina iatrochimica.",
  "Legge de Murphy": "Principio secondo cui tutto ciò che può andar male, andrà male.",
  "A.Einstein": "Fisico teorico noto per la teoria della relatività.",
  "La piccola bottega degli orrori (film)": "Film horror musicale su una pianta carnivora senziente.",
  "Levitico 20:27": "Versetto biblico che tratta le prescrizioni contro la stregoneria.",
  "Sarah Bernhardt": "Attrice teatrale e scrittrice francese, celebre nel XIX secolo",
  "La Bibbia": "Testo sacro delle religioni cristiana ed ebraica.",
  "A.Hitchcock": "Regista britannico noto per i suoi film thriller e suspense",
  "Immanuel Kant": "Filosofo tedesco fondamentale nell'illuminismo e nella filosofia moder",
  "Dag Hammarskjöld": "Diplomatico svedese e segretario generale delle Nazioni Unite",
  "Novalis": "Poeta e filosofo tedesco, figura chiave del Romanticismo",
  "Denis Diderot": "Filosofo e scrittore francese, curatore dell'Encyclopédie",
  "Max Payne (videogiocco)": "Videogioco d'azione in terza persona con trama noir e gameplay bullet-",
  "Commodiano": "Filosofo romano cristiano antico, noto per le sue opere apologetiche.",
  "Pubblicità Progresso": "Associazione italiana per la comunicazione sociale e campagne pubblici",
  "Ch.Saint-Beuve": "Critico letterario e scrittore francese del XIX secolo.",
  "John Milton": "Poeta e filosofo inglese, autore di 'Paradiso Perduto'.",
  "Fortunato Baldelli": "Cardinale italiano della Chiesa cattolica.",
  "Franco Enna": "Scrittore italiano noto per i suoi gialli e thriller",
  "Oliver Cromwell": "Leader militare e politico inglese durante la Guerra civile inglese",
  "Marshall McLuhan": "Teorico della comunicazione canadese noto per il concetto di \"villaggi",
  "Garfield (fumetto)": "Fumetto umoristico con gatto pigro e amante della lasagna.",
  "V.Boskov": "Allenatore di calcio noto per la sua carriera in Italia e Jugoslavia",
  "O.Wilde": "Scrittore e poeta irlandese noto per il suo spirito e le opere teatral",
  "Martin Amis": "Scrittore britannico noto per romanzi e saggi critici.",
  "Le Corbusier": "Architetto e urbanista innovativo del XX secolo.",
  "Aristotele": "Filosofo greco antico, fondò la logica formale e influenzò molte disci",
  "Charles Baudelaire": "Poeta e critico francese, noto per \"I fiori del male\".",
  "Franz Kafka": "Scrittore praghese noto per storie surreali e temi esistenziali",
  "Libero Bovio": "Poeta e scrittore italiano in lingua napoletana.",
  "\"\"Ed, Edd & Eddy\"\" (serie tv d'animazione )": "Serie animata canadese su tre amici con schemi per fare soldi.",
  "Jurrasic Park (film)": "Film di avventura sulla clonazione di dinosauri in un parco a tema.",
  "G.Cocchiara": "",
  "Proverbio italiano": "Massima popolare italiana con insegnamento morale o pratico.",
  "Marco Sartorelli": "Calciatore italiano che gioca in posizione offensiva.",
  "Jack Kerouac": "Scrittore americano, pioniere della Beat Generation.",
  "Romano Battaglia": "Scrittore e giornalista italiano noto per opere di narrativa e reporta",
  "William Blake": "Poeta, pittore e incisore inglese noto per le sue opere visionarie",
  "Proverbio cinese": "Massima tradizionale cinese con insegnamenti morali o pratici.",
  "Proverbio chinese": "Detto tradizionale cinese che esprime saggezza popolare.",
  "Karl Popper": "Filosofo austriaco-britannico noto per la teoria della falsificabilità",
  "Adolf Loos": "Architetto austriaco noto per il suo stile moderno e funzionalista.",
  "Ernst Jünger": "Scrittore e filosofo tedesco noto per opere sulla guerra e tecnologia",
  "Sri Guru Granth Sahib": "Libro sacro e testo spirituale nella fede Sikh",
  "Frank Zappa": "Musicista e compositore americano noto per il rock e jazz sperimentale",
  "Victor Hugo": "Scrittore francese, autore de I Miserabili e Notre-Dame de Paris",
  "R.Wagner": "Compositore tedesco noto per le sue opere teatrali e musicali",
  "Joan Rivers": "Comica e attrice statunitense, nota per satira pungente e spettacoli T",
  "Il cavaliere oscuro (film)": "Film di Batman che esplora il conflitto con Joker in Gotham.",
  "Robert Jungk": "Scrittore e storico austriaco noto per opere su futuro e tecnologia",
  "Olga Visentini": "Giornalista e scrittrice italiana attiva nel giornalismo culturale.",
  "J.Cocteau": "Scrittore, poeta e regista francese del XX secolo",
  "Vladimir Putin": "Presidente e leader politico della Russia.",
  "Erri De Luca": "Scrittore e poeta italiano noto per il suo impegno civile",
  "Oscar Wilde": "Scrittore e drammaturgo irlandese noto per l'umorismo e lo stile",
  "Antoine de Saint-Exupéry": "Scrittore e aviatore francese, autore de Il Piccolo Principe.",
  "Jack London": "Scrittore statunitense noto per racconti sull'avventura e natura.",
  "Will Timmins": "Cantante e chitarrista britannico, membro della band Embrace.",
  "F.de Roberto": "Scrittore e drammaturgo italiano noto per opere sociali e politiche",
  "M.Quoist": "Autore francese noto per opere di spiritualità cristiana.",
  "Ch.Bukowski": "Scrittore e poeta americano noto per il realismo sporco e la vita boem",
  "A.Rembaud": "",
  "Anselmo Bucci": "Artista italiano associato al movimento futurista e all'arte moderna.",
  "\"\"Basic Instinct\"\" (film)": "Thriller erotico diretto da Paul Verhoeven con Sharon Stone.",
  "\"\"Predator\"\" (film)": "Film d'azione e fantascienza con caccia aliena sulla Terra.",
  "Yahoo!Answers": "Piattaforma di domande e risposte online del web Yahoo.",
  "Dante Alighieri": "Poeta italiano, autore della Divina Commedia.",
  "Pietro Verri": "Filosofo, economista e scrittore dell'Illuminismo italiano",
  "Esodo 33:5": "Verso biblico che avverte del pericolo di Dio nelle vicinanze.",
  "Aldos Huxley": "Scrittore e filosofo inglese, noto per \"Il mondo nuovo\".",
  "Paolo Virno": "Filosofo e linguista italiano noto per analisi del lavoro e comunicazi",
  "Cesare Cantù": "Storico e scrittore italiano noto per opere sulla storia d'Italia.",
  "Giovanni Bosco": "Sacerdote italiano noto per il lavoro con i giovani e i poveri.",
  "Maria Callas": "Celebre soprano lirica nota per la sua voce e interpretazioni drammati",
  "Khrushchev": "Leader sovietico noto per la destalinizzazione e la crisi dei missili",
  "Biggum Flodrot, goblin veterano (MthG)": "Goblin veterano del gioco di ruolo MthG",
  "George Orwell": "Scrittore britannico noto per le opere distopiche come 1984",
  "Th.Hobbes": "Filosofo inglese noto per le teorie sul contratto sociale.",
  "Pierre Corneille": "Drammaturgo francese, padre della tragedia classica francese.",
  "Sandro Pertini": "Politico italiano, presidente della Repubblica noto per la sua integri",
  "Apocalisse 1:18": "Verso biblico in cui Gesù dichiara di vivere per sempre.",
  "Sergio Saviane": "Politico e uomo pubblico italiano noto per impegno civico",
  "Emile Zola": "Scrittore francese, fondatore del naturalismo letterario.",
  "L'era glaciale": "Film d'animazione su animali preistorici durante l'era glaciale",
  "Atharva Veda Samhita": "Collezione di inni sacri dell'antica religione vedica indiana",
  "H.Böll": "Scrittore tedesco noto per opere contro la guerra e l'ingiustizia soci",
  "John Audubon": "Naturalista e illustratore noto per le sue dettagliate tavole di uccel",
  "Jules Bois": "Scrittore e occultista francese noto per studi sull'esoterismo.",
  "Diane Lane": "Attrice americana nota per ruoli drammatici e film romantici.",
  "Eli Khamarov": "Artista e regista noto per performance teatrali innovative.",
  "Gesù": "Figura centrale del cristianesimo, considerato il Messia e Figlio di D",
  "W.B.Yeats": "Poeta e drammaturgo irlandese, figura chiave del XX secolo.",
  "B. Disraeli": "Statista e primo ministro britannico, influente nel XIX secolo",
  "Herman Hesse": "Scrittore e poeta tedesco-svizzero noto per opere filosofiche e spirit",
  "Publio Siro": "Antico grammatica romano noto per le sue massime morali.",
  "Trainspotting": "Film britannico che esplora la vita di giovani tossicodipendenti a Edi",
  "Shadow Man (videogiocco)": "Videogioco d'azione con elementi stealth e narrativa oscura.",
  "Ennio Flaiano": "Scrittore e sceneggiatore italiano, noto per il suo lavoro con Fellini",
  "Frederic Prokosch": "Scrittore americano noto per i suoi romanzi e poesie",
  "Robert Walser": "Scrittore svizzero noto per la sua prosa minimalista e innovativa",
  "L. Ariosto": "Poeta italiano noto per l'opera epica 'Orlando furioso'.",
  "D.Lynch": "Regista e sceneggiatore noto per film surreali e inquietanti",
  "Jovanotti": "Cantautore italiano noto per il suo stile eclettico e testi poetici",
  "Alessandro D'Avenia": "Scrittore e insegnante italiano noto per i suoi romanzi e saggi.",
  "U.Eco": "Scrittore e semiologo italiano, noto per i suoi saggi e romanzi.",
  "Plutarco": "Storico e biografo greco noto per le sue Vite parallele.",
  "Richard Eaton": "Musicista e compositore britannico noto per il coro di Edmonton",
  "Gandalf": "Mago saggio e potente nella saga de Il Signore degli Anelli",
  "Gabriele Amorth": "Esorcista italiano noto per il suo lavoro sul demonio e gli esorcismi",
  "Geraldine Ferraro": "Politica e avvocato statunitense, prima candidata donna vice president",
  "Charles Lindbergh": "Pioniere dell'aviazione noto per il primo volo transatlantico in solit",
  "John Wayne": "Attore americano famoso per i ruoli nel cinema western.",
  "Margherita Hack": "Astrofisica e divulgatrice scientifica italiana di fama",
  "Bela Kiraly": "Calciatore ungherese noto per la sua carriera nelle squadre nazionali ",
  "Bhāgavata Purāṇa": "Antico testo sacro induista che narra storie divine e mitologiche.",
  "Alberto Moravia": "Scrittore italiano noto per opere su società e psicologia umana.",
  "Charles Bukowski": "Scrittore e poeta americano noto per il suo stile crudo e realistico",
  "Ezra Pound": "Poeta e critico statunitense, figura chiave del modernismo.",
  "Mattia Volpe": "Calciatore italiano, giovane talento nel ruolo di attaccante.",
  "Christopher Morley": "Scrittore e giornalista americano noto per opere letterarie e critiche",
  "W.Shakespeare": "Drammaturgo e poeta inglese, autore di opere teatrali classiche.",
  "Émile-Auguste Chartier": "Filosofo e giornalista francese noto come Alain",
  "Marilyn Monroe": "Attrice e icona americana simbolo della bellezza e glamour.",
  "Anonimo": "Persona o autore non identificato",
  "Diogene di Sinope": "Filosofo greco noto per l'ascetismo e la critica sociale.",
  "Franco Forte": "Attore italiano noto per ruoli in televisione e cinema.",
  "Bob Monkhouse": "Comico e presentatore televisivo britannico",
  "Alvin Weinberg": "Fisico americano, pioniere nello sviluppo dell'energia nucleare",
  "Graham Greene": "Scrittore britannico noto per romanzi e opere sullo spionaggio.",
  "Die Hard": "Film d'azione con Bruce Willis come poliziotto a Los Angeles",
  "Cicerone": "Oratore e politico romano celebre per i suoi discorsi e scritti.",
  "Paolina Bonaparte": "Sorella di Napoleone, nota per la sua bellezza e influenza storica",
  "M.Twain": "Scrittore americano noto per \"Le avventure di Tom Sawyer\".",
  "Talmud": "Testo sacro ebraico centrale per la legge ebraica.",
  "Codice d'onore (film)": "Film drammatico che tratta tematiche di lealtà e integrità.",
  "Felicia Hemans": "Poetessa inglese nota per i suoi versi romantici e patriottici.",
  "Michael Corleone": "Personaggio principale della saga Il Padrino, capo mafioso.",
  "Big Banf Theory": "Serie TV comica su scienziati e le loro vite sociali.",
  "\"\"Gangs of New York\"\" (film)": "Film drammatico sulla violenza nelle gang di New York nel XIX secolo",
  "Ernesto Olivero": "Attivista e fondatore del Sermig, impegnato nella pace e solidarietà",
  "Solone": "Antico legislatore e statista ateniese noto per le sue leggi.",
  "A.Pope": "Poeta inglese, noto per le sue opere satiriche e saggistiche.",
  "Quinto Curzio Rufo": "Storico romano noto per la sua opera \"Storia delle guerre puniche\".",
  "Antonio Machado": "Poeta spagnolo rappresentante della Generazione del 98",
  "E.Sottsass": "Designer e architetto italiano, fondatore del gruppo Memphis.",
  "Anton Čechov": "Drammaturgo e scrittore russo, noto per i suoi racconti e opere teatra",
  "W.Churchill": "Statista e leader politico britannico famoso per la Seconda Guerra Mon",
  "Manlio Sgalambro": "Filosofo italiano noto per le sue opere sulla filosofia e la letteratu",
  "Thomas Pynchon": "Scrittore americano noto per romanzi complessi e postmoderni.",
  "\"\"Terminator-3\"\" (film)": "Film di fantascienza con cyborg e viaggi nel tempo",
  "Silvio Pellico": "Scrittore e patriota italiano, noto per \"Le mie prigioni\".",
  "Proverbio africano": "Detto popolare tradizionale dell'Africa con saggezza e insegnamenti.",
  "A.Panzini": "Scrittore e lessicografo italiano noto per vocabolari e opere letterar",
  "A.Shopenghauer": "Filosofo tedesco noto per il pessimismo e la metafisica della volontà",
  "F. Beigbeder": "Scrittore e critico francese noto per romanzi e saggistica culturale.",
  "Wolf's Rain (anime)": "Anime giapponese su lupi che cercano un paradiso nascosto.",
  "\"\"Titanic\"\" (film)": "Film drammatico su una tragedia navale iconica.",
  "Catone": "Politico e oratore romano noto per la sua virtù e rigore morale.",
  "Jacopone da Todi": "Poeta e frate francescano italiano, noto per la lauda religiosa",
  "A.Bierce": "Scrittore e giornalista americano noto per racconti cupi e satira.",
  "Robert Fulton Abernethy": "Imprenditore e produttore televisivo americano.",
  "Isacco di Ninive": "Profeta biblico, noto anche come Nabuccodonosor.",
  "Niccolò Ammaniti": "Scrittore italiano noto per romanzi di realismo contemporaneo",
  "Kristian Wilson": "",
  "E.W.Dijkstra": "Pioniere olandese dell'informatica e della programmazione strutturata",
  "S.Dalí": "Pittore surrealista spagnolo noto per opere oniriche e eccentriche.",
  "Vittorio Feltri": "Giornalista e opinionista italiano, noto per il suo stile polemico.",
  "Alessandro Esseno": "Regista e scrittore italiano, noto per cortometraggi e opere indipende",
  "H.Murakami": "Scrittore giapponese noto per romanzi di realismo magico e surrealismo",
  "Aldo Grasso": "Critico televisivo e giornalista italiano",
  "D.Vergassola": "Comico e attore italiano noto per satira e spettacoli televisivi",
  "William Shakespeare": "Drammaturgo inglese, autore di opere teatrali e poesie celebri",
  "Agostino d'Ippona": "Vescovo e teologo cristiano, noto come Sant'Agostino.",
  "Manlio Scopigno": "Calciatore e allenatore di calcio italiano",
  "Blade Runner (film)": "Film di fantascienza che esplora l'identità umana e i replicanti.",
  "Cesare Pavese": "Scrittore e poeta italiano, noto per opere sulla vita rurale e l'alien",
  "Esopo": "Scrittore di favole della Grecia antica, noto per le sue morali.",
  "Arthur C. Clarke": "Scrittore britannico di fantascienza e futurologo.",
  "Battlestar Galactica": "Serie TV di fantascienza su una flotta umana in fuga dagli Cylon",
  "Edgar Poe": "Scrittore statunitense noto per i racconti di mistero e terrore",
  "Mark Grossman": "Diplomatico americano e ex ambasciatore degli Stati Uniti in Turchia",
  "Locuzione latina": "Espressione fissa della lingua latina utilizzata in vari contesti.",
  "G.Allamano": "Scrittore e sceneggiatore italiano del cinema e della televisione",
  "A.C.Doyle": "Scrittore britannico noto per le storie di Sherlock Holmes",
  "J.Steinbeck": "Scrittore americano noto per romanzi sulla Grande Depressione.",
  "Bilbo Baggins": "Personaggio hobbit protagonista de \"Lo Hobbit\" di J.R.R. Tolkien.",
  "R.Kipling": "Scrittore britannico noto per 'Il libro della giungla'.",
  "E.Jong": "Scrittore noto per i suoi romanzi psicologici e controversi.",
  "John Benfield": "Attore britannico noto per ruoli in film e serie TV",
  "V. Van Gogh": "Pittore post-impressionista olandese famoso per i suoi lavori vibranti",
  "La vita secondo Jim (film)": "Film che esplora la vita quotidiana del personaggio Jim",
  "Bette Davis": "Attrice americana celebre per i ruoli drammatici e l'intensità recitat",
  "Fabrice Hadjadj": "Scrittore e filosofo francese noto per opere su fede e cultura.",
  "Proverbio ebraico": "Saggezza tradizionale ebraica espressa in brevi detti.",
  "Star Trek: Enterprise": "Serie TV di fantascienza ambientata nel primo viaggio spaziale umano",
  "A.Manzoni": "Scrittore italiano noto per il romanzo storico \"I promessi sposi\"",
  "Ignazio di Loyola": "Fondatore della Compagnia di Gesù, riformatore cattolico.",
  "Jean Cocteau": "Artista e scrittore francese famoso per il surrealismo e cinema.",
  "Proverbio zen": "Breve detto con insegnamento legato alla filosofia zen.",
  "Eschilo": "Drammaturgo greco antico, padre della tragedia ateniese.",
  "Papa Benedetto XVI": "Papa emerito della Chiesa cattolica, noto per il pontificato tradizion",
  "Gore Vidal": "Scrittore e saggista americano noto per romanzi e critica sociale.",
  "William Powers": "Autore e saggista statunitense noto per studi su tecnologia e società.",
  "John Condry": "Professore di studi su doppiaggio e media giapponesi",
  "Mauro Covacich": "Scrittore italiano noto per i suoi romanzi e racconti contemporanei.",
  "Modest Oprysko": "",
  "Abraham Lincoln": "16° presidente degli Stati Uniti, noto per l'abolizione della schiavit",
  "Virgilio": "Poeta latino autore dell'Eneide, epica sull'origine di Roma",
  "H.G.Wells": "Scrittore britannico noto per romanzi di fantascienza come La guerra d",
  "F.Algarotti": "Poeta e scrittore italiano del XVIII secolo.",
  "Joker": "Film su un uomo emarginato che diventa un criminale iconico.",
  "Genesi": "Libro sacro che descrive la creazione del mondo nelle religioni abrami",
  "Simone Weil": "Filosofa e attivista francese nota per le sue riflessioni sulla politi",
  "Ch. de Gaulle": "Militare e politico francese, guida della Resistenza e presidente.",
  "Raffaele La Capria": "Scrittore e sceneggiatore italiano noto per opere letterarie e film.",
  "Karekin I": "Patriarca ecumenico della Chiesa armena",
  "Al Hirschfeld": "Illustratore americano noto per caricature di celebrità teatrali.",
  "Carmelo Bene": "Attore e regista italiano noto per il teatro sperimentale.",
  "P.P.Pasolini": "Scrittore, regista e intellettuale italiano noto per opere provocatori",
  "Foghorn Leghorn": "Personaggio di cartone animato, un gallo dal forte accento del Sud."
};
