export default {
  "Proverbio": "Dicho popular que expresa sabiduría o consejo común.",
  "Umberto Eco": "Escritor y filósofo italiano, autor de 'El nombre de la rosa'.",
  "Pablo Picasso": "Pintor y escultor español, cofundador del cubismo.",
  "Voltaire": "Filósofo y escritor francés, figura clave de la Ilustración.",
  "Mark Twain": "Escritor estadounidense conocido por \"Las aventuras de Tom Sawyer\".",
  "Apocalypse Now": "Película de guerra sobre Vietnam dirigida por Francis Ford Coppola.",
  "Miguel Hernández": "Poeta y dramaturgo español, figura clave de la generación del 36.",
  "Les Luthiers": "Grupo musical humorístico argentino conocido por sus instrumentos inve",
  "William Shakespeare": "Dramaturgo y poeta inglés famoso por sus obras teatrales clásicas.",
  "Paul Erdos": "Matemático húngaro conocido por su trabajo en teoría de números y comb",
  "George Orwell": "Escritor británico conocido por sus novelas distópicas y críticas soci",
  "A.Compte": "",
  "Marianne Moore": "Poetisa estadounidense reconocida por su poesía modernista y precisa",
  "Soleares": "Estilo musical flamenco con ritmo lento y emotivo.",
  "The Joker (el Guasón)": "Villano icónico del universo Batman caracterizado por su sonrisa sinie",
  "Richard Feynman": "Físico teórico estadounidense, pionero en la electrodinámica cuántica.",
  "Arthur Schopenhauer": "Filósofo alemán conocido por su obra sobre el pesimismo y la voluntad.",
  "Atribuida a De Gaulle": "Expresión referida a Charles de Gaulle, líder francés.",
  "Harold Wilson": "Político británico y Primer Ministro del Reino Unido",
  "Oscar Wilde": "Escritor irlandés conocido por su ingenio y obras como El retrato de D",
  "Canción infantil": "Composición musical sencilla destinada a niños.",
  "Bruce Lee": "Actor y experto en artes marciales, influyente en cine y cultura.",
  "Prov.1:7": "Versículo bíblico que resalta el temor de Dios como sabiduría.",
  "Tyler Durden (El club de la lucha)": "Personaje principal y anárquico de la novela y película El club de la ",
  "Vinton Cerf": "Pionero del internet y coautor del protocolo TCP/IP.",
  "Siniestro Total": "Banda de punk rock española originaria de Galicia.",
  "Theogonia": "Poema de Hesíodo que narra el origen de los dioses griegos.",
  "Robert Louis Stevenson": "Escritor escocés conocido por sus novelas de aventura clásicas.",
  "R.L.Stevenson": "Escritor escocés conocido por novelas clásicas de aventuras.",
  "Frida Kahlo": "Pintora mexicana famosa por sus autorretratos y arte surrealista.",
  "Woody (Toy Story)": "Muñeco de madera y líder en la saga Toy Story",
  "Alfonso X el Sabio": "Rey de Castilla y León famoso por su impulso cultural y legal",
  "John Fusciante": "Guitarrista estadounidense, conocido por su trabajo con Red Hot Chili ",
  "James D. Watson": "Biólogo estadounidense co-descubridor de la estructura del ADN.",
  "Bulerías": "Cante flamenco rápido y complejo originario de Andalucía",
  "Canción popular vizcaína": "Canción tradicional del País Vasco, expresión cultural musical.",
  "Karl Marx": "Filósofo y economista alemán, fundador del marxismo.",
  "Doctor John Zoidberg (Futurama)": "Personaje cómico y médico crustáceo de la serie Futurama.",
  "Shiki Masaoka": "Escritor japonés conocido por su trabajo en la literatura de terror.",
  "William Osler": "Médico canadiense, pionero en la educación médica moderna.",
  "Frederic Chopin": "Compositor y pianista polaco del periodo romántico.",
  "Delia Quiñonez": "",
  "Billy Elliot": "Película sobre un niño que desea ser bailarín de ballet.",
  "Dante Alighieri": "Poeta italiano, autor de La Divina Comedia.",
  "Ricardo Arjona": "Cantautor guatemalteco conocido por sus letras reflexivas y pop latino",
  "W.Blake": "Poeta y pintor inglés, conocido por sus obras místicas y simbólicas.",
  "John Lennon": "Músico británico, miembro de The Beatles y activista por la paz.",
  "Una noche en la ópera": "Comedia clásica de los Hermanos Marx ambientada en la ópera.",
  "Isidoro de Sevilla (Etimologías)": "Obra enciclopédica medieval de Isidoro de Sevilla que compila saberes.",
  "Charles Dickens": "Escritor inglés famoso por sus novelas sociales y victorianas.",
  "Náufrago, la película": "Película sobre un hombre atrapado en una isla desierta.",
  "H.G.Wells": "Escritor inglés conocido por obras de ciencia ficción clásicas.",
  "Carcelera": "Función de vigilancia en prisiones.",
  "Eduardo Galeano": "Escritor y periodista uruguayo conocido por sus obras sobre historia y",
  "Pierre Corneille": "Dramaturgo francés, uno de los tres grandes del teatro clásico.",
  "Solón": "Legislador y poeta ateniense, fundador de reformas sociales y legales.",
  "Wiki": "Enciclopedia colaborativa en línea de contenido libre.",
  "Cervantes": "Escritor español, autor de Don Quijote, pilar de la literatura.",
  "Atribuido a Tomás de Aquino": "Filósofo y teólogo medieval cristiano, influyente en la escolástica.",
  "Oswald de Andrade": "Escritor y poeta brasileño, líder del modernismo en Brasil.",
  "Enrique Jardiel Poncela": "Dramaturgo y novelista español conocido por su humor ingenioso.",
  "A. de Saint-Exupéry": "Aviador y escritor francés, autor de 'El principito'.",
  "Jean Baptiste Alphonse Karr": "Escritor y periodista francés conocido por sus aforismos y sátiras.",
  "W. Shakespeare": "Dramaturgo y poeta inglés, autor de obras clásicas del teatro.",
  "ToteKing": "Raper español conocido por su lírica aguda y estilo único.",
  "G.K.Chesterton": "Escritor y filósofo inglés conocido por sus ensayos y relatos",
  "Antoine de Saint-Exupéry": "Escritor y aviador francés, autor de 'El Principito'.",
  "Anónimo": "Autor desconocido o sin atribución específica",
  "Inglorious Basterds": "Película de guerra dirigida por Quentin Tarantino sobre soldados en la",
  "Ève Curie": "Escritora y periodista francesa, hija de Marie Curie.",
  "R.Tagore": "Poeta y filósofo indio, autor de 'Gitanjali'.",
  "William Cowper": "Poeta inglés conocido por sus poemas líricos y trabajos en prosa.",
  "Killing Joke": "Banda británica de post-punk y rock alternativo.",
  "José de Espronceda": "Poeta romántico español conocido por su obra apasionada y rebelde.",
  "Clemente de Alejandría": "Teólogo cristiano y apologista de la antigüedad.",
  "J.R.R.Tolkien": "Escritor británico, autor de 'El Señor de los Anillos' y 'El Hobbit'",
  "Albert Einstein": "Físico teórico conocido por la teoría de la relatividad.",
  "The Scorpions": "Banda alemana de rock conocida por sus baladas y éxitos internacionale",
  "D&D": "Juego de rol donde los jugadores crean personajes y aventuras fantásti",
  "Bobby Fischer": "Ajedrecista estadounidense, campeón mundial de ajedrez.",
  "Bella (Amanecer)": "Personaje de la saga Crepúsculo, protagonista principal.",
  "W.Shakespeare": "Dramaturgo y poeta inglés, autor de obras clásicas como Hamlet.",
  "Emilio (Aquí no hay quien viva)": "Personaje de la serie española 'Aquí no hay quien viva', vecino carism",
  "N. Banicevich": "",
  "Edgar Allan Poe": "Escritor estadounidense conocido por sus cuentos de terror y misterio.",
  "Extremoduro": "Banda española de rock conocida por su estilo duro y poético.",
  "L.Margulis": "Bióloga conocida por la teoría de la endosimbiosis en evolución.",
  "Como conocí a vuestra madre": "Serie de comedia sobre la vida y amor de un grupo de amigos en Nueva Y",
  "F.G.Lorca": "Poeta y dramaturgo español destacado en el siglo XX",
  "T.Pratchett": "Autor británico de fantasía y sátira, conocido por Mundodisco.",
  "V (V de Vendetta)": "Superhéroe enmascarado que lucha contra un gobierno totalitario en Rei",
  "Yosa Buson": "Poeta y pintor japonés destacado del periodo Edo.",
  "Alber Camus": "Escritor y filósofo francés, conocido por el existencialismo.",
  "Miguel de Unamuno": "Escritor y filósofo español, figura clave de la Generación del 98.",
  "César Augusto": "Primer emperador romano que consolidó el Imperio Romano.",
  "Friedrich Nietzsche": "Filósofo alemán conocido por sus ideas sobre el nihilismo y la volunta",
  "Trabalenguas": "Frases diseñadas para practicar la pronunciación y dicción.",
  "Marqués de Sade": "Noble francés conocido por sus escritos libertinos y polémicos.",
  "B. O' Higgins": "Revolucionario y líder militar irlandés en la independencia de México.",
  "Enrique Bunbury": "Cantante y compositor español de rock y música alternativa.",
  "Juan Bosch": "Político y escritor dominicano, primer presidente tras dictadura",
  "V de Vendetta": "Película de acción y suspenso sobre un vigilante enmascarado en Inglat",
  "Carl Sagan": "Astrónomo y divulgador científico estadounidense.",
  "Goethe": "Escritor y poeta alemán, autor de obras como Fausto.",
  "J.L.Borges": "Escritor argentino conocido por sus relatos y ensayos literarios.",
  "Confucio": "Filósofo chino cuyo pensamiento influyó en la ética y política.}",
  "Le Corbusier": "Arquitecto y urbanista suizo-francés, pionero del modernismo.",
  "Robert Kennedy": "Político estadounidense y abogado, hermano de John F. Kennedy",
  "Elizabethtown": "Película dramática centrada en un viaje y reconciliaciones familiares.",
  "John Ray": "Naturalista inglés, pionero en la clasificación de plantas y animales.",
  "Giovanni Guareschi": "Escritor y humorista italiano, creador de Don Camilo.",
  "Sandro Pertini": "Político y presidente italiano, símbolo de la resistencia antifascista",
  "Albert Camus": "Escritor y filósofo francés, asociado con el existencialismo y el absu",
  "C.G.Yung": "Psicólogo y psicoanalista suizo, fundador de la psicología analítica.",
  "Brassai": "Fotógrafo húngaro-francés conocido por sus imágenes nocturnas de París",
  "Adam Smith": "Economista y filósofo escocés, padre de la economía moderna.",
  "F.Dostoievski": "Escritor ruso conocido por sus novelas psicológicas y filosóficas.",
  "Samuel Taylor Coleridge": "Poeta y filósofo inglés, figura del romanticismo literario",
  "Erich Fromm": "Psicoanalista y filósofo social alemán-estadounidense.",
  "Edsger Dijkstra": "Informático neerlandés, pionero en algoritmos y programación",
  "La princesa que creía en los cuentos de hadas": "Novela romántica sobre la búsqueda del amor verdadero.",
  "Henri-Frédéric Amiel": "Filósofo y escritor suizo, conocido por su diario íntimo.",
  "Benjamin Franklin": "Político y científico estadounidense, uno de los Padres Fundadores.",
  "Sir Francis Bacon": "Filósofo y estadista inglés, pionero en el método científico.",
  "Johann Christoph Friedrich Von Schiller": "Poeta, dramaturgo y filósofo alemán destacado del Romanticismo.",
  "Francisco de Goya": "Pintor y grabador español, figura clave del arte y la ilustración.",
  "Friedrich Wilhelm Nietzsche.": "Filósofo alemán conocido por su crítica a la moral y la cultura.",
  "Baltasar Gracián": "Escritor y filósofo español, conocido por su obra sobre la prudencia y",
  "Manu Chao": "Músico franco-español conocido por fusión de géneros y letras sociales",
  "Raúl Ferruz": "Investigador y catedrático español en biología celular y molecular.",
  "Clifton Fadiman": "Crítico literario y presentador de radio y televisión estadounidense",
  "Caín, de José Saramago": "Novela de José Saramago basada en la historia bíblica de Caín.",
  "Eshter Thuquiets": "",
  "Rubén Darío": "Poeta nicaragüense, padre del modernismo literario en español.",
  "Jean Giono": "Escritor francés conocido por obras sobre la naturaleza y la Provenza.",
  "Donna Haraway": "Científica y filósofa conocida por su trabajo en feminismo y ciencia.",
  "Lao Tse": "Filósofo chino fundador del taoísmo y autor del Tao Te Ching.",
  "Kobayashi Issa": "Poeta japonés conocido por sus haikus sobre la naturaleza y la vida co",
  "Los Piojos": "Banda de rock argentino conocida por mezclar rock y folclore.",
  "Tim Berners-Lee": "Inventor de la World Wide Web y pionero de internet",
  "Séneca": "Filósofo estoico romano y escritor de tragedias y ensayos morales.",
  "C.Lewis": "Escritor británico conocido por \"Las Crónicas de Narnia\".",
  "A.Machado": "Poeta y ensayista español, figura destacada de la Generación del 98.",
  "Duke Nukem": "Personaje de videojuego conocido por su estilo machista y acción.",
  "Dave Barry": "Escritor y columnista humorístico estadounidense.",
  "François de La Rochefoucauld": "Escritor francés famoso por sus máximas y reflexiones sobre la natural",
  "Arquímedes de Siracusa": "Matemático y físico griego, fundador de la hidrostática y la palanca.",
  "Kris Roe": "Cantante y músico estadounidense, líder de la banda The Ataris.",
  "Quilón de Esparta": "Antiguo gobernante de Esparta en la mitología griega.",
  "Drake (Drake & Josh)": "Personaje principal de la serie juvenil 'Drake & Josh'.",
  "Alphonse Allais": "Ensayista y humorista francés conocido por su humor absurdo.",
  "Kaga no Chiyo": "Poetisa japonesa reconocida por sus haikus clásicos.",
  "Terry Pratchett": "Escritor británico conocido por la serie de fantasía 'Mundodisco'.",
  "R.Kurzweil": "Inventor y futurista conocido por sus predicciones tecnológicas.",
  "Héctor del Mar": "Presentador y locutor español conocido por narrar deportes.",
  "Himno Homérico a Ares": "Poema antiguo que alaba al dios griego de la guerra, Ares.",
  "Ramón Gómez de la Serna": "Escritor español, precursor del esperpento y la literatura vanguardist",
  "Woody Allen": "Director y actor estadounidense conocido por sus comedias y dramas.",
  "Fred Allen": "Comediante y presentador de radio estadounidense famoso por su humor.",
  "Anatole France": "Escritor francés conocido por sus novelas y ensayos literarios.",
  "F. Nitzche": "Filósofo alemán conocido por su crítica cultural y filosofía del poder",
  "N.Gaiman (Sandman)": "Autor británico conocido por la serie de cómics 'Sandman'.",
  "The Ramones": "Banda estadounidense pionera del punk rock",
  "Stephenie Meyer": "Autora estadounidense conocida por la serie 'Crepúsculo'.",
  "Jorge Wagensberg": "Científico y divulgador español conocido por su trabajo en física y mu",
  "Clint Eastwood (The Rookie)": "Actor y director estadounidense, protagonizó 'The Rookie'.",
  "José Angel Buesa": "Poeta y escritor cubano conocido por su lírica romántica.",
  "Walt Disney": "Pionero estadounidense del cine de animación y fundador de Disney.",
  "Bertolt Brecht": "Dramaturgo y poeta alemán, creador del teatro épico.",
  "Steven Wright": "Comediante estadounidense conocido por su humor seco y pausado.",
  "Isabel Allende": "Escritora chilena conocida por sus novelas de realismo mágico.",
  "Bertrand Russell": "Filósofo y matemático británico, influyente en lógica y epistemología.",
  "Zapp (Futurama)": "Robot conductor en la serie animada Futurama.",
  "Maximiliano Hernández Martínez": "Político y militar salvadoreño, presidente de El Salvador en el siglo ",
  "Rafael Alberti": "Poeta y dramaturgo español destacado de la Generación del 27.",
  "W.Churchill": "Primer ministro británico famoso por su liderazgo en la Segunda Guerra",
  "Pablo Neruda": "Poeta chileno, conocido por su poesía apasionada y compromiso político",
  "Lord Byron": "Poeta inglés del Romanticismo, conocido por su vida y obras apasionada",
  "V.Hugo": "Escritor francés famoso por obras como \"Los Miserables\".",
  "Norm Coleman": "Político estadounidense, exalcalde de Saint Paul y senador por Minneso",
  "N. Parra": "Poeta y antipoeta chileno, influyente en la literatura contemporánea.",
  "William Faulkner": "Escritor estadounidense reconocido por sus novelas sobre el sur profun",
  "Luis Alfredo Arango": "Poeta y escritor guatemalteco reconocido por su obra literaria",
  "Jonathan Swift": "Escritor irlandés famoso por 'Los viajes de Gulliver'.",
  "DRAE": "Diccionario oficial de la lengua española de la RAE.",
  "Thomas Fuller": "Escritor y clérigo inglés conocido por proverbios y aforismos.",
  "David Herbert Lawrence": "Escritor inglés conocido por sus novelas y poesía de temas sociales y ",
  "Joseph Addison": "Escritor y político inglés, conocido por sus ensayos y obras teatrales",
  "Khalil Gibran": "Poeta y filósofo libanés, autor de 'El Profeta'.",
  "Françoise Sagan": "Escritora francesa conocida por su novela 'Bonjour Tristesse'.",
  "Márquez": "Escritor colombiano famoso por 'Cien años de soledad'.",
  "Bahá'u'lláh": "Fundador de la fe bahá'í y escritor religioso persa",
  "Tres leyes de la robótica": "Principios éticos que rigen el comportamiento de robots según Asimov.",
  "F.Kafka": "Escritor checo de obras emblemáticas sobre la burocracia y la alienaci",
  "Barbara Jordan": "Política y activista estadounidense por derechos civiles y justicia.",
  "Jacques Lacan": "Psicoanalista francés influyente en teoría psicoanalítica moderna",
  "León Tolstói": "Escritor ruso famoso por 'Guerra y Paz' y 'Ana Karenina'.",
  "Marco Tulio Cicerón": "Orador, político y filósofo romano conocido por sus discursos y escrit",
  "Aristóteles": "Filósofo griego que influyó en lógica, ética y ciencias.",
  "Refran": "Dicho popular con enseñanza moral o práctica.",
  "Molière": "Dramaturgo francés famoso por sus comedias clásicas teatrales.",
  "Paul Carvel": "Personaje ficticio de libros de aventuras para niños",
  "Honoré De Balzac": "Escritor francés, autor de 'La Comedia Humana', realismo literario.",
  "Demófilo": "Folklorista y etnógrafo español especializado en tradiciones populares",
  "John Steinbeck": "Escritor estadounidense conocido por sus novelas realistas y sociales.",
  "Esther M. Clark": "",
  "Henry F. Amiel": "Filósofo y escritor suizo conocido por sus diarios personales.",
  "Julio Verne": "Escritor francés conocido por sus novelas de aventuras y ciencia ficci",
  "San Agustín": "Teólogo y filósofo cristiano, influencia clave en la Iglesia.",
  "Valeriu Butulescu": "Poeta y ensayista rumano contemporáneo.",
  "\"\"Frida\"\" (Original Soundtrack)": "Banda sonora de la película sobre la artista Frida Kahlo.",
  "Ray Bradbury": "Escritor estadounidense conocido por sus obras de ciencia ficción.",
  "Juan Ramón Jiménez": "Poeta y ensayista español, Premio Nobel de Literatura.",
  "Robert Frost": "Poeta estadounidense famoso por sus poemas sobre la naturaleza.",
  "William Thomson Kelvin": "Físico y matemático británico conocido por la escala Kelvin de tempera",
  "The Watchman": "Serie de televisión de suspense basada en cómics de superhéroes",
  "F.Nietzshe": "Filósofo alemán conocido por su crítica de la moral tradicional",
  "Bill Hicks": "Comediante y satírico estadounidense conocido por su humor crítico.",
  "Buffy Vampire Slayer": "Serie sobre una joven cazavampiros que lucha contra el mal.",
  "Platón": "Filósofo griego fundador de la Academia y autor de diálogos filosófico",
  "H.Miller": "Escritor estadounidense conocido por la novela 'Trópico de Cáncer'.",
  "Charles Baudelaire": "Poeta francés conocido por 'Las flores del mal', símbolo del modernism",
  "Federico Jiménez Losantos": "Periodista y escritor español conocido por su actividad en medios y po",
  "Angelo Anfossi Mera": "Compositor italiano conocido por sus óperas clásicas.",
  "Bernard Shaw": "Dramaturgo y crítico irlandés, famoso por sus obras satíricas.",
  "José Martí": "Poeta y revolucionario cubano, figura clave en la independencia de Cub",
  "Antonio Frondizi": "Político y jurista argentino, presidente de Argentina.",
  "Emilio Visconti": "Nombre italiano posiblemente asociado a la familia Visconti.",
  "Mahatma Gandhi": "Líder pacifista y figura clave en la independencia de India",
  "Drácula por Bram Stocker": "Novela gótica sobre un vampiro llamado Conde Drácula.",
  "Proverbio sanscrito": "Dicho tradicional originario de la antigua India en sánscrito.",
  "Blaise Pascal": "Filósofo, matemático y físico francés, contribuyó a la ciencia y relig",
  "Metrópolis": "Película alemana clásica de ciencia ficción y expresión visual.",
  "William Blake": "Poeta y artista inglés conocido por su visión mística y obras ilustrad",
  "Francisco de Quevedo": "Escritor y poeta español del Siglo de Oro, conocido por su sátira.",
  "La Biblia": "Libro sagrado del cristianismo y judaísmo con enseñanzas religiosas.",
  "G.B.Shaw": "Dramaturgo y crítico irlandés, famoso por sus obras sociales.",
  "Atahualpa Yupanqui": "Músico y poeta argentino, destacado en el folclore andino.",
  "Vicente Huidobro": "Poeta chileno, fundador del creacionismo en la literatura.",
  "Pinocho": "Personaje de cuento infantil cuyo nariz crece al mentir.",
  "Victor Hugo": "Escritor y poeta francés destacado del Romanticismo.",
  "Alphonse de Lamartine": "Poeta y político francés del Romanticismo.",
  "Thulsa Doom (Conan el bárbaro)": "Villano en la serie Conan el bárbaro, líder culto y poderoso.",
  "Stephen Hawking": "Físico teórico británico conocido por sus trabajos sobre agujeros negr",
  "Margaret Thatcher": "Primera ministra británica, líder conservadora y figura clave política",
  "Jack Sparrow": "Pirata ficticio protagonista de la serie de películas \"Piratas del Car",
  "Sir Walter Scott": "Escritor escocés conocido por novelas históricas y poesía.",
  "El Cid Campeador": "Héroe y líder militar castellano de la Reconquista",
  "Denis Diderot": "Filósofo francés, autor de la Enciclopedia y figura clave del Iluminis",
  "Proverbio alemán": "Dicho tradicional que expresa sabiduría popular alemana.",
  "C.S.Lewis": "Escritor británico conocido por 'Las Crónicas de Narnia'.",
  "C.Castaneda": "Escritor y antropólogo conocido por sus libros sobre chamanismo.",
  "Jaime Balmes": "Filósofo y teólogo español del siglo XIX.",
  "Masajo Suzuki": "Jugador de fútbol japonés",
  "Sir Laurence Olivier": "Actor y director teatral y cinematográfico británico reconocido.",
  "Bela Kiraly": "Jugador y entrenador de fútbol húngaro reconocido",
  "Norman Vincent Peale": "Autor y predicador conocido por promover el pensamiento positivo.",
  "Da Vinci": "Artista e inventor italiano del Renacimiento",
  "H.Heine": "Poeta y escritor alemán conocido por su lirismo y sátira.",
  "H.A.Keller": "",
  "Samuel Butler": "Escritor inglés conocido por novelas satíricas y críticas sociales.",
  "Herman Hesse": "Escritor y poeta alemán-suizo, conocido por 'El lobo estepario'.",
  "H.Murakami": "Escritor japonés conocido por sus novelas que mezclan realismo y surre",
  "A.Einstein": "Físico teórico conocido por la teoría de la relatividad.",
  "Michael Palmer": "Autor estadounidense de novelas de suspenso médico.",
  "Henry Ford": "Industriales estadounidense, pionero en la producción en cadena",
  "Matsuo Basho": "Poeta japonés renombrado por sus haikus.",
  "Anime \"\"Rurouni Kenshin\"\"": "Serie de anime sobre un samurái vagabundo con un pasado oscuro.",
  "A.Burgess": "Escritor inglés conocido por obras distópicas y críticas sociales.",
  "R.Kipling": "Escritor británico conocido por 'El libro de la selva'.",
  "Bonnie (Toy Story 3)": "Niña que se convierte en la nueva dueña de los juguetes de Andy.",
  "Isaac Asimov": "Escritor y bioquímico conocido por sus obras de ciencia ficción y divu",
  "Miguel De Cervantes Saavedra": "Escritor español, autor de Don Quijote, figura clave del Siglo de Oro.",
  "Rafael Moneo": "Arquitecto español reconocido por diseños modernos y funcionales",
  "Jean Jacques Rousseau": "Filósofo y escritor suizo-francés influyente en la Ilustración",
  "A.G.Bell": "Inventor y pionero en telecomunicaciones, creador del teléfono moderno",
  "Ayn Rand": "Escritora y filósofa conocida por el objetivismo y 'La rebelión de Atl",
  "Yuji Ishiyama": "Personaje ficticio japonés",
  "F.Chopin": "Compositor y pianista polaco del Romanticismo",
  "Proverbio zen": "Breve frase con enseñanza profunda en la tradición zen budista.",
  "Aldous Huxley": "Escritor inglés conocido por su novela distópica 'Un mundo feliz'.",
  "Lucrecio": "Filósofo romano conocido por su obra sobre epicureísmo y naturaleza.",
  "George Herbert": "Poeta y sacerdote anglicano inglés del Barroco",
  "Jean Cocteau": "Artista francés polifacético: poeta, dramaturgo y cineasta.",
  "Richard Bach": "Escritor estadounidense conocido por 'Juan Salvador Gaviota'.",
  "George Washington": "Primer presidente de Estados Unidos y líder revolucionario.",
  "Basho": "Poeta japonés conocido por sus haikus innovadores.",
  "N.Maquiavelo": "Político y filósofo italiano, autor de 'El Príncipe'.",
  "Doménico Cieri Estrada": "Diplomático y académico mexicano reconocido en política internacional",
  "G.Flaubert": "Escritor francés famoso por su obra \"Madame Bovary\".",
  "F.Fellini": "Director italiano famoso por películas surrealistas y oníricas.",
  "Stendhal": "Escritor francés, autor de 'Rojo y negro' y 'La cartuja de Parma'.",
  "Alejandro Dumas": "Escritor francés conocido por obras como 'Los tres mosqueteros'.",
  "Homer J. Simpson": "Personaje principal de la serie animada Los Simpson.",
  "I.Allende": "Escritora chilena conocida por sus novelas de realismo mágico.",
  "Luis Rojas Marcos": "Psiquiatra español reconocido por su trabajo en salud mental pública.",
  "Salvador Dalí": "Pintor surrealista español conocido por sus obras oníricas y extravaga",
  "El espinazo del diablo": "Película española de terror dirigida por Guillermo del Toro.",
  "Milan Kundera": "Escritor checo-francés conocido por novelas filosóficas y satíricas.",
  "Sherlock Holmes": "Detective ficticio británico creado por Arthur Conan Doyle.",
  "Fullmetal alchemist (manga)": "Manga de aventura y alquimia creado por Hiromu Arakawa.",
  "Joseph Joubert": "Ensayista y moralista francés conocido por sus aforismos y pensamiento",
  "Lao Tse.": "Filósofo chino, fundador del taoísmo y autor del Tao Te Ching.",
  "Abraham Lincoln": "Presidente de Estados Unidos conocido por abolir la esclavitud.",
  "John Osborne": "Dramaturgo británico destacado por obras que influyeron en el teatro m",
  "Elie Wiesel": "Escritor y activista por los derechos humanos, sobreviviente del Holoc",
  "8:01": "Película sobre los ataques del 11 de septiembre y sus efectos.",
  "Ludwig van Beethoven": "Compositor y pianista alemán, figura clave del clasicismo y romanticis",
  "Henry Fairfield Osborn": "Paleontólogo y geólogo estadounidense, experto en dinosaurios.",
  "Roberto Fontanarrosa": "Humorista gráfico y escritor argentino, famoso por sus personajes y cu",
  "Ángel Santos": "Nombre común que puede referirse a varias personas.",
  "Hudson (Aliens)": "Nave espacial en la película Aliens famosa por su destrucción.",
  "Joaquín Sabina": "Cantautor español conocido por sus letras poéticas y urbanas",
  "Marqués de Vauvenargues": "Filósofo y escritor francés conocido por sus aforismos sobre la moral ",
  "Brian Molko": "Cantante y líder de la banda británica Placebo.",
  "Arthur C. Clarke": "Escritor británico de ciencia ficción y futurista reconocido",
  "John Alexander Tristram": "",
  "Napoleón Bonaparte": "Líder militar y emperador francés famoso por sus conquistas",
  "Enzo Ferrari": "Fundador de Ferrari y leyenda del automovilismo italiano",
  "Bjarne Stoustrup": "Programador danés, creador del lenguaje C++.",
  "Proclo": "Filósofo neoplatónico griego conocido por sus obras sobre Platón.",
  "Jaime Luciano Balmes": "Filósofo y teólogo español del siglo XIX",
  "Simón Bolívar": "Líder militar y político que liberó varios países sudamericanos",
  "Ernest Hemingway": "Escritor estadounidense, conocido por su estilo sencillo y obras clási",
  "Denis Leary": "Actor y comediante estadounidense conocido por su humor irreverente",
  "Proverbio turco": "Dicho tradicional turco que expresa sabiduría popular.",
  "C.Casanova": "Aventurero y escritor italiano famoso por sus memorias.",
  "Paul Samuelson": "Economista estadounidense, primer ganador del Premio Nobel en Economía",
  "Martín Lutero": "Teólogo alemán y líder de la Reforma protestante",
  "Henri Barbusse": "Escritor y periodista francés, conocido por su novela 'El fuego'.",
  "Dante": "Poeta italiano conocido por la obra 'La Divina Comedia'.",
  "Muhammad Ali": "Boxeador estadounidense, considerado uno de los mejores pesos pesados",
  "Winston Churchill": "Político y estadista británico, líder durante la Segunda Guerra Mundia",
  "Henry Jekyll": "Personaje ficticio de Stevenson que representa doble personalidad.",
  "Proverbio chino": "Dicho tradicional que ofrece sabiduría y consejos en cultura china.",
  "El Perich": "Humorista gráfico y caricaturista español conocido por sus dibujos sat",
  "Jacques H. de la Lacreitelle": "Escritor y periodista francés reconocido por su obra literaria.",
  "Robert Burton": "Escritor y clérigo inglés, autor de 'La anatomía de la melancolía'.",
  "A.Burgess (La naranja mecánica)": "Autor de la novela distópica La naranja mecánica.",
  "A.Huxley": "Escritor británico conocido por su novela distópica 'Un mundo feliz'.",
  "Herbert Marshall McLuhan": "Teórico canadiense de la comunicación, conocido por 'el medio es el me",
  "Ramón de Campoamor": "Poeta y filósofo español, conocido por sus décimas y ensayo.",
  "M.Twain": "Escritor estadounidense conocido por 'Las aventuras de Tom Sawyer'.",
  "Cristóbal Colon": "Navegante italiano que descubrió América para España.",
  "Alexandre Dumas (padre)": "Escritor francés famoso por 'Los tres mosqueteros' y novelas histórica",
  "Laura Esquivel": "Escritora mexicana conocida por su novela 'Como agua para chocolate'.",
  "H. de Balzac": "Escritor francés, destacado exponente del realismo literario.",
  "Berenice Abbott": "Fotógrafa estadounidense reconocida por documentación urbana y científ",
  "Michel de Montaigne": "Filósofo francés conocido por sus ensayos sobre la condición humana.",
  "Refrán": "Expresión breve que transmite sabiduría popular o consejo.",
  "E.Hemingway": "Escritor estadounidense, autor de 'El viejo y el mar'.",
  "Adolfo Suárez": "Político español, primer presidente del gobierno tras la dictadura fra",
  "Lin Yutang": "Escritor y traductor chino conocido por sus obras sobre cultura china.",
  "Atribuido a Julio César": "Obras o acciones generalmente relacionadas con Julio César, líder roma",
  "Luis Buñuel": "Director y guionista español, pionero del cine surrealista.",
  "A.G.Quinde": "",
  "J. Rowling": "Autora británica famosa por la serie de libros de Harry Potter.",
  "Gottfried Benn": "Poeta y ensayista alemán del siglo XX.",
  "\"\"Alejo y Valentina\"\"": "Serie animada argentina de humor y situaciones cotidianas",
  "Amos Bronson Alcott": "Educador y filósofo estadounidense, pionero del trascendentalismo.",
  "Tácito": "Historiador y político romano famoso por sus obras sobre el Imperio ro",
  "Chuck Palahniuk": "Escritor estadounidense conocido por su novela 'El club de la lucha'.",
  "Edgar Poe": "Escritor estadounidense conocido por sus cuentos de terror y misterio.",
  "Proverbio noruego": "Dicho popular que transmite sabiduría tradicional noruega.",
  "Averroes": "Filósofo y médico andalusí, exponente del pensamiento islámico",
  "Alan Lewis": "Nombre común sin referencia clara a una persona específica",
  "Domingo Faustino Sarmiento": "Político y educador argentino, impulsor de la educación pública",
  "Buda Gautama": "Fundador del budismo, maestro espiritual y guía de sabiduría",
  "Jean-Luc Godard": "Director y cineasta francés, pionero de la Nouvelle Vague.",
  "J. Steinbeck": "Novelista estadounidense conocido por \"Las uvas de la ira\".",
  "Alan Turing": "Matemático y pionero en informática y criptografía británico",
  "Vicente Fox (ex Presidente de México)": "Político mexicano, ex presidente de México reconocido por reformas eco"
};
